### Admin API V1.0 placeholder

GET http://localhost:5214/admin/api/v1.0/placeholder
Accept: application/json

### Public API V1.0 placeholder

GET http://localhost:5214/public/api/v1.0/placeholder
Accept: application/json
