### Admin API V0.1 placeholder

POST http://localhost:5214/admin/api/v0.1/contests
Accept: application/json
Content-Type: application/json

{
  "contestYear": 2025,
  "hostCityName": "Basel",
  "votingRules": "Liverpool"
}

### Public API V0.1 placeholder

GET http://localhost:5214/public/api/v0.1/voting-country-rankings/points-share?targetCountryCode=GB&votingMethod=Jury
Accept: application/json
