// <auto-generated />
using System;
using Eurocentric.Infrastructure.DataAccess.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eurocentric.Infrastructure.DataAccess.EfCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250730130605_Add_v0_country_tables")]
    partial class Add_v0_country_tables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Eurocentric.Domain.V0Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .HasColumnName("country_code")
                        .IsFixedLength();

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("country_name");

                    b.HasKey("Id")
                        .HasName("pk_country");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasAlternateKey("CountryCode")
                        .HasName("ak_country_country_code");

                    b.ToTable("country", "v0");
                });

            modelBuilder.Entity("Eurocentric.Domain.V0Entities.Country", b =>
                {
                    b.OwnsMany("Eurocentric.Domain.V0Entities.ContestMemo", "ParticipatingContestIds", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasColumnName("id");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("ContestId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("participating_contest_id");

                            b1.Property<Guid>("CountryId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("country_id");

                            b1.HasKey("Id")
                                .HasName("pk_country_participating_contest");

                            SqlServerKeyBuilderExtensions.IsClustered(b1.HasKey("Id"));

                            b1.HasIndex("CountryId")
                                .HasDatabaseName("ix_country_participating_contest_country_id");

                            b1.ToTable("country_participating_contest", "v0");

                            b1.WithOwner()
                                .HasForeignKey("CountryId")
                                .HasConstraintName("fk_country_participating_contest_country_country_id");
                        });

                    b.Navigation("ParticipatingContestIds");
                });
#pragma warning restore 612, 618
        }
    }
}
