// <auto-generated />
using System;
using Eurocentric.Infrastructure.DataAccess.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eurocentric.Infrastructure.DataAccess.EfCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250730131732_Add_v0_contest_tables")]
    partial class Add_v0_contest_tables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Eurocentric.Domain.V0Entities.Contest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("city_name");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit")
                        .HasColumnName("completed");

                    b.Property<int>("ContestFormat")
                        .HasColumnType("int")
                        .HasColumnName("contest_format");

                    b.Property<int>("ContestYear")
                        .HasColumnType("int")
                        .HasColumnName("contest_year");

                    b.HasKey("Id")
                        .HasName("pk_contest");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasAlternateKey("ContestYear")
                        .HasName("ak_contest_contest_year");

                    b.ToTable("contest", "v0");
                });

            modelBuilder.Entity("Eurocentric.Domain.V0Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .HasColumnName("country_code")
                        .IsFixedLength();

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("country_name");

                    b.HasKey("Id")
                        .HasName("pk_country");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasAlternateKey("CountryCode")
                        .HasName("ak_country_country_code");

                    b.ToTable("country", "v0");
                });

            modelBuilder.Entity("Eurocentric.Domain.V0Entities.Contest", b =>
                {
                    b.OwnsMany("Eurocentric.Domain.V0Entities.ChildBroadcast", "ChildBroadcasts", b1 =>
                        {
                            b1.Property<Guid>("ContestId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("contest_id");

                            b1.Property<Guid>("BroadcastId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("broadcast_id");

                            b1.Property<bool>("Completed")
                                .HasColumnType("bit")
                                .HasColumnName("completed");

                            b1.Property<int>("ContestStage")
                                .HasColumnType("int")
                                .HasColumnName("contest_stage");

                            b1.HasKey("ContestId", "BroadcastId")
                                .HasName("pk_contest_child_broadcast");

                            SqlServerKeyBuilderExtensions.IsClustered(b1.HasKey("ContestId", "BroadcastId"));

                            b1.HasIndex("ContestId", "ContestStage")
                                .IsUnique()
                                .HasDatabaseName("ix_contest_child_broadcast_contest_id_contest_stage");

                            b1.ToTable("contest_child_broadcast", "v0");

                            b1.WithOwner()
                                .HasForeignKey("ContestId")
                                .HasConstraintName("fk_contest_child_broadcast_contest_contest_id");
                        });

                    b.OwnsMany("Eurocentric.Domain.V0Entities.Participant", "Participants", b1 =>
                        {
                            b1.Property<Guid>("ContestId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("contest_id");

                            b1.Property<Guid>("ParticipatingCountryId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("participating_country_id");

                            b1.Property<string>("ActName")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("act_name");

                            b1.Property<int>("ParticipantGroup")
                                .HasColumnType("int")
                                .HasColumnName("participant_group");

                            b1.Property<string>("SongTitle")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("song_title");

                            b1.HasKey("ContestId", "ParticipatingCountryId")
                                .HasName("pk_contest_participant");

                            SqlServerKeyBuilderExtensions.IsClustered(b1.HasKey("ContestId", "ParticipatingCountryId"));

                            b1.ToTable("contest_participant", "v0");

                            b1.WithOwner()
                                .HasForeignKey("ContestId")
                                .HasConstraintName("fk_contest_participant_contest_contest_id");
                        });

                    b.Navigation("ChildBroadcasts");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Eurocentric.Domain.V0Entities.Country", b =>
                {
                    b.OwnsMany("Eurocentric.Domain.V0Entities.ContestMemo", "ParticipatingContestIds", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasColumnName("id");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("ContestId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("participating_contest_id");

                            b1.Property<Guid>("CountryId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("country_id");

                            b1.HasKey("Id")
                                .HasName("pk_country_participating_contest");

                            SqlServerKeyBuilderExtensions.IsClustered(b1.HasKey("Id"));

                            b1.HasIndex("CountryId")
                                .HasDatabaseName("ix_country_participating_contest_country_id");

                            b1.ToTable("country_participating_contest", "v0");

                            b1.WithOwner()
                                .HasForeignKey("CountryId")
                                .HasConstraintName("fk_country_participating_contest_country_country_id");
                        });

                    b.Navigation("ParticipatingContestIds");
                });
#pragma warning restore 612, 618
        }
    }
}
