// <auto-generated />
using System;
using Eurocentric.Infrastructure.DataAccess.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eurocentric.Infrastructure.DataAccess.EfCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250706093734_AddPlaceholderContestTable")]
    partial class AddPlaceholderContestTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Eurocentric.Domain.PlaceholderEntities.Contest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("city_name");

                    b.Property<int>("ContestFormat")
                        .HasColumnType("int")
                        .HasColumnName("contest_format");

                    b.Property<int>("ContestYear")
                        .HasColumnType("int")
                        .HasColumnName("contest_year");

                    b.HasKey("Id")
                        .HasName("pk_placeholder_contest");

                    b.HasAlternateKey("ContestYear")
                        .HasName("ak_placeholder_contest_contest_year");

                    b.ToTable("placeholder_contest", null, t =>
                        {
                            t.HasCheckConstraint("ck_placeholder_contest_contest_format_enum", "[contest_format] IN (0,1)");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
