// <auto-generated />
using System;
using Eurocentric.Infrastructure.DataAccess.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eurocentric.Infrastructure.DataAccess.EfCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250715161144_AddBroadcastAggregateTables")]
    partial class AddBroadcastAggregateTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Eurocentric.Domain.Aggregates.Broadcasts.Broadcast", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateOnly>("BroadcastDate")
                        .HasColumnType("date")
                        .HasColumnName("broadcast_date");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit")
                        .HasColumnName("completed");

                    b.Property<int>("ContestStage")
                        .HasColumnType("int")
                        .HasColumnName("contest_stage");

                    b.Property<Guid>("ParentContestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("parent_contest_id");

                    b.HasKey("Id")
                        .HasName("pk_broadcast");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("ParentContestId", "ContestStage")
                        .IsUnique()
                        .HasDatabaseName("ix_broadcast_parent_contest_id_contest_stage");

                    b.ToTable("broadcast", null, t =>
                        {
                            t.HasCheckConstraint("ck_broadcast_contest_stage_enum", "[contest_stage] IN (0,1,2)");
                        });
                });

            modelBuilder.Entity("Eurocentric.Domain.Aggregates.Contests.Contest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("city_name");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit")
                        .HasColumnName("completed");

                    b.Property<int>("ContestFormat")
                        .HasColumnType("int")
                        .HasColumnName("contest_format");

                    b.Property<int>("ContestYear")
                        .HasColumnType("int")
                        .HasColumnName("contest_year");

                    b.HasKey("Id")
                        .HasName("pk_contest");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasAlternateKey("ContestYear")
                        .HasName("ak_contest_contest_year");

                    b.ToTable("contest", null, t =>
                        {
                            t.HasCheckConstraint("ck_contest_contest_format_enum", "[contest_format] IN (0,1)");
                        });

                    b.HasDiscriminator<int>("ContestFormat").IsComplete(true);

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Eurocentric.Domain.Aggregates.Countries.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .HasColumnName("country_code")
                        .IsFixedLength();

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("country_name");

                    b.HasKey("Id")
                        .HasName("pk_country");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasAlternateKey("CountryCode")
                        .HasName("ak_country_country_code");

                    b.ToTable("country", (string)null);
                });

            modelBuilder.Entity("Eurocentric.Domain.PlaceholderEntities.Contest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("city_name");

                    b.Property<int>("ContestFormat")
                        .HasColumnType("int")
                        .HasColumnName("contest_format");

                    b.Property<int>("ContestYear")
                        .HasColumnType("int")
                        .HasColumnName("contest_year");

                    b.HasKey("Id")
                        .HasName("pk_placeholder_contest");

                    b.HasAlternateKey("ContestYear")
                        .HasName("ak_placeholder_contest_contest_year");

                    b.ToTable("placeholder_contest", null, t =>
                        {
                            t.HasCheckConstraint("ck_placeholder_contest_contest_format_enum", "[contest_format] IN (0,1)");
                        });
                });

            modelBuilder.Entity("Eurocentric.Domain.PlaceholderEntities.QueryableCountry", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .HasColumnName("country_code")
                        .IsFixedLength();

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("country_name");

                    b.HasKey("CountryCode")
                        .HasName("pk_placeholder_queryable_country");

                    b.ToTable("placeholder_queryable_country", (string)null);
                });

            modelBuilder.Entity("Eurocentric.Domain.PlaceholderEntities.QueryableJuryAward", b =>
                {
                    b.Property<string>("CompetingCountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .HasColumnName("competing_country_code")
                        .IsFixedLength();

                    b.Property<string>("VotingCountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .HasColumnName("voting_country_code")
                        .IsFixedLength();

                    b.Property<int>("ContestYear")
                        .HasColumnType("int")
                        .HasColumnName("contest_year");

                    b.Property<int>("ContestStage")
                        .HasColumnType("int")
                        .HasColumnName("contest_stage");

                    b.Property<string>("BroadcastTag")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("broadcast_tag");

                    b.Property<int>("MaxPointsValue")
                        .HasColumnType("int")
                        .HasColumnName("max_points_value");

                    b.Property<double>("NormalizedPointsValue")
                        .HasColumnType("float")
                        .HasColumnName("normalized_points_value");

                    b.Property<int>("PointsValue")
                        .HasColumnType("int")
                        .HasColumnName("points_value");

                    b.Property<double>("RealPointsValue")
                        .HasColumnType("float")
                        .HasColumnName("real_points_value");

                    b.Property<int>("RunningOrderPosition")
                        .HasColumnType("int")
                        .HasColumnName("running_order_position");

                    b.HasKey("CompetingCountryCode", "VotingCountryCode", "ContestYear", "ContestStage")
                        .HasName("pk_placeholder_queryable_jury_award");

                    b.HasIndex("CompetingCountryCode")
                        .HasDatabaseName("ix_placeholder_queryable_jury_award_competing_country_code");

                    b.HasIndex("ContestStage")
                        .HasDatabaseName("ix_placeholder_queryable_jury_award_contest_stage");

                    b.HasIndex("ContestYear")
                        .HasDatabaseName("ix_placeholder_queryable_jury_award_contest_year");

                    b.HasIndex("VotingCountryCode")
                        .HasDatabaseName("ix_placeholder_queryable_jury_award_voting_country_code");

                    b.ToTable("placeholder_queryable_jury_award", null, t =>
                        {
                            t.HasCheckConstraint("ck_placeholder_queryable_jury_award_contest_stage_enum", "[contest_stage] IN (0,1,2)");
                        });
                });

            modelBuilder.Entity("Eurocentric.Domain.PlaceholderEntities.QueryableTelevoteAward", b =>
                {
                    b.Property<string>("CompetingCountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .HasColumnName("competing_country_code")
                        .IsFixedLength();

                    b.Property<string>("VotingCountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .HasColumnName("voting_country_code")
                        .IsFixedLength();

                    b.Property<int>("ContestYear")
                        .HasColumnType("int")
                        .HasColumnName("contest_year");

                    b.Property<int>("ContestStage")
                        .HasColumnType("int")
                        .HasColumnName("contest_stage");

                    b.Property<string>("BroadcastTag")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("broadcast_tag");

                    b.Property<int>("MaxPointsValue")
                        .HasColumnType("int")
                        .HasColumnName("max_points_value");

                    b.Property<double>("NormalizedPointsValue")
                        .HasColumnType("float")
                        .HasColumnName("normalized_points_value");

                    b.Property<int>("PointsValue")
                        .HasColumnType("int")
                        .HasColumnName("points_value");

                    b.Property<double>("RealPointsValue")
                        .HasColumnType("float")
                        .HasColumnName("real_points_value");

                    b.Property<int>("RunningOrderPosition")
                        .HasColumnType("int")
                        .HasColumnName("running_order_position");

                    b.HasKey("CompetingCountryCode", "VotingCountryCode", "ContestYear", "ContestStage")
                        .HasName("pk_placeholder_queryable_televote_award");

                    b.HasIndex("CompetingCountryCode")
                        .HasDatabaseName("ix_placeholder_queryable_televote_award_competing_country_code");

                    b.HasIndex("ContestStage")
                        .HasDatabaseName("ix_placeholder_queryable_televote_award_contest_stage");

                    b.HasIndex("ContestYear")
                        .HasDatabaseName("ix_placeholder_queryable_televote_award_contest_year");

                    b.HasIndex("VotingCountryCode")
                        .HasDatabaseName("ix_placeholder_queryable_televote_award_voting_country_code");

                    b.ToTable("placeholder_queryable_televote_award", null, t =>
                        {
                            t.HasCheckConstraint("ck_placeholder_queryable_televote_award_contest_stage_enum", "[contest_stage] IN (0,1,2)");
                        });
                });

            modelBuilder.Entity("Eurocentric.Domain.Aggregates.Contests.LiverpoolFormatContest", b =>
                {
                    b.HasBaseType("Eurocentric.Domain.Aggregates.Contests.Contest");

                    b.ToTable("contest", null, t =>
                        {
                            t.HasCheckConstraint("ck_contest_contest_format_enum", "[contest_format] IN (0,1)");
                        });

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Eurocentric.Domain.Aggregates.Contests.StockholmFormatContest", b =>
                {
                    b.HasBaseType("Eurocentric.Domain.Aggregates.Contests.Contest");

                    b.ToTable("contest", null, t =>
                        {
                            t.HasCheckConstraint("ck_contest_contest_format_enum", "[contest_format] IN (0,1)");
                        });

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("Eurocentric.Domain.Aggregates.Broadcasts.Broadcast", b =>
                {
                    b.OwnsMany("Eurocentric.Domain.Aggregates.Broadcasts.Competitor", "Competitors", b1 =>
                        {
                            b1.Property<Guid>("BroadcastId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("broadcast_id");

                            b1.Property<Guid>("CompetingCountryId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("competing_country_id");

                            b1.Property<int>("FinishingPosition")
                                .HasColumnType("int")
                                .HasColumnName("finishing_position");

                            b1.Property<int>("RunningOrderPosition")
                                .HasColumnType("int")
                                .HasColumnName("running_order_position");

                            b1.HasKey("BroadcastId", "CompetingCountryId")
                                .HasName("ak_broadcast_competitor_broadcast_id_competing_country_id");

                            SqlServerKeyBuilderExtensions.IsClustered(b1.HasKey("BroadcastId", "CompetingCountryId"));

                            b1.HasIndex("BroadcastId", "RunningOrderPosition")
                                .IsUnique()
                                .HasDatabaseName("ix_broadcast_competitor_broadcast_id_running_order_position");

                            b1.ToTable("broadcast_competitor", null, t =>
                                {
                                    t.HasCheckConstraint("ck_broadcast_competitor_finishing_position", "[finishing_position] > 0");

                                    t.HasCheckConstraint("ck_broadcast_competitor_running_order_position", "[running_order_position] > 0");
                                });

                            b1.WithOwner()
                                .HasForeignKey("BroadcastId")
                                .HasConstraintName("fk_broadcast_competitor_broadcast_broadcast_id");

                            b1.OwnsMany("Eurocentric.Domain.ValueObjects.JuryAward", "JuryAwards", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int")
                                        .HasColumnName("id");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<Guid>("BroadcastId")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("broadcast_id");

                                    b2.Property<Guid>("CompetingCountryId")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("competing_country_id");

                                    b2.Property<int>("PointsValue")
                                        .HasColumnType("int")
                                        .HasColumnName("points_value");

                                    b2.Property<Guid>("VotingCountryId")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("voting_country_id");

                                    b2.HasKey("Id")
                                        .HasName("pk_broadcast_competitor_jury_award");

                                    SqlServerKeyBuilderExtensions.IsClustered(b2.HasKey("Id"));

                                    b2.HasIndex("BroadcastId", "CompetingCountryId", "VotingCountryId")
                                        .IsUnique()
                                        .HasDatabaseName("ix_broadcast_competitor_jury_award_broadcast_id_competing_country_id_voting_country_id");

                                    b2.ToTable("broadcast_competitor_jury_award", null, t =>
                                        {
                                            t.HasCheckConstraint("ck_broadcast_competitor_jury_award_country_ids", "[competing_country_id] <> [voting_country_id]");

                                            t.HasCheckConstraint("ck_broadcast_competitor_jury_award_points_value_enum", "[points_value] IN (0,1,2,3,4,5,6,7,8,10,12)");
                                        });

                                    b2.WithOwner()
                                        .HasForeignKey("BroadcastId", "CompetingCountryId")
                                        .HasConstraintName("fk_broadcast_competitor_jury_award_broadcast_competitor_broadcast_id_competing_country_id");
                                });

                            b1.OwnsMany("Eurocentric.Domain.ValueObjects.TelevoteAward", "TelevoteAwards", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int")
                                        .HasColumnName("id");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<Guid>("BroadcastId")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("broadcast_id");

                                    b2.Property<Guid>("CompetingCountryId")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("competing_country_id");

                                    b2.Property<int>("PointsValue")
                                        .HasColumnType("int")
                                        .HasColumnName("points_value");

                                    b2.Property<Guid>("VotingCountryId")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("voting_country_id");

                                    b2.HasKey("Id")
                                        .HasName("pk_broadcast_competitor_televote_award");

                                    SqlServerKeyBuilderExtensions.IsClustered(b2.HasKey("Id"));

                                    b2.HasIndex("BroadcastId", "CompetingCountryId", "VotingCountryId")
                                        .IsUnique()
                                        .HasDatabaseName("ix_broadcast_competitor_televote_award_broadcast_id_competing_country_id_voting_country_id");

                                    b2.ToTable("broadcast_competitor_televote_award", null, t =>
                                        {
                                            t.HasCheckConstraint("ck_broadcast_competitor_televote_award_country_ids", "[competing_country_id] <> [voting_country_id]");

                                            t.HasCheckConstraint("ck_broadcast_competitor_televote_award_points_value_enum", "[points_value] IN (0,1,2,3,4,5,6,7,8,10,12)");
                                        });

                                    b2.WithOwner()
                                        .HasForeignKey("BroadcastId", "CompetingCountryId")
                                        .HasConstraintName("fk_broadcast_competitor_televote_award_broadcast_competitor_broadcast_id_competing_country_id");
                                });

                            b1.Navigation("JuryAwards");

                            b1.Navigation("TelevoteAwards");
                        });

                    b.OwnsMany("Eurocentric.Domain.Aggregates.Broadcasts.Jury", "Juries", b1 =>
                        {
                            b1.Property<Guid>("BroadcastId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("broadcast_id");

                            b1.Property<Guid>("VotingCountryId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("voting_country_id");

                            b1.Property<bool>("PointsAwarded")
                                .HasColumnType("bit")
                                .HasColumnName("points_awarded");

                            b1.HasKey("BroadcastId", "VotingCountryId")
                                .HasName("pk_broadcast_jury");

                            SqlServerKeyBuilderExtensions.IsClustered(b1.HasKey("BroadcastId", "VotingCountryId"));

                            b1.ToTable("broadcast_jury", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("BroadcastId")
                                .HasConstraintName("fk_broadcast_jury_broadcast_broadcast_id");
                        });

                    b.OwnsMany("Eurocentric.Domain.Aggregates.Broadcasts.Televote", "Televotes", b1 =>
                        {
                            b1.Property<Guid>("BroadcastId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("broadcast_id");

                            b1.Property<Guid>("VotingCountryId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("voting_country_id");

                            b1.Property<bool>("PointsAwarded")
                                .HasColumnType("bit")
                                .HasColumnName("points_awarded");

                            b1.HasKey("BroadcastId", "VotingCountryId")
                                .HasName("pk_broadcast_televote");

                            SqlServerKeyBuilderExtensions.IsClustered(b1.HasKey("BroadcastId", "VotingCountryId"));

                            b1.ToTable("broadcast_televote", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("BroadcastId")
                                .HasConstraintName("fk_broadcast_televote_broadcast_broadcast_id");
                        });

                    b.Navigation("Competitors");

                    b.Navigation("Juries");

                    b.Navigation("Televotes");
                });

            modelBuilder.Entity("Eurocentric.Domain.Aggregates.Contests.Contest", b =>
                {
                    b.OwnsMany("Eurocentric.Domain.Aggregates.Contests.Participant", "Participants", b1 =>
                        {
                            b1.Property<Guid>("ContestId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("contest_id");

                            b1.Property<Guid>("ParticipatingCountryId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("participating_country_id");

                            b1.Property<string>("ActName")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("act_name");

                            b1.Property<int>("ParticipantGroup")
                                .HasColumnType("int")
                                .HasColumnName("participant_group");

                            b1.Property<string>("SongTitle")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("song_title");

                            b1.HasKey("ContestId", "ParticipatingCountryId")
                                .HasName("pk_contest_participant");

                            SqlServerKeyBuilderExtensions.IsClustered(b1.HasKey("ContestId", "ParticipatingCountryId"));

                            b1.ToTable("contest_participant", null, t =>
                                {
                                    t.HasCheckConstraint("ck_contest_participant_nullability_permutations", "([participant_group] = 0 AND [act_name] IS NULL AND [song_title] IS NULL) OR ([participant_group] <> 0 AND [act_name] IS NOT NULL AND [song_title] IS NOT NULL)");

                                    t.HasCheckConstraint("ck_contest_participant_participant_group_enum", "[participant_group] IN (0,1,2)");
                                });

                            b1.WithOwner()
                                .HasForeignKey("ContestId")
                                .HasConstraintName("fk_contest_participant_contest_contest_id");
                        });

                    b.OwnsMany("Eurocentric.Domain.ValueObjects.BroadcastMemo", "ChildBroadcasts", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasColumnName("id");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("BroadcastId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("broadcast_id");

                            b1.Property<bool>("Completed")
                                .HasColumnType("bit")
                                .HasColumnName("completed");

                            b1.Property<Guid>("ContestId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("contest_id");

                            b1.Property<int>("ContestStage")
                                .HasColumnType("int")
                                .HasColumnName("contest_stage");

                            b1.HasKey("Id")
                                .HasName("pk_contest_child_broadcast");

                            SqlServerKeyBuilderExtensions.IsClustered(b1.HasKey("Id"));

                            b1.HasIndex("ContestId", "ContestStage")
                                .IsUnique()
                                .HasDatabaseName("ix_contest_child_broadcast_contest_id_contest_stage");

                            b1.ToTable("contest_child_broadcast", null, t =>
                                {
                                    t.HasCheckConstraint("ck_contest_child_broadcast_contest_stage_enum", "[contest_stage] IN (0,1,2)");
                                });

                            b1.WithOwner()
                                .HasForeignKey("ContestId")
                                .HasConstraintName("fk_contest_child_broadcast_contest_contest_id");
                        });

                    b.Navigation("ChildBroadcasts");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Eurocentric.Domain.Aggregates.Countries.Country", b =>
                {
                    b.OwnsMany("Eurocentric.Domain.Identifiers.ContestId", "ParticipatingContestIds", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasColumnName("id");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("CountryId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("country_id");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("participating_contest_id");

                            b1.HasKey("Id")
                                .HasName("pk_country_participating_contest");

                            b1.HasIndex("CountryId", "Value")
                                .IsUnique()
                                .HasDatabaseName("ix_country_participating_contest_country_id_participating_contest_id");

                            b1.ToTable("country_participating_contest", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CountryId")
                                .HasConstraintName("fk_country_participating_contest_country_country_id");
                        });

                    b.Navigation("ParticipatingContestIds");
                });
#pragma warning restore 612, 618
        }
    }
}
