// <auto-generated />
using System;
using Eurocentric.Infrastructure.DataAccess.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eurocentric.Infrastructure.DataAccess.EfCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Eurocentric.Domain.V0.Entities.Broadcast", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateOnly>("BroadcastDate")
                        .HasColumnType("date")
                        .HasColumnName("broadcast_date");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit")
                        .HasColumnName("completed");

                    b.Property<int>("ContestStage")
                        .HasColumnType("int")
                        .HasColumnName("contest_stage");

                    b.Property<Guid>("ParentContestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("parent_contest_id");

                    b.HasKey("Id")
                        .HasName("pk_broadcast");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasAlternateKey("BroadcastDate")
                        .HasName("ak_broadcast_broadcast_date");

                    b.HasAlternateKey("ParentContestId", "ContestStage")
                        .HasName("ak_broadcast_parent_contest_id_contest_stage");

                    b.ToTable("broadcast", "v0");
                });

            modelBuilder.Entity("Eurocentric.Domain.V0.Entities.Contest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("city_name");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit")
                        .HasColumnName("completed");

                    b.Property<int>("ContestFormat")
                        .HasColumnType("int")
                        .HasColumnName("contest_format");

                    b.Property<int>("ContestYear")
                        .HasColumnType("int")
                        .HasColumnName("contest_year");

                    b.HasKey("Id")
                        .HasName("pk_contest");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasAlternateKey("ContestYear")
                        .HasName("ak_contest_contest_year");

                    b.ToTable("contest", "v0");
                });

            modelBuilder.Entity("Eurocentric.Domain.V0.Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .HasColumnName("country_code")
                        .IsFixedLength();

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("country_name");

                    b.PrimitiveCollection<string>("ParticipatingContestIds")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("participating_contest_ids");

                    b.HasKey("Id")
                        .HasName("pk_country");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasAlternateKey("CountryCode")
                        .HasName("ak_country_country_code");

                    b.ToTable("country", "v0");
                });

            modelBuilder.Entity("Eurocentric.Domain.V0.Entities.Broadcast", b =>
                {
                    b.OwnsMany("Eurocentric.Domain.V0.Entities.Competitor", "Competitors", b1 =>
                        {
                            b1.Property<Guid>("BroadcastId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("broadcast_id");

                            b1.Property<Guid>("CompetingCountryId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("competing_country_id");

                            b1.Property<int>("FinishingPosition")
                                .HasColumnType("int")
                                .HasColumnName("finishing_position");

                            b1.Property<int>("RunningOrderPosition")
                                .HasColumnType("int")
                                .HasColumnName("running_order_position");

                            b1.HasKey("BroadcastId", "CompetingCountryId")
                                .HasName("ak_broadcast_competitor_broadcast_id_competing_country_id");

                            SqlServerKeyBuilderExtensions.IsClustered(b1.HasKey("BroadcastId", "CompetingCountryId"));

                            b1.HasIndex("BroadcastId", "RunningOrderPosition")
                                .IsUnique()
                                .HasDatabaseName("ix_broadcast_competitor_broadcast_id_running_order_position");

                            b1.ToTable("broadcast_competitor", "v0");

                            b1.WithOwner()
                                .HasForeignKey("BroadcastId")
                                .HasConstraintName("fk_broadcast_competitor_broadcast_broadcast_id");

                            b1.OwnsMany("Eurocentric.Domain.V0.Entities.JuryAward", "JuryAwards", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int")
                                        .HasColumnName("id");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<Guid>("BroadcastId")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("broadcast_id");

                                    b2.Property<Guid>("CompetingCountryId")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("competing_country_id");

                                    b2.Property<int>("PointsValue")
                                        .HasColumnType("int")
                                        .HasColumnName("points_value");

                                    b2.Property<Guid>("VotingCountryId")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("voting_country_id");

                                    b2.HasKey("Id")
                                        .HasName("pk_broadcast_competitor_jury_award");

                                    SqlServerKeyBuilderExtensions.IsClustered(b2.HasKey("Id"));

                                    b2.HasIndex("BroadcastId")
                                        .HasDatabaseName("ix_broadcast_competitor_jury_award_broadcast_id");

                                    b2.HasIndex("CompetingCountryId")
                                        .HasDatabaseName("ix_broadcast_competitor_jury_award_competing_country_id");

                                    b2.HasIndex("VotingCountryId")
                                        .HasDatabaseName("ix_broadcast_competitor_jury_award_voting_country_id");

                                    b2.HasIndex("BroadcastId", "CompetingCountryId", "VotingCountryId")
                                        .IsUnique()
                                        .HasDatabaseName("ix_broadcast_competitor_jury_award_broadcast_id_competing_country_id_voting_country_id");

                                    b2.ToTable("broadcast_competitor_jury_award", "v0");

                                    b2.WithOwner()
                                        .HasForeignKey("BroadcastId", "CompetingCountryId")
                                        .HasConstraintName("fk_broadcast_competitor_jury_award_broadcast_competitor_broadcast_id_competing_country_id");
                                });

                            b1.OwnsMany("Eurocentric.Domain.V0.Entities.TelevoteAward", "TelevoteAwards", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int")
                                        .HasColumnName("id");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<Guid>("BroadcastId")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("broadcast_id");

                                    b2.Property<Guid>("CompetingCountryId")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("competing_country_id");

                                    b2.Property<int>("PointsValue")
                                        .HasColumnType("int")
                                        .HasColumnName("points_value");

                                    b2.Property<Guid>("VotingCountryId")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("voting_country_id");

                                    b2.HasKey("Id")
                                        .HasName("pk_broadcast_competitor_televote_award");

                                    SqlServerKeyBuilderExtensions.IsClustered(b2.HasKey("Id"));

                                    b2.HasIndex("BroadcastId")
                                        .HasDatabaseName("ix_broadcast_competitor_televote_award_broadcast_id");

                                    b2.HasIndex("CompetingCountryId")
                                        .HasDatabaseName("ix_broadcast_competitor_televote_award_competing_country_id");

                                    b2.HasIndex("VotingCountryId")
                                        .HasDatabaseName("ix_broadcast_competitor_televote_award_voting_country_id");

                                    b2.HasIndex("BroadcastId", "CompetingCountryId", "VotingCountryId")
                                        .IsUnique()
                                        .HasDatabaseName("ix_broadcast_competitor_televote_award_broadcast_id_competing_country_id_voting_country_id");

                                    b2.ToTable("broadcast_competitor_televote_award", "v0");

                                    b2.WithOwner()
                                        .HasForeignKey("BroadcastId", "CompetingCountryId")
                                        .HasConstraintName("fk_broadcast_competitor_televote_award_broadcast_competitor_broadcast_id_competing_country_id");
                                });

                            b1.Navigation("JuryAwards");

                            b1.Navigation("TelevoteAwards");
                        });

                    b.OwnsMany("Eurocentric.Domain.V0.Entities.Jury", "Juries", b1 =>
                        {
                            b1.Property<Guid>("BroadcastId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("broadcast_id");

                            b1.Property<Guid>("VotingCountryId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("voting_country_id");

                            b1.Property<bool>("PointsAwarded")
                                .HasColumnType("bit")
                                .HasColumnName("points_awarded");

                            b1.HasKey("BroadcastId", "VotingCountryId")
                                .HasName("pk_broadcast_jury");

                            SqlServerKeyBuilderExtensions.IsClustered(b1.HasKey("BroadcastId", "VotingCountryId"));

                            b1.ToTable("broadcast_jury", "v0");

                            b1.WithOwner()
                                .HasForeignKey("BroadcastId")
                                .HasConstraintName("fk_broadcast_jury_broadcast_broadcast_id");
                        });

                    b.OwnsMany("Eurocentric.Domain.V0.Entities.Televote", "Televotes", b1 =>
                        {
                            b1.Property<Guid>("BroadcastId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("broadcast_id");

                            b1.Property<Guid>("VotingCountryId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("voting_country_id");

                            b1.Property<bool>("PointsAwarded")
                                .HasColumnType("bit")
                                .HasColumnName("points_awarded");

                            b1.HasKey("BroadcastId", "VotingCountryId")
                                .HasName("pk_broadcast_televote");

                            SqlServerKeyBuilderExtensions.IsClustered(b1.HasKey("BroadcastId", "VotingCountryId"));

                            b1.ToTable("broadcast_televote", "v0");

                            b1.WithOwner()
                                .HasForeignKey("BroadcastId")
                                .HasConstraintName("fk_broadcast_televote_broadcast_broadcast_id");
                        });

                    b.Navigation("Competitors");

                    b.Navigation("Juries");

                    b.Navigation("Televotes");
                });

            modelBuilder.Entity("Eurocentric.Domain.V0.Entities.Contest", b =>
                {
                    b.OwnsMany("Eurocentric.Domain.V0.Entities.ChildBroadcast", "ChildBroadcasts", b1 =>
                        {
                            b1.Property<Guid>("ContestId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("contest_id");

                            b1.Property<Guid>("BroadcastId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("broadcast_id");

                            b1.Property<bool>("Completed")
                                .HasColumnType("bit")
                                .HasColumnName("completed");

                            b1.Property<int>("ContestStage")
                                .HasColumnType("int")
                                .HasColumnName("contest_stage");

                            b1.HasKey("ContestId", "BroadcastId")
                                .HasName("pk_contest_child_broadcast");

                            SqlServerKeyBuilderExtensions.IsClustered(b1.HasKey("ContestId", "BroadcastId"));

                            b1.HasIndex("ContestId", "ContestStage")
                                .IsUnique()
                                .HasDatabaseName("ix_contest_child_broadcast_contest_id_contest_stage");

                            b1.ToTable("contest_child_broadcast", "v0");

                            b1.WithOwner()
                                .HasForeignKey("ContestId")
                                .HasConstraintName("fk_contest_child_broadcast_contest_contest_id");
                        });

                    b.OwnsOne("Eurocentric.Domain.V0.Entities.GlobalTelevote", "GlobalTelevote", b1 =>
                        {
                            b1.Property<Guid>("ContestId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<Guid>("ParticipatingCountryId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("global_televote_participating_country_id");

                            b1.HasKey("ContestId");

                            b1.ToTable("contest", "v0");

                            b1.WithOwner()
                                .HasForeignKey("ContestId")
                                .HasConstraintName("fk_contest_contest_id");
                        });

                    b.OwnsMany("Eurocentric.Domain.V0.Entities.Participant", "Participants", b1 =>
                        {
                            b1.Property<Guid>("ContestId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("contest_id");

                            b1.Property<Guid>("ParticipatingCountryId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("participating_country_id");

                            b1.Property<string>("ActName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("act_name");

                            b1.Property<int>("SemiFinalDraw")
                                .HasColumnType("int")
                                .HasColumnName("semi_final_draw");

                            b1.Property<string>("SongTitle")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("song_title");

                            b1.HasKey("ContestId", "ParticipatingCountryId")
                                .HasName("pk_contest_participant");

                            SqlServerKeyBuilderExtensions.IsClustered(b1.HasKey("ContestId", "ParticipatingCountryId"));

                            b1.ToTable("contest_participant", "v0");

                            b1.WithOwner()
                                .HasForeignKey("ContestId")
                                .HasConstraintName("fk_contest_participant_contest_contest_id");
                        });

                    b.Navigation("ChildBroadcasts");

                    b.Navigation("GlobalTelevote");

                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
