### Admin API v0.1 - Get Station (happy path)
GET http://localhost:5022/admin/api/v0.1/stations/1
Accept: application/json, application/problem+json

### Admin API v0.1 - Get Station (station not found)
GET http://localhost:5022/admin/api/v0.1/stations/0
Accept: application/json, application/problem+json



### Admin API v0.2 - Create Station (happy path)
POST http://localhost:5022/admin/api/v0.2/stations
Accept: application/json, application/problem+json
Content-Type: application/json

{
  "name": "Oval",
  "line": "Northern"
}

### Admin API v0.2 - Create Station (bad request - missing required property)
POST http://localhost:5022/admin/api/v0.2/stations
Accept: application/json, application/problem+json
Content-Type: application/json

{
  "line": "Northern"
}

### Admin API v0.2 - Create Station (bad request - invalid enum name)
POST http://localhost:5022/admin/api/v0.2/stations
Accept: application/json, application/problem+json
Content-Type: application/json

{
  "name": "Oval",
  "line": "NotALine"
}

### Admin API v0.2 - Create Station (bad request - invalid enum value)
POST http://localhost:5022/admin/api/v0.2/stations
Accept: application/json, application/problem+json
Content-Type: application/json

{
  "name": "Oval",
  "line": 999999
}

### Admin API v0.2 - Create Station (unprocessable entity - name property is empty string)
POST http://localhost:5022/admin/api/v0.2/stations
Accept: application/json, application/problem+json
Content-Type: application/json

{
  "name": "",
  "line": "Northern"
}

### Admin API v0.2 - Get Station (happy path)
GET http://localhost:5022/admin/api/v0.2/stations/1
Accept: application/json, application/problem+json

### Admin API v0.2 - Get Station (station not found)
GET http://localhost:5022/admin/api/v0.2/stations/0
Accept: application/json, application/problem+json



### Public API v0.1 - Get Stations (happy path 1 of 3)
GET http://localhost:5022/public/api/v0.1/stations?line=Jubilee
Accept: application/json, application/problem+json

### Public API v0.1 - Get Stations (happy path 2 of 3)
GET http://localhost:5022/public/api/v0.1/stations?line=Jubilee
Accept: application/json, application/problem+json

### Public API v0.1 - Get Stations (happy path3 of 3)
GET http://localhost:5022/public/api/v0.1/stations?line=Jubilee
Accept: application/json, application/problem+json
