### GET request to Admin API placeholder endpoint

GET http://localhost:5263/admin/api/v0.1/placeholder

### GET request to Public API placeholder endpoint

GET http://localhost:5263/public/api/v0.1/placeholder
