namespace Eurocentric.Domain.Analytics.Rankings.Common;

/// <summary>
///     Metadata describing an executed paginated rankings query.
/// </summary>
public abstract record PaginatedMetadata
{
    /// <summary>
    ///     The zero-based pagination page index.
    /// </summary>
    public int PageIndex { get; init; }

    /// <summary>
    ///     The pagination page size.
    /// </summary>
    public int PageSize { get; init; }

    /// <summary>
    ///     Rankings initially sorted by descending rank (<see langword="true" />) or ascending rank (<see langword="false" />
    ///     ).
    /// </summary>
    public bool Descending { get; init; }

    /// <summary>
    ///     The total number of rankings generated by the query.
    /// </summary>
    public int TotalItems { get; init; }

    /// <summary>
    ///     The total number of rankings pages generated by the query.
    /// </summary>
    public int TotalPages { get; init; }
}
