using Eurocentric.Apis.Public.V1.Enums;

namespace Eurocentric.Apis.Public.V1.Dtos.CompetingCountryRankings;

/// <summary>
///     Metadata describing an executed competing country points average rankings query.
/// </summary>
public sealed record CompetingCountryPointsShareMetadata
{
    /// <summary>
    ///     The optional inclusive minimum contest year filter value.
    /// </summary>
    public int? MinYear { get; init; }

    /// <summary>
    ///     The optional inclusive maximum contest year filter value.
    /// </summary>
    public int? MaxYear { get; init; }

    /// <summary>
    ///     The optional contest stage filter value.
    /// </summary>
    public ContestStageFilter? ContestStage { get; init; }

    /// <summary>
    ///     The optional voting country code filter value.
    /// </summary>
    public string? VotingCountryCode { get; init; }

    /// <summary>
    ///     The optional voting method filter value.
    /// </summary>
    public VotingMethodFilter? VotingMethod { get; init; }

    /// <summary>
    ///     The zero-based pagination page index.
    /// </summary>
    public int PageIndex { get; init; }

    /// <summary>
    ///     The pagination page size.
    /// </summary>
    public int PageSize { get; init; }

    /// <summary>
    ///     Rankings initially sorted by descending rank (<see langword="true" />) or ascending rank
    ///     (<see langword="false" />).
    /// </summary>
    public bool Descending { get; init; }

    /// <summary>
    ///     The total number of rankings generated by the query.
    /// </summary>
    public int TotalItems { get; init; }

    /// <summary>
    ///     The total number of rankings pages generated by the query.
    /// </summary>
    public int TotalPages { get; init; }
}
