SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

CREATE OR ALTER PROCEDURE dbo.usp_get_competitor_points_share_rankings(
    @min_year INT = NULL,
    @max_year INT = NULL,
    @contest_stage NVARCHAR(10) = NULL,
    @competing_country_code NCHAR(2) = NULL,
    @voting_method NVARCHAR(10) = NULL,
    @page_index INT = 0,
    @page_size INT = 10,
    @descending BIT = 0
)
AS

/*
-- =============================================
-- Function:    dbo.usp_get_competitor_points_share_rankings
-- Author:      Matt Tantony
-- Create date: 2025-11-10
--
--
-- Description:
-- ============
--  Ranks competitors in broadcasts based on descending points share.
--
--  Returns 1) a single metadata row, then 2) a page of rankings rows.
--
--  Points share is a DECIMAL(18,6) between 0 and 1, calculated as the sum total points the competitor received in their
--  broadcast as a fraction of the available points.
--
--  Rankings are generated by:
--      - Filtering voting data from query parameters.
--      - Grouping data by broadcast competitor.
--      - Calculating points share metric.
--      - Ranking by descending points share.
--      - Sorting rankings
--          - by rank (ascending or descending)
--          - then by contest year (ascending)
--          - then by contest stage (SemiFinal1 < SemiFinal2 < GrandFinal)
--          - then by running order spot (ascending)
--      - Applying pagination.
--
--
-- Optional input parameters:
-- ==========================
--  @min_year INT
--      - Filters voting data by inclusive minimum contest year when not NULL.
--      - Allows NULL. Default value is NULL.
--  @max_year INT
--      - Filters voting data by inclusive maximum contest year when not NULL.
--      - Allows NULL. Default value is NULL.
--  @contest_stage NVARCHAR(10)
--      - Filters voting data by contest stage when not NULL.
--      - Valid 'ContestStageFilter' enum values: {'Any', 'SemiFinal1', 'SemiFinal2', 'SemiFinals', 'GrandFinal'}.
--      - Allows NULL. Default value is NULL.
--  @competing_country_code NCHAR(2)
--      - Filters voting data by competing country ISO 3166-1 alpha-2 country code when not NULL.
--      - Allows NULL. Default value is NULL.
--  @voting_method NVARCHAR(10)
--      - Filters voting data by voting method when not NULL.
--      - Valid 'VotingMethodFilter' enum values: {'Any', 'Jury', 'Televote'}.
--      - Allows NULL. Default value is NULL.
--  @page_index INT
--      - Sets the zero-based pagination page index.
--      - Default value is 0.
--  @page_size INT
--      - Sets the pagination page size.
--      - Default value is 10.
--  @descending BIT
--      - Sets the pre-pagination initial sort to descending rank (1) or ascending rank (0).
--      - Default value is 0.
--
--
-- Returns (1 of 2):
-- =================
-- A single metadata row with the following columns:
--  - min_year INT (allows NULL)
--      - The optional inclusive minimum contest year filter value.
--  - max_year INT (allows NULL)
--      - The optional inclusive maximum contest year filter value.
--  - contest_stage NVARCHAR(10) (allows NULL)
--      - The optional contest stage filter value.
--      - Valid 'ContestStageFilter' enum values: {'Any', 'SemiFinal1', 'SemiFinal2', 'SemiFinals', 'GrandFinal'}.
--  - competing_country_code NCHAR(2) (allows NULL)
--      - The optional competing country code filter value.
--  - voting_method NVARCHAR(10) (allows NULL)
--      - The optional voting method filter value.
--      - Valid 'VotingMethodFilter' enum values: {'Any', 'Jury', 'Televote'}.
--  - page_index INT
--      - The zero-based pagination.
--  - page_size INT
--      - The pagination page size.
--  - descending BIT
--      - Rankings initially sorted by descending rank (1) or ascending rank (0) before pagination.
--  - total_items INT
--      - The total number of rankings generated by the query.
--  - total_pages INT
--      - The total number of rankings pages generated by the query.
--
--
-- Returns (2 of 2):
-- =================
-- A list of 0, 1, or multiple rankings rows with the following columns:
--  - rank BIGINT
--      - The competitor's rank based on descending points average.
--  - contest_year INT
--      - The contest year of the broadcast.
--  - contest_stage NVARCHAR(10)
--      - The broadcast's stage in its contest.
--      - Value 'ContestStage' enum values: {'SemiFinal1', 'SemiFinal2', 'GrandFinal'}.
--  - running_order_spot INT
--      - The competitor's running order spot in the broadcast.
--  - country_code NCHAR(2)
--      - The competing country's ISO 3166-1 alpha-2 country code.
--  - country_name NVARCHAR(200)
--      - The competing country's short UK English name.
--  - finishing_position INT
--      - The competitor's finishing position in the broadcast.
--  - act_name NVARCHAR(200)
--      - The competitor's act name.
--  - song_title NVARCHAR(200)
--      - The competitor's song title.
--  - points_share DECIMAL(18,6)
--      - The sum total points the competitor received in the broadcast as a fraction of the available points.
--  - total_points INT
--      - The sum total points the competitor received in the broadcast.
--  - available_points INT
--      - The maximum available points the competitor could have received in the broadcast.
--  - points_awards INT
--      - The quantity of points awards the competitor received in the broadcast.
--  - voting_countries INT
--      - The number of unique voting countries in the queried voting data for the competitor.
-- =============================================
*/


BEGIN

    SET NOCOUNT ON;

-- Declare constants

    DECLARE @resolved_min_year INT = COALESCE(@min_year, (SELECT MIN(contest_year) FROM dbo.contest));
    DECLARE @resolved_max_year INT = COALESCE(@max_year, (SELECT MAX(contest_year) FROM dbo.contest));
    DECLARE @include_jury_points BIT = IIF(@voting_method = N'Televote', 0, 1);
    DECLARE @include_televote_points BIT = IIF(@voting_method = N'Jury', 0, 1);

-- Filter voting data

    WITH filtered_contest_broadcast AS (SELECT k.contest_id,
                                               b.broadcast_id
                                        FROM dbo.contest k
                                                 JOIN dbo.broadcast b ON b.parent_contest_id = k.contest_id
                                                 JOIN dbo.tvf_map_contest_stage_filter_enum(@contest_stage) cs
                                                      ON cs.contest_stage = b.contest_stage
                                        WHERE k.queryable = 1
                                          AND k.contest_year BETWEEN @resolved_min_year AND @resolved_max_year),

         filtered_competing_country AS (SELECT c.country_id AS competing_country_id
                                        FROM dbo.country c
                                        WHERE @competing_country_code IS NULL
                                           OR c.country_code = @competing_country_code),

         query_datum AS (SELECT fcb.broadcast_id,
                                bcja.competing_country_id,
                                bcja.points_value,
                                MAX(bcja.points_value)
                                    OVER (PARTITION BY bcja.broadcast_id, bcja.voting_country_id) AS max_points_value,
                                bcja.voting_country_id
                         FROM dbo.broadcast_competitor_jury_award bcja
                                  JOIN filtered_contest_broadcast fcb ON fcb.broadcast_id = bcja.broadcast_id
                                  JOIN filtered_competing_country fcc
                                       ON fcc.competing_country_id = bcja.competing_country_id
                         WHERE @include_jury_points = 1
                         UNION ALL
                         SELECT fcb.broadcast_id,
                                bcta.competing_country_id,
                                bcta.points_value,
                                MAX(bcta.points_value)
                                    OVER (PARTITION BY bcta.broadcast_id, bcta.voting_country_id) AS max_points_value,
                                bcta.voting_country_id
                         FROM dbo.broadcast_competitor_televote_award bcta
                                  JOIN filtered_contest_broadcast fcb ON fcb.broadcast_id = bcta.broadcast_id
                                  JOIN filtered_competing_country fcc
                                       ON fcc.competing_country_id = bcta.competing_country_id
                         WHERE @include_televote_points = 1),

-- Group data by broadcast competitor

         grouped_datum AS (SELECT qd.broadcast_id,
                                  qd.competing_country_id,
                                  SUM(qd.points_value)                 AS total_points,
                                  SUM(qd.max_points_value)             AS available_points,
                                  COUNT(*)                             AS points_awards,
                                  COUNT(DISTINCT qd.voting_country_id) AS voting_countries
                           FROM query_datum qd
                           GROUP BY qd.broadcast_id, qd.competing_country_id),

-- Calculate points share metric

         grouped_metric AS (SELECT gd.broadcast_id,
                                   gd.competing_country_id,
                                   dbo.udf_round_to_6dp((1.0 * gd.total_points) / gd.available_points) AS points_share,
                                   gd.total_points,
                                   gd.available_points,
                                   gd.points_awards,
                                   gd.voting_countries
                            FROM grouped_datum gd)

-- Rank by descending points share

    SELECT RANK() OVER (ORDER BY gm.points_share DESC)                   AS rank,
           k.contest_id,
           k.contest_year,
           ccb.contest_stage,
           dbo.udf_get_contest_stage_sort_order_value(ccb.contest_stage) AS contest_stage_sort_order,
           bc.running_order_spot,
           bc.competing_country_id,
           bc.finishing_position,
           gm.points_share,
           gm.total_points,
           gm.available_points,
           gm.points_awards,
           gm.voting_countries
    INTO #ranking
    FROM grouped_metric gm
             JOIN dbo.broadcast_competitor bc
                  ON bc.broadcast_id = gm.broadcast_id AND bc.competing_country_id = gm.competing_country_id
             JOIN dbo.contest_child_broadcast ccb ON ccb.child_broadcast_id = bc.broadcast_id
             JOIN dbo.contest k ON k.contest_id = ccb.contest_id;

-- Return single metadata rows

    DECLARE @total_items INT = (SELECT COUNT(*) FROM #ranking);
    DECLARE @total_pages INT = dbo.udf_get_pagination_total_pages(@page_size, @total_items);

    SELECT @min_year               AS min_year,
           @max_year               AS max_year,
           @contest_stage          AS contest_stage,
           @competing_country_code AS competing_country_code,
           @voting_method          AS voting_method,
           @page_index             AS page_index,
           @page_size              AS page_size,
           @descending             AS descending,
           @total_items            AS total_items,
           @total_pages            AS total_pages;

-- Return sorted paginated rankings rows with additional fields

    SELECT r.rank,
           r.contest_year,
           r.contest_stage,
           r.running_order_spot,
           c.country_code,
           c.country_name,
           r.finishing_position,
           cp.act_name,
           cp.song_title,
           r.points_share,
           r.total_points,
           r.available_points,
           r.points_awards,
           r.voting_countries
    FROM #ranking r
             JOIN dbo.country c ON c.country_id = r.competing_country_id
             JOIN dbo.contest_participant cp
                  ON cp.contest_id = r.contest_id AND cp.participating_country_id = r.competing_country_id
    ORDER BY CASE WHEN @descending = 1 THEN r.rank END DESC,
             CASE WHEN @descending = 0 THEN r.rank END,
             r.contest_year,
             r.contest_stage_sort_order,
             r.running_order_spot
    OFFSET (@page_index * @page_size) ROWS FETCH NEXT @page_size ROWS ONLY;

END

GO
