SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

CREATE OR ALTER PROCEDURE dbo.usp_get_competing_country_points_average_rankings(
    @min_year INT = NULL,
    @max_year INT = NULL,
    @contest_stage NVARCHAR(10) = NULL,
    @voting_country_code NCHAR(2) = NULL,
    @voting_method NVARCHAR(10) = NULL,
    @page_index INT = 0,
    @page_size INT = 10,
    @descending BIT = FALSE
)
AS

/*
-- =============================================
-- Procedure:   dbo.usp_get_competing_country_points_average_rankings
-- Author:      Matt Tantony
-- Create date: 2025-11-04
--
-- Description:
--  Ranks competing countries based on descending POINTS_AVERAGE.
--
--  POINTS_AVERAGE is a float between 0 and 12, calculated as the average individual points value received by the
--  competing country across broadcasts.
--
--  Returns 1) a page of rankings (which may be empty), then 2) a single metadata record.
--
-- Rankings are generated by:
--  - Filtering voting data.
--  - Grouping data by competing country.
--  - Calculating total points, points award count, and points average.
--  - Ranking by descending points average.
--  - Sorting by rank (ascending or descending) and country code.
--  - Applying pagination.
--
-- Input parameters:
--  @min_year INT - Filters voting data by inclusive minimum contest year when not NULL.
--    Accepts NULL.
--    Default value is NULL.
--  @max_year INT - Filters voting data by inclusive maximum contest year when not NULL.
--    Accepts NULL.
--    Default value is NULL.
--  @contest_stage NVARCHAR(10). Filters voting data by contest stage when not NULL.
--    Valid values: {'Any', 'SemiFinal1', 'SemiFinal2', 'SemiFinals', 'GrandFinal'}.
--    Accepts NULL.
--    Default value is NULL.
--  @voting_country_code NCHAR(2). Filters voting data by voting country code when not NULL.
--    Accepts NULL.
--    Default value is NULL.
--  @voting_method NVARCHAR(10). Filters voting data by voting method when not NULL.
--    Valid values: {'Any', 'Jury', 'Televote'}.
--    Accepts NULL.
--    Default value is NULL.
--  @page_index INT - Sets the pagination page index.
--    Default value is 0.
--  @page_size INT - Sets the pagination page size.
--    Default value is 10.
--  @descending BIT - Sorts rankings before pagination by ascending rank (0) or descending rank (1).
--    Default value is 0.
--
-- Returns:
--  1) A page of records with the following columns:
--    - rank INT
--    - country_code NCHAR(2)
--    - country_name NVARCHAR(200)
--    - points_average DECIMAL(9,6)
--    - total_points INT
--    - points_awards INT
--    - broadcasts INT
--    - contests INT
--    - voting_countries INT
--
--  2) A single metadata record with the following columns:
--    - min_year INT, may be NULL
--    - max_year INT, may be NULL
--    - contest_stage NVARCHAR(10), may be NULL
--    - voting_country_code NCHAR(2), may be NULL
--    - voting_method NVARCHAR(10), may be NULL
--    - page_index INT
--    - page_size INT
--    - descending BIT
--    - total_items INT
--    - total_pages INT
-- =============================================
*/

BEGIN

    SET NOCOUNT ON;

    DECLARE @resolved_min_year INT = COALESCE(@min_year, -999999);
    DECLARE @resolved_max_year INT = COALESCE(@max_year, 999999);
    DECLARE @resolved_voting_method NVARCHAR(10) = COALESCE(@voting_method, N'Any');

    WITH

--------------- Selecting query data ----------------

filtered_broadcast AS (SELECT k.contest_id,
                              b.broadcast_id
                       FROM dbo.contest k
                                JOIN dbo.broadcast b ON b.parent_contest_id = k.contest_id
                                INNER JOIN (SELECT contest_stage
                                            FROM dbo.tvf_map_contest_stage_filter_enum(@contest_stage)) cs
                                           ON cs.contest_stage = b.contest_stage
                       WHERE k.queryable = 1
                         AND k.contest_year BETWEEN @resolved_min_year AND @resolved_max_year),

filtered_voting_country AS (SELECT c.country_id AS voting_country_id
                            FROM dbo.country c
                            WHERE @voting_country_code IS NULL
                               OR @voting_country_code = c.country_code),

query_datum AS (SELECT bcja.competing_country_id,
                       bcja.broadcast_id,
                       bcja.voting_country_id,
                       fb.contest_id,
                       bcja.points_value
                FROM dbo.broadcast_competitor_jury_award bcja
                         JOIN filtered_broadcast fb ON fb.broadcast_id = bcja.broadcast_id
                         JOIN filtered_voting_country fvc ON fvc.voting_country_id = bcja.voting_country_id
                WHERE @resolved_voting_method <> N'Televote'

                UNION ALL

                SELECT bcta.competing_country_id,
                       bcta.broadcast_id,
                       bcta.voting_country_id,
                       fb.contest_id,
                       bcta.points_value
                FROM dbo.broadcast_competitor_televote_award bcta
                         JOIN filtered_broadcast fb ON fb.broadcast_id = bcta.broadcast_id
                         JOIN filtered_voting_country fvc ON fvc.voting_country_id = bcta.voting_country_id
                WHERE @resolved_voting_method <> N'Jury'),

-------- Grouping data by competing country ---------

grouped_datum AS (SELECT qd.competing_country_id,
                         SUM(qd.points_value)                 AS total_points,
                         COUNT(*)                             AS points_awards,
                         COUNT(DISTINCT qd.broadcast_id)      AS broadcasts,
                         COUNT(DISTINCT qd.contest_id)        AS contests,
                         COUNT(DISTINCT qd.voting_country_id) AS voting_countries
                  FROM query_datum qd
                  GROUP BY qd.competing_country_id),

-------- Calculating POINTS_AVERAGE metrics ---------

grouped_metric AS (SELECT gd.competing_country_id,
                          CAST(((1.0 * gd.total_points) / gd.points_awards) AS DECIMAL(9, 6)) AS points_average,
                          gd.total_points,
                          gd.points_awards,
                          gd.broadcasts,
                          gd.contests,
                          gd.voting_countries
                   FROM grouped_datum gd)

------- Ranking by descending POINTS_AVERAGE- -------

    SELECT RANK() OVER (ORDER BY gm.points_average DESC) AS rank,
           c.country_code,
           c.country_name,
           gm.points_average,
           gm.total_points,
           gm.points_awards,
           gm.broadcasts,
           gm.contests,
           gm.voting_countries
    INTO #ranking
    FROM grouped_metric gm
             JOIN dbo.country c ON c.country_id = gm.competing_country_id;

-------- Returning sorted paginated rankings --------

    SELECT r.rank,
           r.country_code,
           r.country_name,
           r.points_average,
           r.total_points,
           r.points_awards,
           r.broadcasts,
           r.contests,
           r.voting_countries
    FROM #ranking r
    ORDER BY CASE WHEN @descending = 1 THEN r.rank END DESC,
             CASE WHEN @descending = 0 THEN r.rank END,
             r.country_code
    OFFSET (@page_index * @page_size) ROWS FETCH NEXT (@page_size) ROWS ONLY;

------------- Returning rankings metadata ------------

    DECLARE @total_items INT = (SELECT COUNT(*) FROM #ranking);

    DECLARE @total_pages INT = dbo.udf_get_pagination_total_pages(@page_size, @total_items);

    SELECT @min_year            AS min_year,
           @max_year            AS max_year,
           @contest_stage       AS contest_stage,
           @voting_country_code AS voting_country_code,
           @voting_method       AS voting_method,
           @page_index          AS page_index,
           @page_size           AS page_size,
           @descending          AS descending,
           @total_items         AS total_items,
           @total_pages         AS total_pages;

END

GO
