SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

CREATE OR ALTER PROCEDURE dbo.usp_get_competing_country_points_consensus_rankings(
    @min_year INT = NULL,
    @max_year INT = NULL,
    @contest_stage NVARCHAR(10) = NULL,
    @voting_country_code NCHAR(2) = NULL,
    @page_index INT = 0,
    @page_size INT = 10,
    @descending BIT = 0
)
AS

/*
-- =============================================
-- Function:    dbo.usp_get_competing_country_points_consensus_rankings
-- Author:      Matt Tantony
-- Create date: 2025-11-11
--
--
-- Description:
-- ============
--  Ranks competing countries based on descending points consensus.
--
--  Returns 1) a single metadata row, then 2) a page of rankings rows.
--
--  Points consensus is a DECIMAL(18,6) between 0 and 1, calculated as the cosine similarity between the normalized
--  jury and televote points the competing country received across broadcasts, using each voting country in each
--  broadcast as a vector dimension in the comparison.
--
--  Rankings are generated by:
--      - Filtering voting data from query parameters.
--      - Normalizing each points value in the range [0, 12] to a vector value in the range [1.0, 10.0].
--      - Grouping data by competing country.
--      - Calculating points consensus metric.
--      - Ranking by descending points consensus.
--      - Sorting rankings
--          - by rank (ascending or descending)
--          - then by country code (ascending).
--      - Applying pagination.
--
--
-- Optional input parameters:
-- ==========================
--  @min_year INT
--      - Filters voting data by inclusive minimum contest year when not NULL.
--      - Allows NULL. Default value is NULL.
--  @max_year INT
--      - Filters voting data by inclusive maximum contest year when not NULL.
--      - Allows NULL. Default value is NULL.
--  @contest_stage NVARCHAR(10)
--      - Filters voting data by contest stage when not NULL.
--      - Valid 'ContestStageFilter' enum values: {'Any', 'SemiFinal1', 'SemiFinal2', 'SemiFinals', 'GrandFinal'}.
--      - Allows NULL. Default value is NULL.
--  @voting_country_code NCHAR(2)
--      - Filters voting data by voting country ISO 3166-1 alpha-2 country code when not NULL.
--      - Allows NULL. Default value is NULL.
--  @page_index INT
--      - Sets the zero-based pagination page index.
--      - Default value is 0.
--  @page_size INT
--      - Sets the pagination page size.
--      - Default value is 10.
--  @descending BIT
--      - Sets the pre-pagination initial sort to descending rank (1) or ascending rank (0).
--      - Default value is 0.
--
--
-- Returns (1 of 2):
-- =================
-- A single metadata row with the following columns:
--  - min_year INT (allows NULL)
--      - The optional inclusive minimum contest year filter value.
--  - max_year INT (allows NULL)
--      - The optional inclusive maximum contest year filter value.
--  - contest_stage NVARCHAR(10) (allows NULL)
--      - The optional contest stage filter value.
--      - Valid 'ContestStageFilter' enum values: {'Any', 'SemiFinal1', 'SemiFinal2', 'SemiFinals', 'GrandFinal'}.
--  - voting_country_code NCHAR(2) (allows NULL)
--      - The optional voting country code filter value.
--  - page_index INT
--      - The zero-based pagination.
--  - page_size INT
--      - The pagination page size.
--  - descending BIT
--      - Rankings initially sorted by descending rank (1) or ascending rank (0) before pagination.
--  - total_items INT
--      - The total number of rankings generated by the query.
--  - total_pages INT
--      - The total number of rankings pages generated by the query.
--
--
-- Returns (2 of 2):
-- =================
-- A list of 0, 1, or multiple rankings rows with the following columns:
--  - rank BIGINT
--      - The competing country's rank based on descending points consensus.
--  - country_code NCHAR(2)
--      - The competing country's ISO 3166-1 alpha-2 country code.
--  - country_name NVARCHAR(200)
--      - The competing country's short UK English name.
--  - points_consensus DECIMAL(18,6)
--      - The cosine similarity between the normalized jury and televote points the competing country received across
--        broadcasts, using each voting country in each broadcast as a vector dimension in the comparison.
--  - vector_dimensions INT
--      - The number of vector dimensions in the comparison.
--  - jury_vector_length DECIMAL(18,6)
--      - The length of the normalized jury points vector.
--  - televote_vector_length DECIMAL(18,6)
--      - The length of the normalized televote points vector.
--  - vector_dot_product DECIMAL(18,6)
--      - The dot product of the normalized jury points vector and the normalized televote points vector.
--  - broadcasts INT
--      - The number of unique broadcasts in the queried voting data for the competing country.
--  - contests INT
--      - The number of unique contests in the queried voting data for the competing country.
--  - voting_countries INT
--      - The number of unique voting countries in the queried voting data for the competing country.
-- =============================================
*/

BEGIN

    SET NOCOUNT ON;

-- Declare constants

    DECLARE @resolved_min_year INT = COALESCE(@min_year, (SELECT MIN(contest_year) FROM dbo.contest));
    DECLARE @resolved_max_year INT = COALESCE(@max_year, (SELECT MAX(contest_year) FROM dbo.contest));

-- Filter voting data

    WITH filtered_contest_broadcast AS (SELECT k.contest_id,
                                               b.broadcast_id
                                        FROM dbo.contest k
                                                 JOIN dbo.broadcast b ON b.parent_contest_id = k.contest_id
                                                 JOIN dbo.tvf_map_contest_stage_filter_enum(@contest_stage) cs
                                                      ON cs.contest_stage = b.contest_stage
                                        WHERE k.queryable = 1
                                          AND k.contest_year BETWEEN @resolved_min_year AND @resolved_max_year),

         filtered_voting_country AS (SELECT c.country_id AS voting_country_id
                                     FROM dbo.country c
                                     WHERE @voting_country_code IS NULL
                                        OR c.country_code = @voting_country_code),

         query_datum AS (SELECT bcja.competing_country_id,
                                fcb.broadcast_id,
                                fcb.contest_id,
                                fvc.voting_country_id,
                                bcja.points_value                                                                    AS jury_points_value,
                                MAX(bcja.points_value)
                                    OVER (PARTITION BY bcja.broadcast_id, bcja.voting_country_id)                    AS jury_max_points_value,
                                bcta.points_value                                                                    AS televote_points_value,
                                MAX(bcta.points_value)
                                    OVER (PARTITION BY bcta.broadcast_id, bcta.voting_country_id)                    AS televote_max_points_value
                         FROM dbo.broadcast_competitor_jury_award bcja
                                  JOIN filtered_contest_broadcast fcb ON fcb.broadcast_id = bcja.broadcast_id
                                  JOIN filtered_voting_country fvc ON fvc.voting_country_id = bcja.voting_country_id
                                  JOIN dbo.broadcast_competitor_televote_award bcta
                                       ON bcta.broadcast_id = bcja.broadcast_id AND
                                          bcta.competing_country_id = bcja.competing_country_id AND
                                          bcta.voting_country_id = bcja.voting_country_id),

-- Normalize points values

         normalized_query_datum AS (SELECT qd.competing_country_id,
                                           qd.broadcast_id,
                                           qd.contest_id,
                                           qd.voting_country_id,
                                           dbo.udf_normalize_points_value(qd.jury_points_value,
                                                                          qd.jury_max_points_value)     AS normalized_jury_points_value,
                                           dbo.udf_normalize_points_value(qd.televote_points_value,
                                                                          qd.televote_max_points_value) AS normalized_televote_points_value
                                    FROM query_datum qd),

-- Group data by competing country

         grouped_datum AS (SELECT nqd.competing_country_id,
                                  COUNT(*)                                                                     AS vector_dimensions,
                                  SQRT(SUM(POWER(nqd.normalized_jury_points_value, 2)))                        AS jury_vector_length,
                                  SQRT(SUM(POWER(nqd.normalized_televote_points_value, 2)))                    AS televote_vector_length,
                                  SUM(nqd.normalized_jury_points_value * nqd.normalized_televote_points_value) AS vector_dot_product,
                                  COUNT(DISTINCT nqd.broadcast_id)                                             AS broadcasts,
                                  COUNT(DISTINCT nqd.contest_id)                                               AS contests,
                                  COUNT(DISTINCT nqd.voting_country_id)                                        AS voting_countries
                           FROM normalized_query_datum nqd
                           GROUP BY nqd.competing_country_id),

-- Calculate points consensus metric

         grouped_metric AS (SELECT gd.competing_country_id,
                                   dbo.udf_round_to_6dp(gd.vector_dot_product /
                                                        (gd.jury_vector_length * gd.televote_vector_length)) AS points_consensus,
                                   gd.vector_dimensions,
                                   dbo.udf_round_to_6dp(gd.jury_vector_length)                               AS jury_vector_length,
                                   dbo.udf_round_to_6dp(gd.televote_vector_length)                           AS televote_vector_length,
                                   dbo.udf_round_to_6dp(gd.vector_dot_product)                               AS vector_dot_product,
                                   gd.broadcasts,
                                   gd.contests,
                                   gd.voting_countries
                            FROM grouped_datum gd)

-- Rank by descending points consensus

    SELECT RANK() OVER (ORDER BY gm.points_consensus DESC) AS rank,
           c.country_code,
           c.country_name,
           gm.points_consensus,
           gm.vector_dimensions,
           gm.jury_vector_length,
           gm.televote_vector_length,
           gm.vector_dot_product,
           gm.broadcasts,
           gm.contests,
           gm.voting_countries
    INTO #ranking
    FROM grouped_metric gm
             JOIN dbo.country c ON c.country_id = gm.competing_country_id;

-- Return single metadata row

    DECLARE @total_items INT = (SELECT COUNT(*) FROM #ranking);
    DECLARE @total_pages INT = dbo.udf_get_pagination_total_pages(@page_size, @total_items);

    SELECT @min_year            AS min_year,
           @max_year            AS max_year,
           @contest_stage       AS contest_stage,
           @voting_country_code AS voting_country_code,
           @page_index          AS page_index,
           @page_size           AS page_size,
           @descending          AS descending,
           @total_items         AS total_items,
           @total_pages         AS total_pages;

-- Return sorted paginated rankings rows

    SELECT r.rank,
           r.country_code,
           r.country_name,
           r.points_consensus,
           r.vector_dimensions,
           r.jury_vector_length,
           r.televote_vector_length,
           r.vector_dot_product,
           r.broadcasts,
           r.contests,
           r.voting_countries
    FROM #ranking r
    ORDER BY CASE WHEN @descending = 1 THEN r.rank END DESC,
             CASE WHEN @descending = 0 THEN r.rank END,
             r.country_code
    OFFSET (@page_index * @page_size) ROWS FETCH NEXT @page_size ROWS ONLY;


END

GO
