SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO


CREATE OR ALTER PROCEDURE dbo.usp_get_competitor_points_average_rankings(
    @min_year INT = NULL,
    @max_year INT = NULL,
    @contest_stage NVARCHAR(10) = NULL,
    @voting_method NVARCHAR(10) = NULL,
    @page_index INT = 0,
    @page_size INT = 10,
    @descending BIT = FALSE
)
AS

/*
-- =============================================
-- Procedure:   dbo.usp_get_competitor_points_average_rankings
-- Author:      Matt Tantony
-- Create date: 2025-11-05
--
-- Description:
--  Ranks competitors based on descending points average.
--
--  Returns 1) a page of rankings (which may be empty), then 2) a single metadata record.
--
--  Points average is a float between 0 and 12, calculated as the average individual points value the competitor
--  received in their broadcast.
--
--  Rankings are generated by:
--    - Selecting the query data based on the query parameters.
--    - Grouping data by broadcast competitor.
--    - Calculating total points, points award count, and points average.
--    - Ranking by descending points average.
--    - Sorting rankings
--      - by rank (ascending or descending)
--      - then by contest year (ascending)
--      - then by contest stage (SemiFinal1 < SemiFinal2 < GrandFinal)
--      - then by running order spot (ascending)
--    - Applying pagination.
--
-- Input parameters:
--  @min_year INT - Filters voting data by inclusive minimum contest year when not NULL.
--    Accepts NULL.
--    Default value is NULL.
--  @max_year INT - Filters voting data by inclusive maximum contest year when not NULL.
--    Accepts NULL.
--    Default value is NULL.
--  @contest_stage NVARCHAR(10). Filters voting data by contest stage when not NULL.
--    Enum values: {'Any', 'SemiFinal1', 'SemiFinal2', 'SemiFinals', 'GrandFinal'}.
--    Accepts NULL.
--    Default value is NULL.
--  @voting_method NVARCHAR(10). Filters voting data by voting method when not NULL.
--    Enum values: {'Any', 'Jury', 'Televote'}.
--    Accepts NULL.
--    Default value is NULL.
--  @page_index INT - Sets the pagination page index.
--    Default value is 0.
--  @page_size INT - Sets the pagination page size.
--    Default value is 10.
--  @descending BIT - Sorts rankings initially by descending rank (1) or ascending rank (0).
--    Default value is 0.
--
-- Returns:
--  1) A page of records with the following columns:
--    - rank INT
--    - contest_year INT
--    - contest_stage NVARCHAR(10), enum values: {'SemiFinal1', 'SemiFinal2', 'GrandFinal'}
--    - running_order_spot INT
--    - country_code NCHAR(2)
--    - country_name NVARCHAR(200)
--    - finishing_position INT
--    - act_name NVARCHAR(200)
--    - song_title NVARCHAR(200)
--    - points_average DECIMAL(9,6)
--    - total_points INT
--    - points_awards INT
--    - voting_countries INT
--
--  2) A single metadata record with the following columns:
--    - min_year INT, may be NULL
--    - max_year INT, may be NULL
--    - contest_stage NVARCHAR(10), enum values: {'Any', 'SemiFinal1', 'SemiFinal2', 'SemiFinals', 'GrandFinal'}, may be NULL
--    - voting_method NVARCHAR(10), enum values: {'Any', 'Jury', 'Televote'}, may be NULL
--    - page_index INT
--    - page_size INT
--    - descending BIT
--    - total_items INT
--    - total_pages INT
-- =============================================
*/

BEGIN

    --------------- Declaring constants -----------------

    DECLARE @resolved_min_year INT = COALESCE(@min_year, -999999);
    DECLARE @resolved_max_year INT = COALESCE(@max_year, 999999);

    DECLARE @voting_method_any NVARCHAR(10) = N'Any';
    DECLARE @voting_method_jury NVARCHAR(10) = N'Jury';
    DECLARE @voting_method_televote NVARCHAR(10) = N'Televote';
    DECLARE @resolved_voting_method NVARCHAR(10) = COALESCE(@voting_method, @voting_method_any);

    WITH

--------------- Selecting query data ----------------

filtered_broadcast AS (SELECT k.contest_id,
                              b.broadcast_id
                       FROM dbo.contest k
                                JOIN dbo.broadcast b ON b.parent_contest_id = k.contest_id
                                INNER JOIN (SELECT contest_stage
                                            FROM dbo.tvf_map_contest_stage_filter_enum(@contest_stage)) cs
                                           ON cs.contest_stage = b.contest_stage
                       WHERE k.queryable = 1
                         AND k.contest_year BETWEEN @resolved_min_year AND @resolved_max_year),

query_datum AS (SELECT bcja.broadcast_id,
                       bcja.competing_country_id,
                       bcja.voting_country_id,
                       bcja.points_value
                FROM dbo.broadcast_competitor_jury_award bcja
                         JOIN filtered_broadcast fb ON fb.broadcast_id = bcja.broadcast_id
                WHERE @resolved_voting_method <> @voting_method_televote

                UNION ALL

                SELECT bcta.broadcast_id,
                       bcta.competing_country_id,
                       bcta.voting_country_id,
                       bcta.points_value
                FROM dbo.broadcast_competitor_televote_award bcta
                         JOIN filtered_broadcast fb ON fb.broadcast_id = bcta.broadcast_id
                WHERE @resolved_voting_method <> @voting_method_jury),

------- Grouping data by broadcast competitor -------

grouped_datum AS (SELECT qd.broadcast_id,
                         qd.competing_country_id,
                         SUM(qd.points_value)                 AS total_points,
                         COUNT(*)                             AS points_awards,
                         COUNT(DISTINCT qd.voting_country_id) AS voting_countries
                  FROM query_datum qd
                  GROUP BY qd.broadcast_id, qd.competing_country_id),

-------- Calculating points average metrics ---------

grouped_metric AS (SELECT gd.broadcast_id,
                          gd.competing_country_id,
                          CAST(((1.0 * gd.total_points) / gd.points_awards) AS DECIMAL(9, 6)) AS points_average,
                          gd.total_points,
                          gd.points_awards,
                          gd.voting_countries
                   FROM grouped_datum gd)

------- Ranking by descending points average --------

    SELECT RANK() OVER (ORDER BY gm.points_average DESC)         AS rank,
           k.contest_year,
           dbo.udf_get_contest_stage_sort_order(b.contest_stage) AS contest_stage_sort_order,
           bc.running_order_spot,
           bc.finishing_position,
           k.contest_id,
           gm.broadcast_id,
           gm.competing_country_id,
           b.contest_stage,
           gm.points_average,
           gm.total_points,
           gm.points_awards,
           gm.voting_countries
    INTO #ranking
    FROM grouped_metric gm
             JOIN dbo.broadcast b ON b.broadcast_id = gm.broadcast_id
             JOIN dbo.contest k ON k.contest_id = b.parent_contest_id
             JOIN dbo.broadcast_competitor bc
                  ON bc.broadcast_id = gm.broadcast_id AND bc.competing_country_id = gm.competing_country_id;

-------- Returning sorted paginated rankings --------

    SELECT r.rank,
           r.contest_year,
           r.contest_stage,
           r.running_order_spot,
           c.country_code,
           c.country_name,
           r.finishing_position,
           cp.act_name,
           cp.song_title,
           r.points_average,
           r.total_points,
           r.points_awards,
           r.voting_countries
    FROM #ranking r
             JOIN dbo.country c ON c.country_id = r.competing_country_id
             JOIN dbo.contest_participant cp
                  ON cp.contest_id = r.contest_id AND cp.participating_country_id = r.competing_country_id
    ORDER BY CASE WHEN @descending = 1 THEN r.rank END DESC,
             CASE WHEN @descending = 0 THEN r.rank END,
             r.contest_year,
             r.contest_stage_sort_order,
             r.running_order_spot
    OFFSET (@page_index * @page_size) ROWS FETCH NEXT (@page_size) ROWS ONLY;

-------------- Returning metadata record- ------------

    DECLARE @total_items INT = (SELECT COUNT(*) FROM #ranking);

    DECLARE @total_pages INT = dbo.udf_get_pagination_total_pages(@page_size, @total_items);

    SELECT @min_year      AS min_year,
           @max_year      AS max_year,
           @contest_stage AS contest_stage,
           @voting_method AS voting_method,
           @page_index    AS page_index,
           @page_size     AS page_size,
           @descending    AS descending,
           @total_items   AS total_items,
           @total_pages   AS total_pages;

END

GO
