SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

CREATE OR ALTER PROCEDURE dbo.usp_get_voting_country_jury_points_listings(
    @contest_year INT,
    @contest_stage NVARCHAR(10),
    @voting_country_code NCHAR(2)
)
AS

/*
-- =============================================
-- Function:    dbo.usp_get_voting_country_jury_points_listings
-- Author:      Matt Tantony
-- Create date: 2025-11-15
--
--
-- Description:
-- ============
--  Returns a list of all the jury points given by a specified voting country in a specified broadcast.
--
--  Listings are generated by:
--      - Filtering voting data from query parameters.
--      - Listing points awards.
--      - Sorting points awards
--          - by points value (descending)
--          - then by competing country code (ascending).
--
--
-- Required input parameters:
-- ==========================
--  @contest_year INT
--      - Filters voting data by contest year.
--  @contest_stage NVARCHAR(10)
--      - Filters voting data by contest stage.
--      - Valid 'ContestStage' enum values: {'SemiFinal1', 'SemiFinal2', 'GrandFinal'}.
--  @voting_country_code NCHAR(2)
--      - Filters voting data by voting country ISO 3166-1 alpha-2 country code.
--
--
-- Returns:
-- ========
-- A list of 0, 1, or multiple listings rows with the following columns:
--  - points_value INT
--      - The value of the jury points award the voting country gave to the competing country.
--  - competing_country_code NCHAR(2)
--      - The competing country's ISO 3166-1 alpha-2 country code.
--  - competing_country_name NVARCHAR(200)
--      - The competing country's short UK English name.
-- =============================================
*/


BEGIN

    SET NOCOUNT ON;

-- Filter voting data

    WITH filtered_datum AS (SELECT bcja.points_value,
                                   bcja.competing_country_id
                            FROM dbo.contest k
                                     JOIN dbo.broadcast b ON b.parent_contest_id = k.contest_id
                                     JOIN dbo.broadcast_competitor_jury_award bcja ON bcja.broadcast_id = b.broadcast_id
                                     JOIN dbo.country c ON c.country_id = bcja.voting_country_id
                            WHERE k.queryable = 1
                              AND k.contest_year = @contest_year
                              AND b.contest_stage = @contest_stage
                              AND c.country_code = @voting_country_code)

-- Compile listings, sort, and return listings rows

    SELECT fd.points_value AS points_value,
           c.country_code  AS competing_country_code,
           c.country_name  AS competing_country_name
    FROM filtered_datum fd
             JOIN dbo.country c ON c.country_id = fd.competing_country_id
    ORDER BY points_value DESC, competing_country_code;


END

GO
