SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

CREATE OR ALTER PROCEDURE dbo.usp_get_voting_country_points_in_range_rankings(
    @competing_country_code NCHAR(2),
    @min_points INT,
    @max_points INT,
    @min_year INT = NULL,
    @max_year INT = NULL,
    @contest_stage NVARCHAR(10) = NULL,
    @voting_method NVARCHAR(10) = NULL,
    @page_index INT = 0,
    @page_size INT = 10,
    @descending BIT = 0
)
AS

/*
-- =============================================
-- Function:    dbo.usp_get_voting_country_points_in_range_rankings
-- Author:      Matt Tantony
-- Create date: 2025-11-14
--
--
-- Description:
-- ============
--  Ranks voting countries based on descending points in range.
--
--  Returns 1) a single metadata row, then 2) a page of rankings rows.
--
--  Points in range is a DECIMAL(18,6) between 0 and 1, calculated as the frequency of points awards within a
--  specified value range the voting country gave to a specified competing country, relative to the number of points
--  awards the voting country gave.
--
--  Rankings are generated by:
--      - Filtering voting data from query parameters.
--      - Grouping data by voting country.
--      - Calculating points in range metric.
--      - Ranking by descending points in range.
--      - Sorting rankings
--          - by rank (ascending or descending)
--          - then by country code (ascending).
--      - Applying pagination.
--
--
-- Required input parameters:
-- ==========================
-- @competing_country_code NCHAR(2)
--      - Filters voting data by competing country ISO 3166-1 alpha-2 country code.
-- @min_points INT
--      - Specifies the inclusive minimum points value.
-- @max_points INT
--      - Specifies the inclusive maximum points value.
--
--
-- Optional input parameters:
-- ==========================
--  @min_year INT
--      - Filters voting data by inclusive minimum contest year when not NULL.
--      - Allows NULL. Default value is NULL.
--  @max_year INT
--      - Filters voting data by inclusive maximum contest year when not NULL.
--      - Allows NULL. Default value is NULL.
--  @contest_stage NVARCHAR(10)
--      - Filters voting data by contest stage when not NULL.
--      - Valid 'ContestStageFilter' enum values: {'Any', 'SemiFinal1', 'SemiFinal2', 'SemiFinals', 'GrandFinal'}.
--      - Allows NULL. Default value is NULL.
--  @voting_method NVARCHAR(10)
--      - Filters voting data by voting method when not NULL.
--      - Valid 'VotingMethodFilter' enum values: {'Any', 'Jury', 'Televote'}.
--      - Allows NULL. Default value is NULL.
--  @page_index INT
--      - Sets the zero-based pagination page index.
--      - Default value is 0.
--  @page_size INT
--      - Sets the pagination page size.
--      - Default value is 10.
--  @descending BIT
--      - Specifies descending rank (1) or ascending rank (0) initial sort before pagination.
--      - Default value is 0.
--
--
-- Returns (1 of 2):
-- =================
-- A single metadata row with the following columns:
--  - competing_country_code NCHAR(2)
--      - The required competing country code filter value.
--  - min_points INT
--      - The required inclusive minimum points award value.
--  - max_points INT
--      - The required inclusive maximum points award value.
--  - min_year INT (allows NULL)
--      - The optional inclusive minimum contest year filter value.
--  - max_year INT (allows NULL)
--      - The optional inclusive maximum contest year filter value.
--  - contest_stage NVARCHAR(10) (allows NULL)
--      - The optional contest stage filter value.
--      - Valid 'ContestStageFilter' enum values: {'Any', 'SemiFinal1', 'SemiFinal2', 'SemiFinals', 'GrandFinal'}.--
--  - voting_method NVARCHAR(10) (allows NULL)
--      - The optional voting method filter value.
--      - Valid 'VotingMethodFilter' enum values: {'Any', 'Jury', 'Televote'}.
--  - page_index INT
--      - The zero-based pagination index.
--  - page_size INT
--      - The pagination page size.
--  - descending BIT
--      - Specifies descending rank (1) or ascending rank (0) initial sort before pagination.
--  - total_items INT
--      - The number of rankings generated by the query.
--  - total_pages INT
--      - The number of rankings pages generated by the query.
--
--
-- Returns (2 of 2):
-- =================
-- A list of 0, 1, or multiple rankings rows with the following columns:
--  - rank BIGINT
--      - The voting country's rank based on descending points average.
--  - country_code NCHAR(2)
--      - The voting country's ISO 3166-1 alpha-2 country code.
--  - country_name NVARCHAR(200)
--      - The voting country's short UK English name.
--  - points_in_range DECIMAL(18,6)
--      - The frequency of points awards within the specified value range the voting country gave to the specified
--        competing country across broadcasts, relative to the number of points awards the voting country gave.
--  - points_awards_in_range INT
--      - The frequency of points awards within the specified value range the voting country gave to the specified
--        competing country across broadcasts.
--  - points_awards INT
--      - The number of points awards in the queried filtered voting data for the voting country.
--  - broadcasts INT
--      - The number of unique broadcasts in the queried filtered voting data for the voting country.
--  - contests INT
--      - The number of unique contests in the queried filtered voting data for the voting country.
-- =============================================
*/

BEGIN

    SET NOCOUNT ON;

-- Declare constants

    DECLARE @resolved_min_year INT = COALESCE(@min_year, (SELECT MIN(contest_year) FROM dbo.contest));
    DECLARE @resolved_max_year INT = COALESCE(@max_year, (SELECT MAX(contest_year) FROM dbo.contest));
    DECLARE @include_jury_points BIT = IIF(@voting_method = N'Televote', 0, 1);
    DECLARE @include_televote_points BIT = IIF(@voting_method = N'Jury', 0, 1);

-- Filter voting data

    WITH filtered_contest_broadcast AS (SELECT k.contest_id,
                                               b.broadcast_id
                                        FROM dbo.contest k
                                                 JOIN dbo.broadcast b ON b.parent_contest_id = k.contest_id
                                                 JOIN dbo.tvf_map_contest_stage_filter_enum(@contest_stage) cs
                                                      ON cs.contest_stage = b.contest_stage
                                        WHERE k.queryable = 1
                                          AND k.contest_year BETWEEN @resolved_min_year AND @resolved_max_year),

         filtered_competing_country AS (SELECT c.country_id AS competing_country_id
                                        FROM dbo.country c
                                        WHERE c.country_code = @competing_country_code),

         query_datum AS (SELECT bcja.voting_country_id,
                                bcja.points_value,
                                fcb.broadcast_id,
                                fcb.contest_id
                         FROM dbo.broadcast_competitor_jury_award bcja
                                  JOIN filtered_contest_broadcast fcb ON fcb.broadcast_id = bcja.broadcast_id
                                  JOIN filtered_competing_country fvc
                                       ON fvc.competing_country_id = bcja.competing_country_id
                         WHERE @include_jury_points = 1
                         UNION ALL
                         SELECT bcta.voting_country_id,
                                bcta.points_value,
                                fcb.broadcast_id,
                                fcb.contest_id
                         FROM dbo.broadcast_competitor_televote_award bcta
                                  JOIN filtered_contest_broadcast fcb ON fcb.broadcast_id = bcta.broadcast_id
                                  JOIN filtered_competing_country fvc
                                       ON fvc.competing_country_id = bcta.competing_country_id
                         WHERE @include_televote_points = 1),

-- Group data by voting country

         grouped_datum AS (SELECT qd.voting_country_id,
                                  SUM(IIF(qd.points_value BETWEEN @min_points AND @max_points, 1, 0)) AS points_awards_in_range,
                                  COUNT(*)                                                            AS points_awards,
                                  COUNT(DISTINCT qd.broadcast_id)                                     AS broadcasts,
                                  COUNT(DISTINCT qd.contest_id)                                       AS contests
                           FROM query_datum qd
                           GROUP BY qd.voting_country_id),

-- Calculate points in range metric

         grouped_metric AS (SELECT gd.voting_country_id,
                                   dbo.udf_round_to_6dp((1.0 * gd.points_awards_in_range) / gd.points_awards) AS points_in_range,
                                   gd.points_awards_in_range,
                                   gd.points_awards,
                                   gd.broadcasts,
                                   gd.contests
                            FROM grouped_datum gd)

-- Rank by descending points average

    SELECT RANK() OVER (ORDER BY gm.points_in_range DESC) AS rank,
           c.country_code,
           c.country_name,
           gm.points_in_range,
           gm.points_awards_in_range,
           gm.points_awards,
           gm.broadcasts,
           gm.contests
    INTO #ranking
    FROM grouped_metric gm
             JOIN dbo.country c ON c.country_id = gm.voting_country_id;

-- Return single metadata row

    DECLARE @total_items INT = (SELECT COUNT(*) FROM #ranking);

    DECLARE @total_pages INT = dbo.udf_get_pagination_total_pages(@page_size, @total_items);

    SELECT @competing_country_code AS competing_country_code,
           @min_points             AS min_points,
           @max_points             AS max_points,
           @min_year               AS min_year,
           @max_year               AS max_year,
           @contest_stage          AS contest_stage,
           @voting_method          AS voting_method,
           @page_index             AS page_index,
           @page_size              AS page_size,
           @descending             AS descending,
           @total_items            AS total_items,
           @total_pages            AS total_pages;

-- Return sorted paginated rankings rows

    SELECT r.rank,
           r.country_code,
           r.country_name,
           r.points_in_range,
           r.points_awards_in_range,
           r.points_awards,
           r.broadcasts,
           r.contests
    FROM #ranking r
    ORDER BY CASE WHEN @descending = 1 THEN r.rank END DESC,
             CASE WHEN @descending = 0 THEN r.rank END,
             r.country_code
    OFFSET (@page_index * @page_size) ROWS FETCH NEXT @page_size ROWS ONLY;


END

GO
