using Eurocentric.Features.PublicApi.V1.Common.Constants;
using Eurocentric.Features.PublicApi.V1.Rankings.Competitors.GetCompetitorPointsAverageRankings;
using Eurocentric.Features.PublicApi.V1.Rankings.Competitors.GetCompetitorPointsConsensusRankings;
using Eurocentric.Features.PublicApi.V1.Rankings.Competitors.GetCompetitorPointsInRangeRankings;
using Eurocentric.Features.PublicApi.V1.Rankings.Competitors.GetCompetitorPointsShareRankings;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;

namespace Eurocentric.Features.PublicApi.V1.Rankings.Competitors;

/// <summary>
///     Extension methods to be invoked when configuring web application middleware.
/// </summary>
internal static class Middleware
{
    /// <summary>
    ///     Adds the endpoints tagged with "Competitor Rankings".
    /// </summary>
    /// <param name="builder">The endpoint route builder to which the endpoints are to be added.</param>
    internal static void MapCompetitorRankingsEndpoints(this IEndpointRouteBuilder builder)
    {
        RouteGroupBuilder group = builder.MapGroup("rankings/competitors")
            .WithTags(EndpointNames.Tags.CompetitorRankings)
            .ProducesProblem(StatusCodes.Status400BadRequest);

        group.MapGet("points-average", GetCompetitorPointsAverageRankingsFeature.ExecuteAsync)
            .WithName(EndpointNames.Routes.CompetitorRankings.GetCompetitorPointsAverageRankings)
            .WithSummary("Get competitor points average rankings")
            .WithDescription(
                """
                Returns a page of competitor rankings based on descending points average.

                Points average is a float between 0 and 12, calculated as the average individual points value received by the
                competitor in its broadcast.

                Rankings are generated by:
                - Filtering voting data.
                - Grouping data by competitor.
                - Calculating total points, points award count, and points average.
                - Ranking by descending points average.
                - Sorting by rank (ascending or descending), year, stage, and running order.
                - Applying pagination.
                """)
            .HasApiVersion(1, 0)
            .Produces<GetCompetitorPointsAverageRankingsResponse>();

        group.MapGet("points-consensus", GetCompetitorPointsConsensusRankingsFeature.ExecuteAsync)
            .WithName(EndpointNames.Routes.CompetitorRankings.GetCompetitorPointsConsensusRankings)
            .WithSummary("Get competitor points consensus rankings")
            .WithDescription(
                """
                Returns a page of competitor rankings based on descending points consensus.

                Points consensus is a float between 0 and 1, calculated as the cosine similarity
                between jury and televote points received by the competitor in its broadcast.
                Each voting country in each broadcast acts as a vector dimension in the comparison.

                Rankings are generated by:
                - Filtering voting data.
                - Normalizing points values to a scale from 1.0 to 100.0.
                - Grouping data by competitor.
                - Calculating vector lengths, dot product, and points consensus.
                - Ranking by descending points consensus.
                - Sorting by rank (ascending or descending), year, stage, and running order.
                - Applying pagination.
                """)
            .HasApiVersion(1, 0)
            .Produces<GetCompetitorPointsConsensusRankingsResponse>();

        group.MapGet("points-in-range", GetCompetitorPointsInRangeRankingsFeature.ExecuteAsync)
            .WithName(EndpointNames.Routes.CompetitorRankings.GetCompetitorPointsInRangeRankings)
            .WithSummary("Get competitor points in range rankings")
            .WithDescription(
                """
                Returns a page of competitor rankings based on descending points in range.

                Points in range is a float between 0 and 1, calculated as the frequency of points awards within a given range
                received by the competitor in its broadcast, relative to the number of points awards it received.

                Rankings are generated by:
                - Filtering voting data.
                - Grouping data by competitor.
                - Calculating points award counts and points in range.
                - Ranking by descending points in range.
                - Sorting by rank (ascending or descending), year, stage, and running order.
                - Applying pagination.
                """)
            .HasApiVersion(1, 0)
            .Produces<GetCompetitorPointsInRangeRankingsResponse>();

        group.MapGet("points-share", GetCompetitorPointsShareRankingsFeature.ExecuteAsync)
            .WithName(EndpointNames.Routes.CompetitorRankings.GetCompetitorPointsShareRankings)
            .WithSummary("Get competitor points share rankings")
            .WithDescription(
                """
                Returns a page of competitor rankings based on descending points share.

                Points share is a float between 0 and 1, calculated as the total points received by the competitor in its
                broadcast as a fraction of the maximum available points.

                Rankings are generated by:
                - Filtering voting data.
                - Grouping data by competitor.
                - Calculating total points, available points, and points share.
                - Ranking by descending points share.
                - Sorting by rank (ascending or descending), year, stage, and running order.
                - Applying pagination.
                """)
            .HasApiVersion(1, 0)
            .Produces<GetCompetitorPointsShareRankingsResponse>();
    }
}
