using CSharpFunctionalExtensions;
using Eurocentric.Apis.Public.V1.Config;
using Eurocentric.Apis.Public.V1.Dtos.CompetitorRankings;
using Eurocentric.Apis.Public.V1.Enums;
using Eurocentric.Components.EndpointMapping;
using Eurocentric.Components.Messaging;
using Eurocentric.Domain.Analytics.Rankings.Competitors;
using Eurocentric.Domain.Core;
using JetBrains.Annotations;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using SlimMessageBus;
using IResult = Microsoft.AspNetCore.Http.IResult;

namespace Eurocentric.Apis.Public.V1.Features.CompetitorRankings;

internal static class GetCompetitorPointsShareRankings
{
    private static async Task<IResult> ExecuteAsync(
        [AsParameters] GetCompetitorPointsShareRankingsRequest request,
        [FromServices] IRequestResponseBus bus,
        CancellationToken ct = default
    ) => await bus.DispatchAsync(request.ToQuery(), MapToOk, ct);

    private static Query ToQuery(this GetCompetitorPointsShareRankingsRequest request)
    {
        return new Query
        {
            MinYear = request.MinYear,
            MaxYear = request.MaxYear,
            ContestStage = request.ContestStage?.ToDomainContestStageFilter(),
            CompetingCountryCode = request.CompetingCountryCode,
            VotingMethod = request.VotingMethod?.ToDomainVotingMethodFilter(),
            PageIndex = request.PageIndex,
            PageSize = request.PageSize,
            Descending = request.Descending,
        };
    }

    private static Ok<GetCompetitorPointsShareRankingsResponse> MapToOk(PointsShareRankings rankings)
    {
        (List<PointsShareRanking> rankingRecords, PointsShareMetadata metadataRecord) = rankings;

        return TypedResults.Ok(
            new GetCompetitorPointsShareRankingsResponse(
                rankingRecords.Select(ranking => ranking.ToDto()).ToArray(),
                metadataRecord.ToDto()
            )
        );
    }

    internal sealed class EndpointMapper : IEndpointMapper
    {
        public void MapEndpoint(RouteGroupBuilder routeBuilder)
        {
            routeBuilder
                .MapGet("competitor-rankings/points-share", ExecuteAsync)
                .WithName(V1EndpointNames.CompetitorRankings.GetCompetitorPointsShareRankings)
                .AddedInVersion1Point0()
                .WithSummary("Get competitor points share rankings")
                .WithDescription(
                    """
                    Ranks competitors in broadcasts based on *descending points share*.

                    Returns a page of rankings and a metadata object.

                    Points share is a float between 0 and 1, calculated as the sum total points the competitor received
                    in the broadcast as a fraction of the available points.

                    Rankings are generated by:

                    - Filtering voting data from query parameters.
                    - Grouping data by broadcast competitor.
                    - Calculating points share metric.
                    - Ranking by descending points share.
                    - Sorting rankings
                        - by rank (ascending or descending)
                        - then by contest year (ascending)
                        - then by contest stage (SemiFinal1 < SemiFinal2 < GrandFinal)
                        - then by running order spot (ascending)
                    - Applying pagination.
                    """
                )
                .WithTags(V1Tags.CompetitorRankings)
                .Produces<GetCompetitorPointsShareRankingsResponse>()
                .ProducesProblem(StatusCodes.Status400BadRequest)
                .ProducesProblem(StatusCodes.Status422UnprocessableEntity);
        }
    }

    internal sealed record Query : PointsShareQuery, IQuery<PointsShareRankings>;

    [UsedImplicitly]
    internal sealed class QueryHandler(ICompetitorRankingsGateway gateway) : IQueryHandler<Query, PointsShareRankings>
    {
        public async Task<Result<PointsShareRankings, IDomainError>> OnHandle(Query query, CancellationToken ct) =>
            await gateway.GetPointsShareRankingsAsync(query, ct);
    }
}
