using CSharpFunctionalExtensions;
using Eurocentric.Apis.Public.V1.Config;
using Eurocentric.Apis.Public.V1.Dtos.CompetitorRankings;
using Eurocentric.Apis.Public.V1.Enums;
using Eurocentric.Components.EndpointMapping;
using Eurocentric.Components.Messaging;
using Eurocentric.Domain.Analytics.Rankings.Competitors;
using Eurocentric.Domain.Core;
using JetBrains.Annotations;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using SlimMessageBus;
using IResult = Microsoft.AspNetCore.Http.IResult;

namespace Eurocentric.Apis.Public.V1.Features.CompetitorRankings;

internal static class GetCompetitorPointsInRangeRankings
{
    private static async Task<IResult> ExecuteAsync(
        [AsParameters] GetCompetitorPointsInRangeRankingsRequest request,
        [FromServices] IRequestResponseBus bus,
        CancellationToken ct = default
    ) => await bus.DispatchAsync(request.ToQuery(), MapToOk, ct);

    private static Query ToQuery(this GetCompetitorPointsInRangeRankingsRequest request)
    {
        return new Query
        {
            MinPoints = request.MinPoints,
            MaxPoints = request.MaxPoints,
            MinYear = request.MinYear,
            MaxYear = request.MaxYear,
            ContestStage = request.ContestStage?.ToDomainContestStageFilter(),
            CompetingCountryCode = request.CompetingCountryCode,
            VotingMethod = request.VotingMethod?.ToDomainVotingMethodFilter(),
            PageIndex = request.PageIndex,
            PageSize = request.PageSize,
            Descending = request.Descending,
        };
    }

    private static Ok<GetCompetitorPointsInRangeRankingsResponse> MapToOk(PointsInRangeRankings rankings)
    {
        (List<PointsInRangeRanking> rankingRecords, PointsInRangeMetadata metadataRecord) = rankings;

        return TypedResults.Ok(
            new GetCompetitorPointsInRangeRankingsResponse(
                rankingRecords.Select(ranking => ranking.ToDto()).ToArray(),
                metadataRecord.ToDto()
            )
        );
    }

    internal sealed class EndpointMapper : IEndpointMapper
    {
        public void MapEndpoint(RouteGroupBuilder routeBuilder)
        {
            routeBuilder
                .MapGet("competitor-rankings/points-in-range", ExecuteAsync)
                .WithName(V1EndpointNames.CompetitorRankings.GetCompetitorPointsInRangeRankings)
                .AddedInVersion1Point0()
                .WithSummary("Get competitor points in range rankings")
                .WithDescription(
                    """
                    Ranks competitors in broadcasts based on *descending points in range*.

                    Returns a page of rankings and a metadata object.

                    Points in range is a float between 0 and 1, calculated as the frequency of points awards within a
                    specified value range the competitor received in their broadcast, relative to the number of points
                    awards the competitor received.

                    Rankings are generated by:

                    - Filtering voting data from query parameters.
                    - Grouping data by broadcast competitor.
                    - Calculating points in range metric.
                    - Ranking by descending points in range.
                    - Sorting rankings
                        - by rank (ascending or descending)
                        - then by contest year (ascending)
                        - then by contest stage (SemiFinal1 < SemiFinal2 < GrandFinal)
                        - then by running order spot (ascending)
                    - Applying pagination.
                    """
                )
                .WithTags(V1Tags.CompetitorRankings)
                .Produces<GetCompetitorPointsInRangeRankingsResponse>()
                .ProducesProblem(StatusCodes.Status400BadRequest)
                .ProducesProblem(StatusCodes.Status422UnprocessableEntity);
        }
    }

    internal sealed record Query : PointsInRangeQuery, IQuery<PointsInRangeRankings>;

    [UsedImplicitly]
    internal sealed class QueryHandler(ICompetitorRankingsGateway gateway) : IQueryHandler<Query, PointsInRangeRankings>
    {
        public async Task<Result<PointsInRangeRankings, IDomainError>> OnHandle(Query query, CancellationToken ct) =>
            await gateway.GetPointsInRangeRankingsAsync(query, ct);
    }
}
