using CSharpFunctionalExtensions;
using Eurocentric.Apis.Public.V1.Config;
using Eurocentric.Apis.Public.V1.Dtos.CompetingCountryRankings;
using Eurocentric.Apis.Public.V1.Enums;
using Eurocentric.Components.EndpointMapping;
using Eurocentric.Components.Messaging;
using Eurocentric.Domain.Analytics.Rankings.CompetingCountries;
using Eurocentric.Domain.Core;
using JetBrains.Annotations;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using SlimMessageBus;
using IResult = Microsoft.AspNetCore.Http.IResult;

namespace Eurocentric.Apis.Public.V1.Features.CompetingCountryRankings;

internal static class GetCompetingCountryPointsInRangeRankings
{
    private static async Task<IResult> ExecuteAsync(
        [AsParameters] GetCompetingCountryPointsInRangeRankingsRequest request,
        [FromServices] IRequestResponseBus bus,
        CancellationToken ct = default
    ) => await bus.DispatchAsync(request.ToQuery(), MapToOk, ct);

    private static Query ToQuery(this GetCompetingCountryPointsInRangeRankingsRequest request)
    {
        return new Query
        {
            MinPoints = request.MinPoints,
            MaxPoints = request.MaxPoints,
            MinYear = request.MinYear,
            MaxYear = request.MaxYear,
            ContestStage = request.ContestStage?.ToDomainContestStageFilter(),
            VotingCountryCode = request.VotingCountryCode,
            VotingMethod = request.VotingMethod?.ToDomainVotingMethodFilter(),
            PageIndex = request.PageIndex,
            PageSize = request.PageSize,
            Descending = request.Descending,
        };
    }

    private static Ok<GetCompetingCountryPointsInRangeRankingsResponse> MapToOk(PointsInRangeRankings rankings)
    {
        (List<PointsInRangeRanking> rankingRecords, PointsInRangeMetadata metadataRecord) = rankings;

        return TypedResults.Ok(
            new GetCompetingCountryPointsInRangeRankingsResponse(
                rankingRecords.Select(ranking => ranking.ToDto()).ToArray(),
                metadataRecord.ToDto()
            )
        );
    }

    internal sealed class EndpointMapper : IEndpointMapper
    {
        public void MapEndpoint(RouteGroupBuilder routeBuilder)
        {
            routeBuilder
                .MapGet("competing-country-rankings/points-in-range", ExecuteAsync)
                .WithName(V1EndpointNames.CompetingCountryRankings.GetCompetingCountryPointsInRangeRankings)
                .AddedInVersion1Point0()
                .WithSummary("Get competing country points in range rankings")
                .WithDescription(
                    """
                    Ranks competing countries based on *descending points in range*.

                    Returns a page of rankings and a metadata object.

                    Points in range is a float between 0 and 1, calculated as the frequency of points awards within a
                    specified value range the competing country received across broadcasts, relative to the number of
                    points awards the competing country received.

                    Rankings are generated by:

                    - Filtering voting data from query parameters.
                    - Grouping data by competing country.
                    - Calculating points in range metric.
                    - Ranking by descending points in range.
                    - Sorting rankings
                        - by rank (ascending or descending)
                        - then by country code (ascending).
                    - Applying pagination.
                    """
                )
                .WithTags(V1Tags.CompetingCountryRankings)
                .Produces<GetCompetingCountryPointsInRangeRankingsResponse>()
                .ProducesProblem(StatusCodes.Status400BadRequest)
                .ProducesProblem(StatusCodes.Status422UnprocessableEntity);
        }
    }

    internal sealed record Query : PointsInRangeQuery, IQuery<PointsInRangeRankings>;

    [UsedImplicitly]
    internal sealed class QueryHandler(ICompetingCountryRankingsGateway gateway)
        : IQueryHandler<Query, PointsInRangeRankings>
    {
        public async Task<Result<PointsInRangeRankings, IDomainError>> OnHandle(Query query, CancellationToken ct) =>
            await gateway.GetPointsInRangeRankingsAsync(query, ct);
    }
}
