using CSharpFunctionalExtensions;
using Eurocentric.Apis.Public.V1.Config;
using Eurocentric.Apis.Public.V1.Dtos.CompetingCountryRankings;
using Eurocentric.Apis.Public.V1.Enums;
using Eurocentric.Components.EndpointMapping;
using Eurocentric.Components.Messaging;
using Eurocentric.Domain.Analytics.Rankings.CompetingCountries;
using Eurocentric.Domain.Core;
using JetBrains.Annotations;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using SlimMessageBus;
using IResult = Microsoft.AspNetCore.Http.IResult;

namespace Eurocentric.Apis.Public.V1.Features.CompetingCountryRankings;

internal static class GetCompetingCountryPointsAverageRankings
{
    private static async Task<IResult> ExecuteAsync(
        [AsParameters] GetCompetingCountryPointsAverageRankingsRequest request,
        [FromServices] IRequestResponseBus bus,
        CancellationToken ct = default
    ) => await bus.DispatchAsync(request.ToQuery(), MapToOk, ct);

    private static Query ToQuery(this GetCompetingCountryPointsAverageRankingsRequest request)
    {
        return new Query
        {
            MinYear = request.MinYear,
            MaxYear = request.MaxYear,
            ContestStage = request.ContestStage?.ToDomainContestStageFilter(),
            VotingCountryCode = request.VotingCountryCode,
            VotingMethod = request.VotingMethod?.ToDomainVotingMethodFilter(),
            PageIndex = request.PageIndex,
            PageSize = request.PageSize,
            Descending = request.Descending,
        };
    }

    private static Ok<GetCompetingCountryPointsAverageRankingsResponse> MapToOk(PointsAverageRankings rankings)
    {
        (List<PointsAverageRanking> rankingRecords, PointsAverageMetadata metadataRecord) = rankings;

        return TypedResults.Ok(
            new GetCompetingCountryPointsAverageRankingsResponse(
                rankingRecords.Select(ranking => ranking.ToDto()).ToArray(),
                metadataRecord.ToDto()
            )
        );
    }

    internal sealed class EndpointMapper : IEndpointMapper
    {
        public void MapEndpoint(RouteGroupBuilder routeBuilder)
        {
            routeBuilder
                .MapGet("competing-country-rankings/points-average", ExecuteAsync)
                .WithName(V1EndpointNames.CompetingCountryRankings.GetCompetingCountryPointsAverageRankings)
                .AddedInVersion1Point0()
                .WithSummary("Get competing country points average rankings")
                .WithDescription(
                    """
                    Ranks competing countries based on *descending points average*.

                    Returns a page of rankings and a metadata object.

                    Points average is a float between 0 and 12, calculated as the average individual points value
                    the competing country received across broadcasts.

                    Rankings are generated by:

                    - Selecting the query data based on the query parameters.
                    - Grouping data by competing country.
                    - Calculating total points, points award count, and points average.
                    - Ranking by descending points average.
                    - Sorting rankings
                      - by rank (ascending or descending)
                      - then by country code (ascending).
                    - Applying pagination.
                    """
                )
                .WithTags(V1Tags.CompetingCountryRankings)
                .Produces<GetCompetingCountryPointsAverageRankingsResponse>()
                .ProducesProblem(StatusCodes.Status400BadRequest)
                .ProducesProblem(StatusCodes.Status422UnprocessableEntity);
        }
    }

    internal sealed record Query : PointsAverageQuery, IQuery<PointsAverageRankings>;

    [UsedImplicitly]
    internal sealed class QueryHandler(ICompetingCountryRankingsGateway gateway)
        : IQueryHandler<Query, PointsAverageRankings>
    {
        public async Task<Result<PointsAverageRankings, IDomainError>> OnHandle(Query query, CancellationToken ct) =>
            await gateway.GetPointsAverageRankingsAsync(query, ct);
    }
}
