using CSharpFunctionalExtensions;
using Eurocentric.Apis.Public.V1.Config;
using Eurocentric.Apis.Public.V1.Dtos.CompetingCountryRankings;
using Eurocentric.Apis.Public.V1.Enums;
using Eurocentric.Components.EndpointMapping;
using Eurocentric.Components.Messaging;
using Eurocentric.Domain.Analytics.Rankings.CompetingCountries;
using Eurocentric.Domain.Core;
using JetBrains.Annotations;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using SlimMessageBus;
using IResult = Microsoft.AspNetCore.Http.IResult;

namespace Eurocentric.Apis.Public.V1.Features.CompetingCountryRankings;

internal static class GetCompetingCountryPointsConsensusRankings
{
    private static async Task<IResult> ExecuteAsync(
        [AsParameters] GetCompetingCountryPointsConsensusRankingsRequest request,
        [FromServices] IRequestResponseBus bus,
        CancellationToken ct = default
    ) => await bus.DispatchAsync(request.ToQuery(), MapToOk, ct);

    private static Query ToQuery(this GetCompetingCountryPointsConsensusRankingsRequest request)
    {
        return new Query
        {
            MinYear = request.MinYear,
            MaxYear = request.MaxYear,
            ContestStage = request.ContestStage?.ToDomainContestStageFilter(),
            VotingCountryCode = request.VotingCountryCode,
            PageIndex = request.PageIndex,
            PageSize = request.PageSize,
            Descending = request.Descending,
        };
    }

    private static Ok<GetCompetingCountryPointsConsensusRankingsResponse> MapToOk(PointsConsensusRankings rankings)
    {
        (List<PointsConsensusRanking> rankingRecords, PointsConsensusMetadata metadataRecord) = rankings;

        return TypedResults.Ok(
            new GetCompetingCountryPointsConsensusRankingsResponse(
                rankingRecords.Select(ranking => ranking.ToDto()).ToArray(),
                metadataRecord.ToDto()
            )
        );
    }

    internal sealed class EndpointMapper : IEndpointMapper
    {
        public void MapEndpoint(RouteGroupBuilder routeBuilder)
        {
            routeBuilder
                .MapGet("competing-country-rankings/points-consensus", ExecuteAsync)
                .WithName(V1EndpointNames.CompetingCountryRankings.GetCompetingCountryPointsConsensusRankings)
                .AddedInVersion1Point0()
                .WithSummary("Get competing country points consensus rankings")
                .WithDescription(
                    """
                    Ranks competing countries based on *descending points consensus*.

                    Returns a page of rankings and a metadata object.

                    Points consensus is a float between 0 and 1, calculated as the cosine similarity between the
                    normalized jury and televote points the competing country received across broadcasts, using each
                    voting country in each broadcast as a vector dimension in the comparison.

                    Rankings are generated by:

                    - Filtering voting data from query parameters.
                    - Normalizing each points value in the range [0, 12] to a vector value in the range [1.0, 10.0].
                    - Grouping data by competing country.
                    - Calculating points consensus metric.
                    - Ranking by descending points consensus.
                    - Sorting rankings
                        - by rank (ascending or descending)
                        - then by country code (ascending).
                    - Applying pagination.
                    """
                )
                .WithTags(V1Tags.CompetingCountryRankings)
                .Produces<GetCompetingCountryPointsConsensusRankingsResponse>()
                .ProducesProblem(StatusCodes.Status400BadRequest)
                .ProducesProblem(StatusCodes.Status422UnprocessableEntity);
        }
    }

    internal sealed record Query : PointsConsensusQuery, IQuery<PointsConsensusRankings>;

    [UsedImplicitly]
    internal sealed class QueryHandler(ICompetingCountryRankingsGateway gateway)
        : IQueryHandler<Query, PointsConsensusRankings>
    {
        public async Task<Result<PointsConsensusRankings, IDomainError>> OnHandle(Query query, CancellationToken ct) =>
            await gateway.GetPointsConsensusRankingsAsync(query, ct);
    }
}
