SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

CREATE PROCEDURE dbo.usp_get_competitor_points_consensus_rankings(
    @contest_stages tvp_enum_int_value READONLY,
    @min_year INT = NULL,
    @max_year INT = NULL,
    @descending BIT,
    @page_index INT,
    @page_size INT,
    @total_items INT OUTPUT
)
AS

/*
-- =============================================
-- Procedure:   dbo.usp_get_competitor_points_consensus_rankings
-- Author:      Matt Tantony
-- Create date: 2025-08-23
--    
-- Description: 
--  Returns a page of competitor rankings based on descending points consensus.
--  Points consensus is a float between 0 and 1, calculated as the cosine similarity between jury and televote points 
--  received by the competitor in their broadcast. Each voting country in each broadcast acts as a vector dimension in 
--  the comparison.
--
-- Rankings are generated by:
--  - Filtering voting data.
--  - Normalizing points values to a scale from 1.0 to 100.0.
--  - Grouping data by competitor.
--  - Calculating vector lengths, dot product, and points consensus.
--  - Ranking by descending points consensus.
--  - Sorting by rank (ascending or descending), year, stage, and running order.
--  - Applying pagination.
-- 
-- Input parameters:
--  @contest_stages TVP - Filters voting data by contest stage int enum values.
--  @min_year INT - Filters voting data by inclusive minimum contest year when not null. Default is null.
--  @max_year INT - Filters voting data by inclusive maximum contest year when not null. Default is null.
--  @descending BIT - Sorts rankings by descending rank before pagination.
--  @page_index INT - Sets the zero-based pagination page index.
--  @page_size INT - Sets the pagination page size.
--
-- Output parameter:
--  @total_items INT - Is set to the total number of rankings before pagination.
--
-- Returns a page of records with the following columns:
--  - rank INT
--  - contest_year INT
--  - contest_stage INT [enum {0,1,2}]
--  - running_order_position INT
--  - country_code NCHAR(2)
--  - country_name NVARCHAR(200)
--  - finishing_position INT
--  - act_name NVARCHAR(200)
--  - song_title NVARCHAR(200)
--  - points_consensus DECIMAL(9,6)
--  - vector_dot_product DECIMAL(18,6)
--  - jury_vector_length DECIMAL(18,6)
--  - televote_vector_length DECIMAL(18,6)
--  - points_award_pairs INT
-- =============================================
*/

BEGIN

    SET NOCOUNT ON;

    WITH

        --------------- Filtering voting data ---------------

        filtered_broadcast AS (SELECT b.id                AS broadcast_id,
                                      b.parent_contest_id AS contest_id
                               FROM dbo.contest e
                                        JOIN dbo.broadcast b ON b.parent_contest_id = e.id
                                        JOIN @contest_stages cs ON cs.value = b.contest_stage
                               WHERE e.completed = 1
                                 AND (@min_year IS NULL OR e.contest_year >= @min_year)
                                 AND (@max_year IS NULL OR e.contest_year <= @max_year)),

        query_datum AS (SELECT bcja.broadcast_id,
                               bcja.competing_country_id,
                               bcja.points_value                                                 AS jury_value,
                               MAX(bcja.points_value)
                                   OVER (PARTITION BY bcja.broadcast_id, bcja.voting_country_id) AS jury_max,
                               bcta.points_value                                                 AS televote_value,
                               MAX(bcta.points_value)
                                   OVER (PARTITION BY bcta.broadcast_id, bcta.voting_country_id) AS televote_max
                        FROM dbo.broadcast_competitor_jury_award bcja
                                 JOIN filtered_broadcast fb ON fb.broadcast_id = bcja.broadcast_id
                                 JOIN dbo.broadcast_competitor_televote_award bcta
                                      ON bcta.broadcast_id = bcja.broadcast_id
                                          AND bcta.competing_country_id = bcja.competing_country_id
                                          AND bcta.voting_country_id = bcja.voting_country_id),

        ------------- Normalizing points values -------------

        normalized_query_datum AS (SELECT qd.broadcast_id,
                                          qd.competing_country_id,
                                          GREATEST(1.0, (100.0 * qd.jury_value) / qd.jury_max)         AS normalized_jury_value,
                                          GREATEST(1.0, (100.0 * qd.televote_value) / qd.televote_max) AS normalized_televote_value
                                   FROM query_datum qd),

        ------------- Grouping data by competitor -----------

        grouped_datum AS (SELECT nqd.broadcast_id,
                                 nqd.competing_country_id,
                                 SUM(nqd.normalized_jury_value * nqd.normalized_televote_value) AS vector_dot_product,
                                 SQRT(SUM(POWER(nqd.normalized_jury_value, 2)))                 AS jury_vector_length,
                                 SQRT(SUM(POWER(nqd.normalized_televote_value, 2)))             AS televote_vector_length,
                                 COUNT(*)                                                       AS points_award_pairs
                          FROM normalized_query_datum nqd
                          GROUP BY nqd.broadcast_id, nqd.competing_country_id),

        ------- Calculating points consensus metrics --------

        metric AS (SELECT gd.broadcast_id,
                          gd.competing_country_id,
                          gd.vector_dot_product /
                          (gd.jury_vector_length * gd.televote_vector_length) AS points_consensus,
                          gd.vector_dot_product,
                          gd.jury_vector_length,
                          gd.televote_vector_length,
                          gd.points_award_pairs
                   FROM grouped_datum gd)

    ------ Ranking by descending points consensus -------

    SELECT RANK() OVER (ORDER BY m.points_consensus DESC) AS rank,
           e.contest_year,
           b.contest_stage,
           bc.running_order_position,
           c.country_code,
           c.country_name,
           bc.finishing_position,
           cp.act_name,
           cp.song_title,
           m.points_consensus,
           m.vector_dot_product,
           m.jury_vector_length,
           m.televote_vector_length,
           m.points_award_pairs
    INTO #ranking
    FROM metric m
             JOIN dbo.country c ON c.id = m.competing_country_id
             JOIN dbo.broadcast b ON b.id = m.broadcast_id
             JOIN dbo.broadcast_competitor bc
                  ON bc.broadcast_id = m.broadcast_id AND bc.competing_country_id = m.competing_country_id
             JOIN dbo.contest e ON e.id = b.parent_contest_id
             JOIN dbo.contest_participant cp
                  ON cp.contest_id = e.id AND cp.participating_country_id = m.competing_country_id;

    -------- Setting @total_items output param ----------

    SET @total_items = (SELECT COUNT(*) FROM #ranking);

    --------------- Sorting and paginating --------------

    SELECT r.rank,
           r.contest_year,
           r.contest_stage,
           r.running_order_position,
           r.country_code,
           r.country_name,
           r.finishing_position,
           r.act_name,
           r.song_title,
           CAST(r.points_consensus AS DECIMAL(9, 6))        AS points_consensus,
           CAST(r.vector_dot_product AS DECIMAL(18, 6))     AS vector_dot_product,
           CAST(r.jury_vector_length AS DECIMAL(18, 6))     AS jury_vector_length,
           CAST(r.televote_vector_length AS DECIMAL(18, 6)) AS televote_vector_length,
           r.points_award_pairs
    FROM #ranking r
    ORDER BY CASE WHEN @descending = 1 THEN r.rank END DESC,
             CASE WHEN @descending = 0 THEN r.rank END,
             r.contest_year,
             r.contest_stage,
             r.running_order_position
    OFFSET (@page_index * @page_size) ROWS FETCH NEXT (@page_size) ROWS ONLY;

END
GO