SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

CREATE PROCEDURE dbo.usp_get_competing_country_points_in_range_rankings(
    @min_points INT,
    @max_points INT,
    @contest_stages tvp_enum_int_value READONLY,
    @exclude_jury BIT,
    @exclude_televote BIT,
    @min_year INT = NULL,
    @max_year INT = NULL,
    @voting_country_code NCHAR(2) = NULL,
    @descending BIT,
    @page_index INT,
    @page_size INT,
    @total_items INT OUTPUT
)
AS

/*
-- =============================================
-- Procedure:   dbo.usp_get_competing_country_points_in_range_rankings
-- Author:      Matt Tantony
-- Create date: 2025-08-22
--    
-- Description: 
--  Returns a page of competing country rankings based on descending points in range.
--  Points in range is a float between 0 and 1, calculated as the frequency of points awards within a given range 
--  received by the competing country across broadcasts, relative to the number of points awards it received.
--
-- Rankings are generated by:
--  - Filtering voting data.
--  - Grouping data by competing country.
--  - Calculating points award counts and points in range.
--  - Ranking by descending points in range.
--  - Sorting by rank (ascending or descending) and country code.
--  - Applying pagination.
-- 
-- Input parameters:
--  @min_points INT - Sets the inclusive points range minimum.
--  @max_points INT - Sets the inclusive points range maximum.
--  @contest_stages TVP - Filters voting data by contest stage int enum values.
--  @exclude_jury BIT - Excludes jury points from voting data.
--  @exclude_televote BIT - Excludes televote points from voting data.
--  @min_year INT - Filters voting data by inclusive minimum contest year when not null. Default is null.
--  @max_year INT - Filters voting data by inclusive maximum contest year when not null. Default is null.
--  @voting_country_code NCHAR(2) - Filters voting data by voting country code when not null. Default is null.
--  @descending BIT - Sorts rankings by descending rank before pagination.
--  @page_index INT - Sets the zero-based pagination page index.
--  @page_size INT - Sets the pagination page size.
--
-- Output parameter:
--  @total_items INT - Is set to the total number of rankings before pagination.
--
-- Returns a page of records with the following columns:
--  - rank INT
--  - country_code NCHAR(2)
--  - country_name NVARCHAR(200)
--  - points_in_range DECIMAL(9,6)
--  - points_awards_in_range INT
--  - points_awards INT
--  - broadcasts INT
--  - contests INT
--  - voting_countries INT
-- =============================================
*/

BEGIN

    SET NOCOUNT ON;

    WITH

        --------------- Filtering voting data ---------------

        filtered_broadcast AS (SELECT b.id                AS broadcast_id,
                                      b.parent_contest_id AS contest_id
                               FROM dbo.contest e
                                        JOIN dbo.broadcast b ON b.parent_contest_id = e.id
                                        JOIN @contest_stages cs ON cs.value = b.contest_stage
                               WHERE e.completed = 1
                                 AND (@min_year IS NULL OR e.contest_year >= @min_year)
                                 AND (@max_year IS NULL OR e.contest_year <= @max_year)),

        filtered_voting_country AS (SELECT c.id AS voting_country_id
                                    FROM dbo.country c
                                    WHERE (@voting_country_code IS NULL OR c.country_code = @voting_country_code)),

        query_datum AS (SELECT bcja.competing_country_id,
                               fb.contest_id,
                               bcja.broadcast_id,
                               bcja.voting_country_id,
                               IIF(bcja.points_value BETWEEN @min_points AND @max_points, 1, 0) AS points_award_in_range
                        FROM dbo.broadcast_competitor_jury_award bcja
                                 JOIN filtered_broadcast fb ON fb.broadcast_id = bcja.broadcast_id
                                 JOIN filtered_voting_country fvc ON fvc.voting_country_id = bcja.voting_country_id
                        WHERE @exclude_jury = 0
                        UNION ALL
                        SELECT bcta.competing_country_id,
                               fb.contest_id,
                               bcta.broadcast_id,
                               bcta.voting_country_id,
                               IIF(bcta.points_value BETWEEN @min_points AND @max_points, 1, 0) AS points_award_in_range
                        FROM dbo.broadcast_competitor_televote_award bcta
                                 JOIN filtered_broadcast fb ON fb.broadcast_id = bcta.broadcast_id
                                 JOIN filtered_voting_country fvc ON fvc.voting_country_id = bcta.voting_country_id
                        WHERE @exclude_televote = 0),

        -------- Grouping data by competing country ---------

        grouped_datum AS (SELECT qd.competing_country_id,
                                 SUM(qd.points_award_in_range)        AS points_awards_in_range,
                                 COUNT(*)                             AS points_awards,
                                 COUNT(DISTINCT qd.broadcast_id)      AS broadcasts,
                                 COUNT(DISTINCT qd.contest_id)        AS contests,
                                 COUNT(DISTINCT qd.voting_country_id) AS voting_countries
                          FROM query_datum qd
                          GROUP BY qd.competing_country_id),

        -------- Calculating points in range metrics --------

        metric AS (SELECT gd.competing_country_id,
                          (1.0 * gd.points_awards_in_range) / gd.points_awards AS points_in_range,
                          gd.points_awards_in_range,
                          gd.points_awards,
                          gd.broadcasts,
                          gd.contests,
                          gd.voting_countries
                   FROM grouped_datum gd)

    ------- Ranking by descending points in range -------

    SELECT RANK() OVER (ORDER BY m.points_in_range DESC) AS rank,
           c.country_code,
           c.country_name,
           m.points_in_range,
           m.points_awards_in_range,
           m.points_awards,
           m.broadcasts,
           m.contests,
           m.voting_countries
    INTO #ranking
    FROM metric m
             JOIN dbo.country c ON c.id = m.competing_country_id;

    -------- Setting @total_items output param ----------

    SET @total_items = (SELECT COUNT(*) FROM #ranking);

    --------------- Sorting and paginating --------------

    SELECT r.rank,
           r.country_code,
           r.country_name,
           CAST(r.points_in_range AS DECIMAL(9, 6)) AS points_in_range,
           r.points_awards_in_range,
           r.points_awards,
           r.broadcasts,
           r.contests,
           r.voting_countries
    FROM #ranking r
    ORDER BY CASE WHEN @descending = 1 THEN r.rank END DESC,
             CASE WHEN @descending = 0 THEN r.rank END,
             r.country_code
    OFFSET (@page_index * @page_size) ROWS FETCH NEXT (@page_size) ROWS ONLY;

END
GO