SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

CREATE PROCEDURE dbo.usp_get_competitor_points_in_range_rankings(
    @min_points INT,
    @max_points INT,
    @contest_stages tvp_enum_int_value READONLY,
    @exclude_jury BIT,
    @exclude_televote BIT,
    @min_year INT = NULL,
    @max_year INT = NULL,
    @descending BIT,
    @page_index INT,
    @page_size INT,
    @total_items INT OUTPUT
)
AS

/*
-- =============================================
-- Procedure:   dbo.usp_get_competitor_points_in_range_rankings
-- Author:      Matt Tantony
-- Create date: 2025-08-23
--    
-- Description: 
--  Returns a page of competitor rankings based on descending points in range.
--  Points in range is a float between 0 and 1, calculated as the frequency of points awards within a given range 
--  received by the competitor in their broadcast, relative to the number of points awards they received.
--
-- Rankings are generated by:
--  - Filtering voting data.
--  - Grouping data by competitor.
--  - Calculating points award counts and points in range.
--  - Ranking by descending points in range.
--  - Sorting by rank (ascending or descending), year, stage, and running order.
--  - Applying pagination.
-- 
-- Input parameters:
--  @min_points INT - Sets the inclusive points range minimum.
--  @max_points INT - Sets the inclusive points range maximum.
--  @contest_stages TVP - Filters voting data by contest stage int enum values.
--  @exclude_jury BIT - Excludes jury points from voting data.
--  @exclude_televote BIT - Excludes televote points from voting data.
--  @min_year INT - Filters voting data by inclusive minimum contest year when not null. Default is null.
--  @max_year INT - Filters voting data by inclusive maximum contest year when not null. Default is null.
--  @descending BIT - Sorts rankings by descending rank before pagination.
--  @page_index INT - Sets the zero-based pagination page index.
--  @page_size INT - Sets the pagination page size.
--
-- Output parameter:
--  @total_items INT - Is set to the total number of rankings before pagination.
--
-- Returns a page of records with the following columns:
--  - rank INT
--  - contest_year INT
--  - contest_stage INT [enum {0,1,2}]
--  - running_order_position INT
--  - country_code NCHAR(2)
--  - country_name NVARCHAR(200)
--  - finishing_position INT
--  - act_name NVARCHAR(200)
--  - song_title NVARCHAR(200)
--  - points_in_range DECIMAL(9,6)
--  - points_awards_in_range INT
--  - points_awards INT
-- =============================================
*/

BEGIN

    SET NOCOUNT ON;

    WITH

        --------------- Filtering voting data ---------------

        filtered_broadcast AS (SELECT b.id                AS broadcast_id,
                                      b.parent_contest_id AS contest_id
                               FROM dbo.contest e
                                        JOIN dbo.broadcast b ON b.parent_contest_id = e.id
                                        JOIN @contest_stages cs ON cs.value = b.contest_stage
                               WHERE e.completed = 1
                                 AND (@min_year IS NULL OR e.contest_year >= @min_year)
                                 AND (@max_year IS NULL OR e.contest_year <= @max_year)),

        query_datum AS (SELECT bcja.broadcast_id,
                               bcja.competing_country_id,
                               IIF(bcja.points_value BETWEEN @min_points AND @max_points, 1, 0) AS points_award_in_range
                        FROM dbo.broadcast_competitor_jury_award bcja
                                 JOIN filtered_broadcast fb ON fb.broadcast_id = bcja.broadcast_id
                        WHERE @exclude_jury = 0
                        UNION ALL
                        SELECT bcta.broadcast_id,
                               bcta.competing_country_id,
                               IIF(bcta.points_value BETWEEN @min_points AND @max_points, 1, 0) AS points_award_in_range
                        FROM dbo.broadcast_competitor_televote_award bcta
                                 JOIN filtered_broadcast fb ON fb.broadcast_id = bcta.broadcast_id
                        WHERE @exclude_televote = 0),

        ------------- Grouping data by competitor -----------

        grouped_datum AS (SELECT qd.broadcast_id,
                                 qd.competing_country_id,
                                 SUM(qd.points_award_in_range) AS points_awards_in_range,
                                 COUNT(*)                      AS points_awards
                          FROM query_datum qd
                          GROUP BY qd.broadcast_id, qd.competing_country_id),

        -------- Calculating points in range metrics --------

        metric AS (SELECT gd.broadcast_id,
                          gd.competing_country_id,
                          (1.0 * gd.points_awards_in_range) / gd.points_awards AS points_in_range,
                          gd.points_awards_in_range,
                          gd.points_awards
                   FROM grouped_datum gd)

    ------- Ranking by descending points in range -------

    SELECT RANK() OVER (ORDER BY m.points_in_range DESC) AS rank,
           e.contest_year,
           b.contest_stage,
           bc.running_order_position,
           c.country_code,
           c.country_name,
           bc.finishing_position,
           cp.act_name,
           cp.song_title,
           m.points_in_range,
           m.points_awards_in_range,
           m.points_awards
    INTO #ranking
    FROM metric m
             JOIN dbo.country c ON c.id = m.competing_country_id
             JOIN dbo.broadcast b ON b.id = m.broadcast_id
             JOIN dbo.broadcast_competitor bc
                  ON bc.broadcast_id = m.broadcast_id AND bc.competing_country_id = m.competing_country_id
             JOIN dbo.contest e ON e.id = b.parent_contest_id
             JOIN dbo.contest_participant cp
                  ON cp.contest_id = e.id AND cp.participating_country_id = m.competing_country_id;

    -------- Setting @total_items output param ----------

    SET @total_items = (SELECT COUNT(*) FROM #ranking);

    --------------- Sorting and paginating --------------

    SELECT r.rank,
           r.contest_year,
           r.contest_stage,
           r.running_order_position,
           r.country_code,
           r.country_name,
           r.finishing_position,
           r.act_name,
           r.song_title,
           CAST(r.points_in_range AS DECIMAL(9, 6)) AS points_in_range,
           r.points_awards_in_range,
           r.points_awards
    FROM #ranking r
    ORDER BY CASE WHEN @descending = 1 THEN r.rank END DESC,
             CASE WHEN @descending = 0 THEN r.rank END,
             r.contest_year,
             r.contest_stage,
             r.running_order_position
    OFFSET (@page_index * @page_size) ROWS FETCH NEXT (@page_size) ROWS ONLY;

END
GO