using CSharpFunctionalExtensions;
using Eurocentric.Apis.Public.V1.Config;
using Eurocentric.Apis.Public.V1.Dtos.VotingCountryRankings;
using Eurocentric.Apis.Public.V1.Enums;
using Eurocentric.Components.EndpointMapping;
using Eurocentric.Components.Messaging;
using Eurocentric.Domain.Analytics.Rankings.VotingCountries;
using Eurocentric.Domain.Core;
using JetBrains.Annotations;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using SlimMessageBus;
using IResult = Microsoft.AspNetCore.Http.IResult;

namespace Eurocentric.Apis.Public.V1.Features.VotingCountryRankings;

internal static class GetVotingCountryPointsShareRankings
{
    private static async Task<IResult> ExecuteAsync(
        [AsParameters] GetVotingCountryPointsShareRankingsRequest request,
        [FromServices] IRequestResponseBus bus,
        CancellationToken ct = default
    ) => await bus.DispatchAsync(request.ToQuery(), MapToOk, ct);

    private static Query ToQuery(this GetVotingCountryPointsShareRankingsRequest request)
    {
        return new Query
        {
            CompetingCountryCode = request.CompetingCountryCode,
            MinYear = request.MinYear,
            MaxYear = request.MaxYear,
            ContestStage = request.ContestStage?.ToDomainContestStageFilter(),
            VotingMethod = request.VotingMethod?.ToDomainVotingMethodFilter(),
            PageIndex = request.PageIndex,
            PageSize = request.PageSize,
            Descending = request.Descending,
        };
    }

    private static Ok<GetVotingCountryPointsShareRankingsResponse> MapToOk(PointsShareRankings rankings)
    {
        (List<PointsShareRanking> rankingRecords, PointsShareMetadata metadataRecord) = rankings;

        return TypedResults.Ok(
            new GetVotingCountryPointsShareRankingsResponse(
                rankingRecords.Select(ranking => ranking.ToDto()).ToArray(),
                metadataRecord.ToDto()
            )
        );
    }

    internal sealed class EndpointMapper : IEndpointMapper
    {
        public void MapEndpoint(RouteGroupBuilder routeBuilder)
        {
            routeBuilder
                .MapGet("voting-country-rankings/points-share", ExecuteAsync)
                .WithName(V1EndpointNames.VotingCountryRankings.GetVotingCountryPointsShareRankings)
                .AddedInVersion1Point0()
                .WithSummary("Get voting country points share rankings")
                .WithDescription(
                    """
                    Ranks voting countries based on *descending points share*.

                    Returns a page of rankings and a metadata object.

                    Points share is a float between 0 and 1, calculated as the sum total points the voting country gave
                    to a specified competing country across broadcasts, as a fraction of the available points.

                    Rankings are generated by:

                    - Filtering voting data from query parameters.
                    - Grouping data by voting country.
                    - Calculating points share metric.
                    - Ranking by descending points share.
                    - Sorting rankings
                        - by rank (ascending or descending)
                        - then by country code (ascending).
                    - Applying pagination.
                    """
                )
                .WithTags(V1Tags.VotingCountryRankings)
                .Produces<GetVotingCountryPointsShareRankingsResponse>()
                .ProducesProblem(StatusCodes.Status400BadRequest)
                .ProducesProblem(StatusCodes.Status422UnprocessableEntity);
        }
    }

    internal sealed record Query : PointsShareQuery, IQuery<PointsShareRankings>;

    [UsedImplicitly]
    internal sealed class QueryHandler(IVotingCountryRankingsGateway gateway)
        : IQueryHandler<Query, PointsShareRankings>
    {
        public async Task<Result<PointsShareRankings, IDomainError>> OnHandle(Query query, CancellationToken ct) =>
            await gateway.GetPointsShareRankingsAsync(query, ct);
    }
}
