using Eurocentric.Features.PublicApi.V0.Common.Constants;
using Eurocentric.Features.PublicApi.V0.Common.Versioning;
using Eurocentric.Features.PublicApi.V0.CompetingCountryRankings.GetCompetingCountryPointsInRangeRankings;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;

namespace Eurocentric.Features.PublicApi.V0.CompetingCountryRankings;

/// <summary>
///     Extension methods to be invoked when configuring HTTP request pipeline middleware.
/// </summary>
internal static class Middleware
{
    /// <summary>
    ///     Maps the "Competing Country Rankings" tagged endpoints to the endpoint route builder.
    /// </summary>
    /// <param name="builder">The endpoint route builder.</param>
    internal static void MapCompetingCountryRankingsEndpoints(this IEndpointRouteBuilder builder)
    {
        RouteGroupBuilder endpointGroup = builder.MapGroup("rankings/competing-countries")
            .WithTags(EndpointNames.CompetingCountryRankings.Tag)
            .WithDescription("Endpoints that rank competing countries using metrics " +
                             "calculated from the points they received across broadcasts.");

        endpointGroup.MapGet("points-in-range", GetCompetingCountryPointsInRangeRankingsFeature.ExecuteAsync)
            .WithName(EndpointNames.CompetingCountryRankings.GetCompetingCountryPointsInRangeRankings)
            .WithSummary("Get competing country points in range rankings")
            .WithDescription(
                """
                Returns a page of competing country rankings based on descending points in range.

                Points in range is a float between 0 and 1, calculated as the frequency of points awards within a given range
                received by the competing country across broadcasts, relative to the number of points awards it received.

                Rankings are generated by:
                - Filtering voting data.
                - Grouping data by competing country.
                - Calculating points award counts and points in range.
                - Ranking by descending points in range.
                - Sorting by rank (ascending or descending) and country code.
                - Applying pagination.
                """)
            .IntroducedInVersion0Point(2)
            .Produces<GetCompetingCountryPointsInRangeRankingsResponse>();
    }
}
