// <auto-generated />
using System;
using Eurocentric.Infrastructure.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eurocentric.Infrastructure.EfCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250519173822_AddContestAggregateTables")]
    partial class AddContestAggregateTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Eurocentric.Domain.Contests.Contest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("city_name");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("contest_format");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("contest_status");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("contest_year");

                    b.HasKey("Id")
                        .HasName("pk_contest");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasAlternateKey("Year")
                        .HasName("ak_contest_contest_year");

                    b.ToTable("contest", null, t =>
                        {
                            t.HasCheckConstraint("ck_contest_contest_format_enum", "[contest_format] IN (N'Liverpool', N'Stockholm')");

                            t.HasCheckConstraint("ck_contest_contest_status_enum", "[contest_status] IN (N'Initialized', N'InProgress', N'Completed')");

                            t.HasCheckConstraint("ck_contest_contest_year", "[contest_year] BETWEEN 2016 AND 2050");
                        });

                    b.HasDiscriminator<string>("Format");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Eurocentric.Domain.Countries.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .HasColumnName("country_code")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("country_name");

                    b.HasKey("Id")
                        .HasName("pk_country");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasAlternateKey("CountryCode")
                        .HasName("ak_country_country_code");

                    b.ToTable("country", (string)null);
                });

            modelBuilder.Entity("Eurocentric.Domain.Contests.LiverpoolFormatContest", b =>
                {
                    b.HasBaseType("Eurocentric.Domain.Contests.Contest");

                    b.ToTable("contest", null, t =>
                        {
                            t.HasCheckConstraint("ck_contest_contest_format_enum", "[contest_format] IN (N'Liverpool', N'Stockholm')");

                            t.HasCheckConstraint("ck_contest_contest_status_enum", "[contest_status] IN (N'Initialized', N'InProgress', N'Completed')");

                            t.HasCheckConstraint("ck_contest_contest_year", "[contest_year] BETWEEN 2016 AND 2050");
                        });

                    b.HasDiscriminator().HasValue("Liverpool");
                });

            modelBuilder.Entity("Eurocentric.Domain.Contests.StockholmFormatContest", b =>
                {
                    b.HasBaseType("Eurocentric.Domain.Contests.Contest");

                    b.ToTable("contest", null, t =>
                        {
                            t.HasCheckConstraint("ck_contest_contest_format_enum", "[contest_format] IN (N'Liverpool', N'Stockholm')");

                            t.HasCheckConstraint("ck_contest_contest_status_enum", "[contest_status] IN (N'Initialized', N'InProgress', N'Completed')");

                            t.HasCheckConstraint("ck_contest_contest_year", "[contest_year] BETWEEN 2016 AND 2050");
                        });

                    b.HasDiscriminator().HasValue("Stockholm");
                });

            modelBuilder.Entity("Eurocentric.Domain.Contests.Contest", b =>
                {
                    b.OwnsMany("Eurocentric.Domain.Contests.Participant", "Participants", b1 =>
                        {
                            b1.Property<Guid>("ContestId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("contest_id");

                            b1.Property<Guid>("ParticipatingCountryId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("participating_country_id");

                            b1.Property<string>("ActName")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("act_name");

                            b1.Property<int>("Group")
                                .HasColumnType("int")
                                .HasColumnName("participant_group");

                            b1.Property<string>("SongTitle")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("song_title");

                            b1.HasKey("ContestId", "ParticipatingCountryId")
                                .HasName("pk_contest_participant");

                            SqlServerKeyBuilderExtensions.IsClustered(b1.HasKey("ContestId", "ParticipatingCountryId"));

                            b1.ToTable("contest_participant", null, t =>
                                {
                                    t.HasCheckConstraint("ck_contest_participant_participant_group_enum", "[participant_group] IN (0, 1, 2)");

                                    t.HasCheckConstraint("ck_contest_participant_value_nullability", "([participant_group] = 0 AND [act_name] IS NULL AND [song_title] IS NULL) OR ([participant_group] <> 0 AND [act_name] IS NOT NULL AND [song_title] IS NOT NULL)");
                                });

                            b1.WithOwner()
                                .HasForeignKey("ContestId")
                                .HasConstraintName("fk_contest_participant_contest_contest_id");
                        });

                    b.OwnsMany("Eurocentric.Domain.ValueObjects.BroadcastMemo", "BroadcastMemos", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasColumnName("id");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("BroadcastId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("broadcast_id");

                            b1.Property<Guid>("ContestId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("contest_id");

                            b1.Property<string>("ContestStage")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("contest_stage");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("broadcast_status");

                            b1.HasKey("Id")
                                .HasName("pk_contest_broadcast_memo");

                            SqlServerKeyBuilderExtensions.IsClustered(b1.HasKey("Id"));

                            b1.HasIndex("ContestId", "BroadcastId")
                                .IsUnique()
                                .HasDatabaseName("ix_contest_broadcast_memo_contest_id_broadcast_id");

                            b1.HasIndex("ContestId", "ContestStage")
                                .IsUnique()
                                .HasDatabaseName("ix_contest_broadcast_memo_contest_id_contest_stage");

                            b1.ToTable("contest_broadcast_memo", null, t =>
                                {
                                    t.HasCheckConstraint("ck_contest_broadcast_memo_broadcast_status_enum", "[broadcast_status] IN (N'Initialized', N'InProgress', N'Completed')");

                                    t.HasCheckConstraint("ck_contest_broadcast_memo_contest_stage_enum", "[contest_stage] IN (N'SemiFinal1', N'SemiFinal2', N'GrandFinal')");
                                });

                            b1.WithOwner()
                                .HasForeignKey("ContestId")
                                .HasConstraintName("fk_contest_broadcast_memo_contest_contest_id");
                        });

                    b.Navigation("BroadcastMemos");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Eurocentric.Domain.Countries.Country", b =>
                {
                    b.OwnsMany("Eurocentric.Domain.ValueObjects.ContestMemo", "ContestMemos", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasColumnName("id");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("ContestId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("contest_id");

                            b1.Property<Guid>("CountryId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("country_id");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("contest_status");

                            b1.HasKey("Id")
                                .HasName("pk_country_contest_memo");

                            b1.HasIndex("CountryId", "ContestId")
                                .IsUnique()
                                .HasDatabaseName("ix_country_contest_memo_country_id_contest_id");

                            b1.ToTable("country_contest_memo", null, t =>
                                {
                                    t.HasCheckConstraint("ck_country_contest_memo_contest_status_enum", "[contest_status] IN (N'Initialized', N'InProgress', N'Completed')");
                                });

                            b1.WithOwner()
                                .HasForeignKey("CountryId")
                                .HasConstraintName("fk_country_contest_memo_country_country_id");
                        });

                    b.Navigation("ContestMemos");
                });
#pragma warning restore 612, 618
        }
    }
}
