// <auto-generated />
using System;
using System.Collections.Generic;
using Eurocentric.Infrastructure.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eurocentric.Infrastructure.EfCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250515070316_Country_Aggregate")]
    partial class Country_Aggregate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Eurocentric.Domain.Countries.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.ComplexProperty<Dictionary<string, object>>("CountryCode", "Eurocentric.Domain.Countries.Country.CountryCode#CountryCode", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nchar(2)")
                                .HasColumnName("country_code");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Name", "Eurocentric.Domain.Countries.Country.Name#CountryName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("name");
                        });

                    b.HasKey("Id")
                        .HasName("pk_country");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.ToTable("country", (string)null);
                });

            modelBuilder.Entity("Eurocentric.Domain.Countries.Country", b =>
                {
                    b.OwnsMany("Eurocentric.Domain.ValueObjects.ContestMemo", "ContestMemos", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasColumnName("id");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("ContestId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("contest_id");

                            b1.Property<Guid>("CountryId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("country_id");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("status");

                            b1.HasKey("Id")
                                .HasName("pk_country_contest_memo");

                            b1.HasIndex("CountryId", "ContestId")
                                .IsUnique()
                                .HasDatabaseName("ix_country_contest_memo_country_id_contest_id");

                            b1.ToTable("country_contest_memo", null, t =>
                                {
                                    t.HasCheckConstraint("ck_country_contest_memo_status_enum", "[status] IN (N'Initialized', N'InProgress', N'Completed')");
                                });

                            b1.WithOwner()
                                .HasForeignKey("CountryId")
                                .HasConstraintName("fk_country_contest_memo_country_country_id");
                        });

                    b.Navigation("ContestMemos");
                });
#pragma warning restore 612, 618
        }
    }
}
