// <auto-generated />
using System;
using Eurocentric.Infrastructure.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eurocentric.Infrastructure.EfCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Eurocentric.Domain.Countries.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .HasColumnName("country_code")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("country_name");

                    b.HasKey("Id")
                        .HasName("pk_country");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasAlternateKey("CountryCode")
                        .HasName("ak_country_country_code");

                    b.ToTable("country", (string)null);
                });

            modelBuilder.Entity("Eurocentric.Domain.Countries.Country", b =>
                {
                    b.OwnsMany("Eurocentric.Domain.ValueObjects.ContestMemo", "ContestMemos", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasColumnName("id");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("ContestId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("contest_id");

                            b1.Property<Guid>("CountryId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("country_id");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("contest_status");

                            b1.HasKey("Id")
                                .HasName("pk_country_contest_memo");

                            b1.HasIndex("CountryId", "ContestId")
                                .IsUnique()
                                .HasDatabaseName("ix_country_contest_memo_country_id_contest_id");

                            b1.ToTable("country_contest_memo", null, t =>
                                {
                                    t.HasCheckConstraint("ck_country_contest_memo_contest_status_enum", "[contest_status] IN (N'Initialized', N'InProgress', N'Completed')");
                                });

                            b1.WithOwner()
                                .HasForeignKey("CountryId")
                                .HasConstraintName("fk_country_contest_memo_country_country_id");
                        });

                    b.Navigation("ContestMemos");
                });
#pragma warning restore 612, 618
        }
    }
}
