// <auto-generated />
using System;
using Eurocentric.Infrastructure.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eurocentric.Infrastructure.EfCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("euro")
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Eurocentric.Domain.Countries.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .HasColumnName("country_code")
                        .IsFixedLength();

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("country_name");

                    b.HasKey("Id")
                        .HasName("pk_country");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasAlternateKey("CountryCode")
                        .HasName("ak_country_country_code");

                    b.ToTable("country", "euro");
                });

            modelBuilder.Entity("Eurocentric.Domain.Countries.Country", b =>
                {
                    b.OwnsMany("Eurocentric.Domain.ValueObjects.ContestMemo", "ParticipatingContests", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasColumnName("id");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("ContestId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("contest_id");

                            b1.Property<int>("ContestStatus")
                                .HasColumnType("int")
                                .HasColumnName("contest_status");

                            b1.Property<Guid>("CountryId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("country_id");

                            b1.HasKey("Id")
                                .HasName("pk_country_participating_contest");

                            SqlServerKeyBuilderExtensions.IsClustered(b1.HasKey("Id"));

                            b1.HasIndex("CountryId", "ContestId")
                                .IsUnique()
                                .HasDatabaseName("ix_country_participating_contest_country_id_contest_id");

                            b1.ToTable("country_participating_contest", "euro", t =>
                                {
                                    t.HasCheckConstraint("ck_country_participating_contest_contest_status_enum", "[contest_status] IN (0, 1, 2)");
                                });

                            b1.WithOwner()
                                .HasForeignKey("CountryId")
                                .HasConstraintName("fk_country_participating_contest_country_country_id");
                        });

                    b.Navigation("ParticipatingContests");
                });
#pragma warning restore 612, 618
        }
    }
}
