using Eurocentric.Features.PublicApi.V1.Common.Constants;
using Eurocentric.Features.PublicApi.V1.Rankings.VotingCountries.GetVotingCountryPointsAverageRankings;
using Eurocentric.Features.PublicApi.V1.Rankings.VotingCountries.GetVotingCountryPointsShareRankings;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;

namespace Eurocentric.Features.PublicApi.V1.Rankings.VotingCountries;

/// <summary>
///     Extension methods to be invoked when configuring web application middleware.
/// </summary>
internal static class Middleware
{
    /// <summary>
    ///     Adds the endpoints tagged with "Voting Country Rankings".
    /// </summary>
    /// <param name="builder">The endpoint route builder to which the endpoints are to be added.</param>
    internal static void MapVotingCountryRankingsEndpoints(this IEndpointRouteBuilder builder)
    {
        RouteGroupBuilder group = builder.MapGroup("rankings/voting-countries")
            .WithTags(EndpointNames.Tags.VotingCountryRankings)
            .ProducesProblem(StatusCodes.Status400BadRequest);

        group.MapGet("points-average", GetVotingCountryPointsAverageRankingsFeature.ExecuteAsync)
            .WithName(EndpointNames.Routes.VotingCountryRankings.GetVotingCountryPointsAverageRankings)
            .WithSummary("Get voting country points average rankings")
            .WithDescription(
                """
                Returns a page of voting country rankings based on descending points average.

                Points average is a float between 0 and 12, calculated as the average individual points value awarded by the
                voting country to a given competing country across broadcasts.

                Rankings are generated by:
                - Filtering voting data.
                - Grouping data by voting country.
                - Calculating total points, points award count, and points average.
                - Ranking by descending points average.
                - Sorting by rank (ascending or descending) and country code.
                - Applying pagination.
                """)
            .HasApiVersion(1, 0)
            .Produces<GetVotingCountryPointsAverageRankingsResponse>();

        group.MapGet("points-share", GetVotingCountryPointsShareRankingsFeature.ExecuteAsync)
            .WithName(EndpointNames.Routes.VotingCountryRankings.GetVotingCountryPointsShareRankings)
            .WithSummary("Get voting country points share rankings")
            .WithDescription(
                """
                Returns a page of voting country rankings based on descending points share.

                Points share is a float between 0 and 1, calculated as the total points awarded by the voting country to a given
                competing country across broadcasts as a fraction of the maximum available points.

                Rankings are generated by:
                - Filtering voting data.
                - Grouping data by voting country.
                - Calculating total points, available points, and points share.
                - Ranking by descending points share.
                - Sorting by rank (ascending or descending) and country code.
                - Applying pagination.
                """)
            .HasApiVersion(1, 0)
            .Produces<GetVotingCountryPointsShareRankingsResponse>();
    }
}
