/*
    Creates the stored procedure v0.usp_get_competing_country_points_in_range_rankings.
*/

SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

CREATE PROCEDURE v0.usp_get_competing_country_points_in_range_rankings(
    @min_points INT,
    @max_points INT,
    @min_year INT = NULL,
    @max_year INT = NULL,
    @contest_stages dbo.tvp_enum_int_value READONLY,
    @exclude_jury BIT,
    @exclude_televote BIT,
    @voting_country_code NCHAR(2) = NULL,
    @page_index INT,
    @page_size INT,
    @descending BIT,
    @total_rankings INT OUTPUT
)
AS
/*
-- =============================================
-- Procedure:   v0.usp_get_competing_country_points_in_range_rankings
-- Author:      Matt Tantony
-- Create date: 2025-09-18
--
-- Description:
--  Returns a page of competing country rankings based on descending points in range.
--  Points in range is a float between 0 and 1, calculated as the frequency of points awards within a given range
--  received by the competing country across broadcasts, relative to the number of points awards it received.
--
-- Rankings are generated by:
--  - Filtering voting data.
--  - Grouping data by competing country.
--  - Calculating points award counts and points in range.
--  - Ranking by descending points in range.
--  - Sorting by rank (ascending or descending) and country code.
--  - Applying pagination.
--
-- Input parameters:
--  @min_points INT - Sets the inclusive points range minimum.
--  @max_points INT - Sets the inclusive points range maximum.
--  @contest_stages TVP - Filters voting data by contest stage enum integer values.
--  @exclude_jury BIT - Excludes jury points from voting data.
--  @exclude_televote BIT - Excludes televote points from voting data.
--  @min_year INT - Filters voting data by inclusive minimum contest year when not null. Default is null.
--  @max_year INT - Filters voting data by inclusive maximum contest year when not null. Default is null.
--  @voting_country_code NCHAR(2) - Filters voting data by voting country code when not null. Default is null.
--  @descending BIT - Sorts rankings by descending rank before pagination.
--  @page_index INT - Sets the zero-based pagination page index.
--  @page_size INT - Sets the pagination page size.
--
-- Output parameter:
--  @total_rankings INT - Is set to the total number of rankings before pagination.
--
-- Returns a page of records with the following columns:
--  - rank INT
--  - country_code NCHAR(2)
--  - country_name NVARCHAR(200)
--  - points_in_range DECIMAL(9,6)
--  - points_awards_in_range INT
--  - points_awards INT
--  - broadcasts INT
--  - contests INT
--  - voting_countries INT
-- =============================================
*/

BEGIN

    SET NOCOUNT ON;

    WITH
        -- Filtered voting country IDs
        t0 AS (SELECT c.country_id AS voting_country_id
               FROM v0.country c
               WHERE @voting_country_code IS NULL
                  OR c.country_code = @voting_country_code),

        -- Filtered broadcast IDs and contest IDs
        t1 AS (SELECT b.broadcast_id,
                      e.contest_id
               FROM v0.contest e,
                    v0.broadcast b,
                    @contest_stages cs
               WHERE e.queryable = 1
                 AND (@min_year IS NULL OR e.contest_year >= @min_year)
                 AND (@max_year IS NULL OR e.contest_year <= @max_year)
                 AND e.contest_id = b.parent_contest_id
                 AND b.contest_stage = cs.value),

        -- Queryable data
        t2 AS (SELECT ja.competing_country_id,
                      t0.voting_country_id,
                      t1.broadcast_id,
                      t1.contest_id,
                      IIF(ja.points_value BETWEEN @min_points AND @max_points, 1.0, 0.0) AS points_value_in_range
               FROM v0.jury_award ja,
                    t0,
                    t1
               WHERE @exclude_jury = 0
                 AND ja.voting_country_id = t0.voting_country_id
                 AND ja.broadcast_id = t1.broadcast_id
               UNION ALL
               SELECT ta.competing_country_id,
                      t0.voting_country_id,
                      t1.broadcast_id,
                      t1.contest_id,
                      IIF(ta.points_value BETWEEN @min_points AND @max_points, 1.0, 0.0) AS points_value_in_range
               FROM v0.televote_award ta,
                    t0,
                    t1
               WHERE @exclude_televote = 0
                 AND ta.voting_country_id = t0.voting_country_id
                 AND ta.broadcast_id = t1.broadcast_id),

        -- Aggregate
        t3 AS (SELECT t2.competing_country_id,
                      AVG(t2.points_value_in_range)        AS points_in_range,
                      COUNT(*)                             AS points_awards,
                      COUNT(DISTINCT t2.broadcast_id)      AS broadcasts,
                      COUNT(DISTINCT t2.contest_id)        AS contests,
                      COUNT(DISTINCT t2.voting_country_id) AS voting_countries
               FROM t2
               GROUP BY t2.competing_country_id)

-- Ranking
    SELECT RANK() OVER (ORDER BY t3.points_in_range DESC) AS rank,
           c.country_code,
           c.country_name,
           t3.points_in_range,
           t3.points_awards,
           t3.broadcasts,
           t3.contests,
           t3.voting_countries
    INTO #ranking
    FROM t3,
         v0.country c
    WHERE t3.competing_country_id = c.country_id;

-- Total items
    SET @total_rankings = (SELECT COUNT(*) FROM #ranking);

    -- Page
    SELECT r.rank,
           r.country_code,
           r.country_name,
           r.points_in_range,
           r.points_awards,
           r.broadcasts,
           r.contests,
           r.voting_countries
    FROM #ranking r
    ORDER BY CASE WHEN @descending = 1 THEN r.rank END DESC,
             CASE WHEN @descending = 0 THEN r.rank END,
             r.country_code
    OFFSET (@page_index * @page_size) ROWS FETCH NEXT (@page_size) ROWS ONLY;

END
GO
