using CSharpFunctionalExtensions;
using Eurocentric.Apis.Public.V1.Config;
using Eurocentric.Apis.Public.V1.Dtos.Rankings.VotingCountries;
using Eurocentric.Apis.Public.V1.Enums;
using Eurocentric.Components.EndpointMapping;
using Eurocentric.Components.Messaging;
using Eurocentric.Domain.Analytics.Rankings.VotingCountries;
using Eurocentric.Domain.Core;
using JetBrains.Annotations;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using SlimMessageBus;
using IResult = Microsoft.AspNetCore.Http.IResult;

namespace Eurocentric.Apis.Public.V1.Features.Rankings.VotingCountries;

internal static class GetVotingCountryPointsAverageRankings
{
    private static async Task<IResult> ExecuteAsync(
        [AsParameters] GetVotingCountryPointsAverageRankingsRequest request,
        [FromServices] IRequestResponseBus bus,
        CancellationToken ct = default
    ) => await bus.DispatchAsync(request.ToQuery(), MapToOk, ct);

    private static Query ToQuery(this GetVotingCountryPointsAverageRankingsRequest request)
    {
        return new Query
        {
            CompetingCountryCode = request.CompetingCountryCode,
            MinYear = request.MinYear,
            MaxYear = request.MaxYear,
            ContestStage = request.ContestStage?.ToDomainContestStageFilter(),
            VotingMethod = request.VotingMethod?.ToDomainVotingMethodFilter(),
            PageIndex = request.PageIndex,
            PageSize = request.PageSize,
            Descending = request.Descending,
        };
    }

    private static Ok<GetVotingCountryPointsAverageRankingsResponse> MapToOk(PointsAverageRankings rankings)
    {
        (List<PointsAverageRanking> rankingRecords, PointsAverageMetadata metadataRecord) = rankings;

        return TypedResults.Ok(
            new GetVotingCountryPointsAverageRankingsResponse(
                rankingRecords.Select(ranking => ranking.ToDto()).ToArray(),
                metadataRecord.ToDto()
            )
        );
    }

    internal sealed class EndpointMapper : IEndpointMapper
    {
        public void MapEndpoint(RouteGroupBuilder routeBuilder)
        {
            routeBuilder
                .MapGet("voting-country-rankings/points-average", ExecuteAsync)
                .WithName(V1EndpointNames.VotingCountryRankings.GetVotingCountryPointsAverageRankings)
                .AddedInVersion1Point0()
                .WithSummary("Get voting country points average rankings")
                .WithDescription(
                    """
                    Returns a page of voting country rankings based on descending points average.

                    Points average is a float between 0 and 12, calculated as the average individual points value
                    awarded by the voting country to a given competing country across broadcasts.

                    Rankings are generated by:
                    - Filtering voting data.
                    - Grouping data by voting country.
                    - Calculating total points, points award count, and points average.
                    - Ranking by descending points average.
                    - Sorting by rank (ascending or descending) and country code.
                    - Applying pagination.
                    """
                )
                .WithTags(V1Tags.VotingCountryRankings)
                .Produces<GetVotingCountryPointsAverageRankingsResponse>()
                .ProducesProblem(StatusCodes.Status400BadRequest)
                .ProducesProblem(StatusCodes.Status422UnprocessableEntity);
        }
    }

    internal sealed record Query : PointsAverageQuery, IQuery<PointsAverageRankings>;

    [UsedImplicitly]
    internal sealed class QueryHandler(IVotingCountryRankingsGateway gateway)
        : IQueryHandler<Query, PointsAverageRankings>
    {
        public async Task<Result<PointsAverageRankings, IDomainError>> OnHandle(Query query, CancellationToken ct) =>
            await gateway.GetPointsAverageRankingsAsync(query, ct);
    }
}
