using Eurocentric.Apis.Public.V1.Config;
using Eurocentric.Apis.Public.V1.Enums;
using Eurocentric.Components.OpenApi;

namespace Eurocentric.Apis.Public.V1.Dtos.CompetitorRankings;

/// <summary>
///     Metadata describing an executed competitor points in range rankings query.
/// </summary>
public sealed record CompetitorPointsInRangeMetadata : IDtoSchemaExampleProvider<CompetitorPointsInRangeMetadata>
{
    /// <summary>
    ///     The required inclusive minimum points value.
    /// </summary>
    public int MinPoints { get; init; }

    /// <summary>
    ///     The required inclusive maximum points value.
    /// </summary>
    public int MaxPoints { get; init; }

    /// <summary>
    ///     The optional inclusive minimum contest year filter value.
    /// </summary>
    public int? MinYear { get; init; }

    /// <summary>
    ///     The optional inclusive maximum contest year filter value.
    /// </summary>
    public int? MaxYear { get; init; }

    /// <summary>
    ///     The optional contest stage filter value.
    /// </summary>
    public ContestStageFilter? ContestStage { get; init; }

    /// <summary>
    ///     The optional competing country code filter value.
    /// </summary>
    public string? CompetingCountryCode { get; init; }

    /// <summary>
    ///     The optional voting method filter value.
    /// </summary>
    public VotingMethodFilter? VotingMethod { get; init; }

    /// <summary>
    ///     The zero-based pagination page index.
    /// </summary>
    public int PageIndex { get; init; }

    /// <summary>
    ///     The pagination page size.
    /// </summary>
    public int PageSize { get; init; }

    /// <summary>
    ///     Specifies descending rank (<see langword="true" />) or ascending rank (<see langword="false" />) initial sort
    ///     before pagination.
    /// </summary>
    public bool Descending { get; init; }

    /// <summary>
    ///     The number of rankings generated by the query.
    /// </summary>
    public int TotalItems { get; init; }

    /// <summary>
    ///     The number of rankings pages generated by the query.
    /// </summary>
    public int TotalPages { get; init; }

    public static CompetitorPointsInRangeMetadata CreateExample() =>
        new()
        {
            MinPoints = 1,
            MaxPoints = 12,
            PageIndex = V1PaginationDefaults.PageIndex,
            PageSize = V1PaginationDefaults.PageSize,
            Descending = V1PaginationDefaults.Descending,
            TotalItems = 500,
            TotalPages = 50,
        };
}
