// <auto-generated />
using System;
using Eurocentric.Components.DataAccess.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eurocentric.Components.DataAccess.EfCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251211073644_Add_v0_aggregate_tables")]
    partial class Add_v0_aggregate_tables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Eurocentric.Domain.Aggregates.V0.Broadcast", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("broadcast_id");

                    b.Property<DateOnly>("BroadcastDate")
                        .HasColumnType("date")
                        .HasColumnName("broadcast_date");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit")
                        .HasColumnName("completed");

                    b.Property<string>("ContestStage")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("contest_stage");

                    b.Property<Guid>("ParentContestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("parent_contest_id");

                    b.Property<string>("VotingRules")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("voting_rules");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("BroadcastDate")
                        .IsUnique();

                    b.HasIndex("ParentContestId", "ContestStage")
                        .IsUnique();

                    b.ToTable("broadcast", "v0", t =>
                        {
                            t.HasCheckConstraint("CK_broadcast_broadcast_date", "[broadcast_date] BETWEEN '2016-01-01' AND '2050-12-31'");

                            t.HasCheckConstraint("CK_broadcast_contest_stage_Enum", "[contest_stage] IN (N'GrandFinal', N'SemiFinal1', N'SemiFinal2')");

                            t.HasCheckConstraint("CK_broadcast_voting_rules_Enum", "[voting_rules] IN (N'TelevoteAndJury', N'TelevoteOnly')");
                        });
                });

            modelBuilder.Entity("Eurocentric.Domain.Aggregates.V0.Contest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("contest_id");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("city_name");

                    b.Property<int>("ContestYear")
                        .HasColumnType("int")
                        .HasColumnName("contest_year");

                    b.Property<string>("GrandFinalVotingRules")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("grand_final_voting_rules");

                    b.Property<bool>("Queryable")
                        .HasColumnType("bit")
                        .HasColumnName("queryable");

                    b.Property<string>("SemiFinalVotingRules")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("semi_final_voting_rules");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("ContestYear")
                        .IsUnique();

                    b.ToTable("contest", "v0", t =>
                        {
                            t.HasCheckConstraint("CK_contest_contest_year", "[contest_year] BETWEEN 2016 and 2050");

                            t.HasCheckConstraint("CK_contest_grand_final_voting_rules_Enum", "[grand_final_voting_rules] IN (N'TelevoteAndJury', N'TelevoteOnly')");

                            t.HasCheckConstraint("CK_contest_semi_final_voting_rules_Enum", "[semi_final_voting_rules] IN (N'TelevoteAndJury', N'TelevoteOnly')");
                        });
                });

            modelBuilder.Entity("Eurocentric.Domain.Aggregates.V0.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("country_id");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("country_code");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("country_name");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("CountryCode")
                        .IsUnique();

                    b.ToTable("country", "v0");
                });

            modelBuilder.Entity("Eurocentric.Domain.Aggregates.V0.Broadcast", b =>
                {
                    b.OwnsMany("Eurocentric.Domain.Aggregates.V0.Competitor", "Competitors", b1 =>
                        {
                            b1.Property<Guid>("BroadcastId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("broadcast_id");

                            b1.Property<Guid>("CompetingCountryId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("competing_country_id");

                            b1.Property<int>("FinishingPosition")
                                .HasColumnType("int")
                                .HasColumnName("finishing_position");

                            b1.Property<int>("RunningOrderSpot")
                                .HasColumnType("int")
                                .HasColumnName("running_order_spot");

                            b1.HasKey("BroadcastId", "CompetingCountryId");

                            SqlServerKeyBuilderExtensions.IsClustered(b1.HasKey("BroadcastId", "CompetingCountryId"));

                            b1.HasIndex("BroadcastId", "RunningOrderSpot")
                                .IsUnique();

                            b1.ToTable("broadcast_competitor", "v0", t =>
                                {
                                    t.HasCheckConstraint("CK_broadcast_competitor_finishing_position", "[finishing_position] >= 1");

                                    t.HasCheckConstraint("CK_broadcast_competitor_running_order_spot", "[running_order_spot] >= 1");
                                });

                            b1.WithOwner()
                                .HasForeignKey("BroadcastId");

                            b1.OwnsMany("Eurocentric.Domain.Aggregates.V0.JuryAward", "JuryAwards", b2 =>
                                {
                                    b2.Property<int>("RowId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int")
                                        .HasColumnName("row_id");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("RowId"));

                                    b2.Property<Guid>("BroadcastId")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("broadcast_id");

                                    b2.Property<Guid>("CompetingCountryId")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("competing_country_id");

                                    b2.Property<int>("PointsValue")
                                        .HasColumnType("int")
                                        .HasColumnName("points_value");

                                    b2.Property<Guid>("VotingCountryId")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("voting_country_id");

                                    b2.HasKey("RowId");

                                    SqlServerKeyBuilderExtensions.IsClustered(b2.HasKey("RowId"));

                                    b2.HasIndex("BroadcastId");

                                    b2.HasIndex("CompetingCountryId");

                                    b2.HasIndex("VotingCountryId");

                                    b2.HasIndex("BroadcastId", "CompetingCountryId", "VotingCountryId")
                                        .IsUnique();

                                    b2.ToTable("broadcast_competitor_jury_award", "v0", t =>
                                        {
                                            t.HasCheckConstraint("CK_broadcast_competitor_jury_award_country_ids", "[competing_country_id] <> [voting_country_id]");

                                            t.HasCheckConstraint("CK_broadcast_competitor_jury_award_points_value", "[points_value] >= 0");
                                        });

                                    b2.WithOwner()
                                        .HasForeignKey("BroadcastId", "CompetingCountryId");
                                });

                            b1.OwnsMany("Eurocentric.Domain.Aggregates.V0.TelevoteAward", "TelevoteAwards", b2 =>
                                {
                                    b2.Property<int>("RowId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int")
                                        .HasColumnName("row_id");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("RowId"));

                                    b2.Property<Guid>("BroadcastId")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("broadcast_id");

                                    b2.Property<Guid>("CompetingCountryId")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("competing_country_id");

                                    b2.Property<int>("PointsValue")
                                        .HasColumnType("int")
                                        .HasColumnName("points_value");

                                    b2.Property<Guid>("VotingCountryId")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("voting_country_id");

                                    b2.HasKey("RowId");

                                    SqlServerKeyBuilderExtensions.IsClustered(b2.HasKey("RowId"));

                                    b2.HasIndex("BroadcastId");

                                    b2.HasIndex("CompetingCountryId");

                                    b2.HasIndex("VotingCountryId");

                                    b2.HasIndex("BroadcastId", "CompetingCountryId", "VotingCountryId")
                                        .IsUnique();

                                    b2.ToTable("broadcast_competitor_televote_award", "v0", t =>
                                        {
                                            t.HasCheckConstraint("CK_broadcast_competitor_televote_award_country_ids", "[competing_country_id] <> [voting_country_id]");

                                            t.HasCheckConstraint("CK_broadcast_competitor_televote_award_points_value", "[points_value] >= 0");
                                        });

                                    b2.WithOwner()
                                        .HasForeignKey("BroadcastId", "CompetingCountryId");
                                });

                            b1.Navigation("JuryAwards");

                            b1.Navigation("TelevoteAwards");
                        });

                    b.OwnsMany("Eurocentric.Domain.Aggregates.V0.Jury", "Juries", b1 =>
                        {
                            b1.Property<Guid>("BroadcastId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("broadcast_id");

                            b1.Property<Guid>("VotingCountryId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("voting_country_id");

                            b1.Property<bool>("PointsAwarded")
                                .HasColumnType("bit")
                                .HasColumnName("points_awarded");

                            b1.HasKey("BroadcastId", "VotingCountryId");

                            SqlServerKeyBuilderExtensions.IsClustered(b1.HasKey("BroadcastId", "VotingCountryId"));

                            b1.ToTable("broadcast_jury", "v0");

                            b1.WithOwner()
                                .HasForeignKey("BroadcastId");
                        });

                    b.OwnsMany("Eurocentric.Domain.Aggregates.V0.Televote", "Televotes", b1 =>
                        {
                            b1.Property<Guid>("BroadcastId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("broadcast_id");

                            b1.Property<Guid>("VotingCountryId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("voting_country_id");

                            b1.Property<bool>("PointsAwarded")
                                .HasColumnType("bit")
                                .HasColumnName("points_awarded");

                            b1.HasKey("BroadcastId", "VotingCountryId");

                            SqlServerKeyBuilderExtensions.IsClustered(b1.HasKey("BroadcastId", "VotingCountryId"));

                            b1.ToTable("broadcast_televote", "v0");

                            b1.WithOwner()
                                .HasForeignKey("BroadcastId");
                        });

                    b.Navigation("Competitors");

                    b.Navigation("Juries");

                    b.Navigation("Televotes");
                });

            modelBuilder.Entity("Eurocentric.Domain.Aggregates.V0.Contest", b =>
                {
                    b.OwnsMany("Eurocentric.Domain.Aggregates.V0.ChildBroadcast", "ChildBroadcasts", b1 =>
                        {
                            b1.Property<Guid>("ContestId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("contest_id");

                            b1.Property<Guid>("ChildBroadcastId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("child_broadcast_id");

                            b1.Property<bool>("Completed")
                                .HasColumnType("bit")
                                .HasColumnName("completed");

                            b1.Property<string>("ContestStage")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("contest_stage");

                            b1.HasKey("ContestId", "ChildBroadcastId");

                            SqlServerKeyBuilderExtensions.IsClustered(b1.HasKey("ContestId", "ChildBroadcastId"));

                            b1.HasIndex("ContestId", "ContestStage")
                                .IsUnique();

                            b1.ToTable("contest_child_broadcast", "v0", t =>
                                {
                                    t.HasCheckConstraint("CK_contest_child_broadcast_contest_stage_Enum", "[contest_stage] IN (N'GrandFinal', N'SemiFinal1', N'SemiFinal2')");
                                });

                            b1.WithOwner()
                                .HasForeignKey("ContestId");
                        });

                    b.OwnsOne("Eurocentric.Domain.Aggregates.V0.GlobalTelevote", "GlobalTelevote", b1 =>
                        {
                            b1.Property<Guid>("ContestId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("VotingCountryId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("global_televote_voting_country_id");

                            b1.HasKey("ContestId");

                            b1.ToTable("contest", "v0");

                            b1.WithOwner()
                                .HasForeignKey("ContestId");
                        });

                    b.OwnsMany("Eurocentric.Domain.Aggregates.V0.Participant", "Participants", b1 =>
                        {
                            b1.Property<Guid>("ContestId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("contest_id");

                            b1.Property<Guid>("ParticipatingCountryId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("participating_country_id");

                            b1.Property<string>("ActName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("act_name");

                            b1.Property<string>("SemiFinalDraw")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("semi_final_draw");

                            b1.Property<string>("SongTitle")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("song_title");

                            b1.HasKey("ContestId", "ParticipatingCountryId");

                            SqlServerKeyBuilderExtensions.IsClustered(b1.HasKey("ContestId", "ParticipatingCountryId"));

                            b1.ToTable("contest_participant", "v0", t =>
                                {
                                    t.HasCheckConstraint("CK_contest_participant_semi_final_draw_Enum", "[semi_final_draw] IN (N'SemiFinal1', N'SemiFinal2')");
                                });

                            b1.WithOwner()
                                .HasForeignKey("ContestId");
                        });

                    b.Navigation("ChildBroadcasts");

                    b.Navigation("GlobalTelevote");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Eurocentric.Domain.Aggregates.V0.Country", b =>
                {
                    b.OwnsMany("Eurocentric.Domain.Aggregates.V0.ContestRole", "ContestRoles", b1 =>
                        {
                            b1.Property<int>("RowId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasColumnName("row_id");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("RowId"));

                            b1.Property<Guid>("ContestId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("contest_id");

                            b1.Property<string>("ContestRoleType")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("contest_role_type");

                            b1.Property<Guid>("CountryId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("country_id");

                            b1.HasKey("RowId");

                            SqlServerKeyBuilderExtensions.IsClustered(b1.HasKey("RowId"));

                            b1.HasIndex("CountryId", "ContestId")
                                .IsUnique();

                            b1.ToTable("country_contest_role", "v0", t =>
                                {
                                    t.HasCheckConstraint("CK_country_contest_role_contest_role_type_Enum", "[contest_role_type] IN (N'Participant', N'GlobalTelevote')");
                                });

                            b1.WithOwner()
                                .HasForeignKey("CountryId");
                        });

                    b.Navigation("ContestRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
