// <auto-generated />
using System;
using Eurocentric.Components.DataAccess.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eurocentric.Components.DataAccess.EfCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260313162202_Create_v0_broadcast_aggregate_tables")]
    partial class Create_v0_broadcast_aggregate_tables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Eurocentric.Domain.Aggregates.V0.Broadcasts.Broadcast", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("broadcast_id");

                    b.Property<DateOnly>("BroadcastDate")
                        .HasColumnType("date")
                        .HasColumnName("broadcast_date");

                    b.Property<string>("BroadcastFormat")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("broadcast_format");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit")
                        .HasColumnName("completed");

                    b.Property<string>("ContestStage")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("contest_stage");

                    b.Property<Guid>("ParentContestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("parent_contest_id");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasAlternateKey("BroadcastDate");

                    b.HasAlternateKey("ParentContestId", "ContestStage");

                    b.ToTable("broadcast", "v0", t =>
                        {
                            t.HasCheckConstraint("CK_broadcast_broadcast_date", "broadcast_date BETWEEN '2016-01-01' AND '2030-12-31'");

                            t.HasCheckConstraint("CK_broadcast_broadcast_format_Enum", "[broadcast_format] IN ('JuryAndTelevote', 'TelevoteOnly')");

                            t.HasCheckConstraint("CK_broadcast_contest_stage_Enum", "[contest_stage] IN ('SemiFinal1', 'SemiFinal2', 'GrandFinal')");
                        });
                });

            modelBuilder.Entity("Eurocentric.Domain.Aggregates.V0.Contests.Contest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("contest_id");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("city_name");

                    b.Property<int>("ContestYear")
                        .HasColumnType("int")
                        .HasColumnName("contest_year");

                    b.Property<string>("GrandFinalBroadcastFormat")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("grand_final_broadcast_format");

                    b.Property<bool>("Queryable")
                        .HasColumnType("bit")
                        .HasColumnName("queryable");

                    b.Property<string>("SemiFinalBroadcastFormat")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("semi_final_broadcast_format");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasAlternateKey("ContestYear");

                    b.ToTable("contest", "v0", t =>
                        {
                            t.HasCheckConstraint("CK_contest_contest_year", "contest_year BETWEEN 2016 AND 2030");

                            t.HasCheckConstraint("CK_contest_grand_final_broadcast_format_Enum", "[grand_final_broadcast_format] IN ('JuryAndTelevote', 'TelevoteOnly')");

                            t.HasCheckConstraint("CK_contest_semi_final_broadcast_format_Enum", "[semi_final_broadcast_format] IN ('JuryAndTelevote', 'TelevoteOnly')");
                        });
                });

            modelBuilder.Entity("Eurocentric.Domain.Aggregates.V0.Countries.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("country_id");

                    b.PrimitiveCollection<string>("ActiveContestIds")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("active_contest_ids");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .HasColumnName("country_code")
                        .IsFixedLength();

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("country_name");

                    b.Property<string>("CountryType")
                        .IsRequired()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("country_type");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasAlternateKey("CountryCode");

                    b.ToTable("country", "v0", t =>
                        {
                            t.HasCheckConstraint("CK_country_country_type_Enum", "[country_type] IN ('Real', 'Pseudo')");
                        });
                });

            modelBuilder.Entity("Eurocentric.Domain.Aggregates.V0.Broadcasts.Broadcast", b =>
                {
                    b.OwnsMany("Eurocentric.Domain.Aggregates.V0.Broadcasts.Competitor", "Competitors", b1 =>
                        {
                            b1.Property<Guid>("BroadcastId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("broadcast_id");

                            b1.Property<Guid>("CompetingCountryId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("competing_country_id");

                            b1.Property<string>("BroadcastHalf")
                                .IsRequired()
                                .HasMaxLength(6)
                                .IsUnicode(false)
                                .HasColumnType("varchar(6)")
                                .HasColumnName("broadcast_half");

                            b1.Property<int>("FinishingSpot")
                                .HasColumnType("int")
                                .HasColumnName("finishing_spot");

                            b1.Property<int>("PerformingSpot")
                                .HasColumnType("int")
                                .HasColumnName("performing_spot");

                            b1.HasKey("BroadcastId", "CompetingCountryId");

                            SqlServerKeyBuilderExtensions.IsClustered(b1.HasKey("BroadcastId", "CompetingCountryId"));

                            b1.ToTable("broadcast_competitor", "v0", t =>
                                {
                                    t.HasCheckConstraint("CK_broadcast_competitor_broadcast_half_Enum", "[broadcast_half] IN ('First', 'Second')");

                                    t.HasCheckConstraint("CK_broadcast_competitor_finishing_spot", "finishing_spot >= 1");

                                    t.HasCheckConstraint("CK_broadcast_competitor_performing_spot", "performing_spot >= 1");
                                });

                            b1.WithOwner()
                                .HasForeignKey("BroadcastId");

                            b1.OwnsMany("Eurocentric.Domain.Aggregates.V0.Broadcasts.PointsAward", "PointsAwards", b2 =>
                                {
                                    b2.Property<int>("RowId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int")
                                        .HasColumnName("row_id");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("RowId"));

                                    b2.Property<Guid>("BroadcastId")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("broadcast_id");

                                    b2.Property<Guid>("CompetingCountryId")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("competing_country_id");

                                    b2.Property<int>("PointsValue")
                                        .HasColumnType("int")
                                        .HasColumnName("points_value");

                                    b2.Property<Guid>("VotingCountryId")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("voting_country_id");

                                    b2.Property<string>("VotingMethod")
                                        .IsRequired()
                                        .HasMaxLength(8)
                                        .IsUnicode(false)
                                        .HasColumnType("varchar(8)")
                                        .HasColumnName("voting_method");

                                    b2.HasKey("RowId");

                                    SqlServerKeyBuilderExtensions.IsClustered(b2.HasKey("RowId"));

                                    b2.HasIndex("CompetingCountryId");

                                    b2.HasIndex("VotingCountryId");

                                    b2.HasIndex("BroadcastId", "CompetingCountryId", "VotingCountryId", "VotingMethod")
                                        .IsUnique();

                                    b2.ToTable("broadcast_competitor_points_award", "v0", t =>
                                        {
                                            t.HasCheckConstraint("CK_broadcast_competitor_points_award_country_ids", "competing_country_id <> voting_country_id");

                                            t.HasCheckConstraint("CK_broadcast_competitor_points_award_points_value", "points_value BETWEEN 0 AND 12");

                                            t.HasCheckConstraint("CK_broadcast_competitor_points_award_voting_method_Enum", "[voting_method] IN ('Jury', 'Televote')");
                                        });

                                    b2.WithOwner()
                                        .HasForeignKey("BroadcastId", "CompetingCountryId");
                                });

                            b1.Navigation("PointsAwards");
                        });

                    b.OwnsMany("Eurocentric.Domain.Aggregates.V0.Broadcasts.Jury", "Juries", b1 =>
                        {
                            b1.Property<Guid>("BroadcastId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("broadcast_id");

                            b1.Property<Guid>("VotingCountryId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("voting_country_id");

                            b1.Property<bool>("PointsAwarded")
                                .HasColumnType("bit")
                                .HasColumnName("points_awarded");

                            b1.HasKey("BroadcastId", "VotingCountryId");

                            SqlServerKeyBuilderExtensions.IsClustered(b1.HasKey("BroadcastId", "VotingCountryId"));

                            b1.ToTable("broadcast_jury", "v0");

                            b1.WithOwner()
                                .HasForeignKey("BroadcastId");
                        });

                    b.OwnsMany("Eurocentric.Domain.Aggregates.V0.Broadcasts.Televote", "Televotes", b1 =>
                        {
                            b1.Property<Guid>("BroadcastId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("broadcast_id");

                            b1.Property<Guid>("VotingCountryId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("voting_country_id");

                            b1.Property<bool>("PointsAwarded")
                                .HasColumnType("bit")
                                .HasColumnName("points_awarded");

                            b1.HasKey("BroadcastId", "VotingCountryId");

                            SqlServerKeyBuilderExtensions.IsClustered(b1.HasKey("BroadcastId", "VotingCountryId"));

                            b1.ToTable("broadcast_televote", "v0");

                            b1.WithOwner()
                                .HasForeignKey("BroadcastId");
                        });

                    b.Navigation("Competitors");

                    b.Navigation("Juries");

                    b.Navigation("Televotes");
                });

            modelBuilder.Entity("Eurocentric.Domain.Aggregates.V0.Contests.Contest", b =>
                {
                    b.OwnsMany("Eurocentric.Domain.Aggregates.V0.Contests.ChildBroadcast", "ChildBroadcasts", b1 =>
                        {
                            b1.Property<Guid>("ContestId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("contest_id");

                            b1.Property<Guid>("ChildBroadcastId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("child_broadcast_id");

                            b1.Property<bool>("Completed")
                                .HasColumnType("bit")
                                .HasColumnName("completed");

                            b1.Property<string>("ContestStage")
                                .IsRequired()
                                .HasMaxLength(10)
                                .IsUnicode(false)
                                .HasColumnType("varchar(10)")
                                .HasColumnName("contest_stage");

                            b1.HasKey("ContestId", "ChildBroadcastId");

                            SqlServerKeyBuilderExtensions.IsClustered(b1.HasKey("ContestId", "ChildBroadcastId"));

                            b1.HasIndex("ContestId", "ContestStage")
                                .IsUnique();

                            b1.ToTable("contest_child_broadcast", "v0", t =>
                                {
                                    t.HasCheckConstraint("CK_contest_child_broadcast_contest_stage_Enum", "[contest_stage] IN ('SemiFinal1', 'SemiFinal2', 'GrandFinal')");
                                });

                            b1.WithOwner()
                                .HasForeignKey("ContestId");
                        });

                    b.OwnsOne("Eurocentric.Domain.Aggregates.V0.Contests.GlobalTelevote", "GlobalTelevote", b1 =>
                        {
                            b1.Property<Guid>("ContestId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("VotingCountryId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("global_televote_voting_country_id");

                            b1.HasKey("ContestId");

                            b1.ToTable("contest", "v0");

                            b1.WithOwner()
                                .HasForeignKey("ContestId");
                        });

                    b.OwnsMany("Eurocentric.Domain.Aggregates.V0.Contests.Participant", "Participants", b1 =>
                        {
                            b1.Property<Guid>("ContestId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("contest_id");

                            b1.Property<Guid>("ParticipatingCountryId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("participating_country_id");

                            b1.Property<string>("ActName")
                                .IsRequired()
                                .HasMaxLength(150)
                                .IsUnicode(true)
                                .HasColumnType("nvarchar(150)")
                                .HasColumnName("act_name");

                            b1.Property<string>("SemiFinalDraw")
                                .IsRequired()
                                .HasMaxLength(10)
                                .IsUnicode(false)
                                .HasColumnType("varchar(10)")
                                .HasColumnName("semi_final_draw");

                            b1.Property<string>("SongTitle")
                                .IsRequired()
                                .HasMaxLength(150)
                                .IsUnicode(true)
                                .HasColumnType("nvarchar(150)")
                                .HasColumnName("song_title");

                            b1.HasKey("ContestId", "ParticipatingCountryId");

                            SqlServerKeyBuilderExtensions.IsClustered(b1.HasKey("ContestId", "ParticipatingCountryId"));

                            b1.ToTable("contest_participant", "v0", t =>
                                {
                                    t.HasCheckConstraint("CK_contest_participant_semi_final_draw_Enum", "[semi_final_draw] IN ('SemiFinal1', 'SemiFinal2')");
                                });

                            b1.WithOwner()
                                .HasForeignKey("ContestId");
                        });

                    b.Navigation("ChildBroadcasts");

                    b.Navigation("GlobalTelevote");

                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
