// <auto-generated />
using System;
using Eurocentric.Components.DataAccess.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eurocentric.Components.DataAccess.EfCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260204062914_Create_placeholder_contest_aggregate_tables")]
    partial class Create_placeholder_contest_aggregate_tables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Eurocentric.Domain.Placeholders.Aggregates.Contest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("contest_id");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("city_name");

                    b.Property<int>("ContestYear")
                        .HasColumnType("int")
                        .HasColumnName("contest_year");

                    b.Property<string>("GrandFinalVotingFormat")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("grand_final_voting_format");

                    b.Property<bool>("Queryable")
                        .HasColumnType("bit")
                        .HasColumnName("queryable");

                    b.Property<string>("SemiFinalVotingFormat")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("semi_final_voting_format");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasAlternateKey("ContestYear");

                    b.ToTable("contest", "placeholder", t =>
                        {
                            t.HasCheckConstraint("CK_contest_contest_year", "[contest_year] BETWEEN 2016 AND 2050");

                            t.HasCheckConstraint("CK_contest_grand_final_voting_format_Enum", "[grand_final_voting_format] IN ('TelevoteAndJury', 'TelevoteOnly')");

                            t.HasCheckConstraint("CK_contest_semi_final_voting_format_Enum", "[semi_final_voting_format] IN ('TelevoteAndJury', 'TelevoteOnly')");
                        });
                });

            modelBuilder.Entity("Eurocentric.Domain.Placeholders.Aggregates.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("country_id");

                    b.PrimitiveCollection<string>("ContestIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contest_ids");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .HasColumnName("country_code")
                        .IsFixedLength();

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("country_name");

                    b.Property<string>("CountryType")
                        .IsRequired()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("country_type");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasAlternateKey("CountryCode");

                    b.ToTable("country", "placeholder", t =>
                        {
                            t.HasCheckConstraint("CK_country_country_type_Enum", "[country_type] IN ('Real', 'Pseudo')");
                        });
                });

            modelBuilder.Entity("Eurocentric.Domain.Placeholders.Aggregates.Contest", b =>
                {
                    b.OwnsMany("Eurocentric.Domain.Placeholders.Aggregates.BroadcastMemo", "BroadcastMemos", b1 =>
                        {
                            b1.Property<int>("RowId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasColumnName("row_id");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("RowId"));

                            b1.Property<Guid>("BroadcastId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("broadcast_id");

                            b1.Property<bool>("Completed")
                                .HasColumnType("bit")
                                .HasColumnName("completed");

                            b1.Property<Guid>("ContestId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("contest_id");

                            b1.Property<string>("ContestStage")
                                .IsRequired()
                                .HasMaxLength(10)
                                .IsUnicode(false)
                                .HasColumnType("varchar(10)")
                                .HasColumnName("contest_stage");

                            b1.HasKey("RowId");

                            SqlServerKeyBuilderExtensions.IsClustered(b1.HasKey("RowId"));

                            b1.HasIndex("ContestId", "BroadcastId")
                                .IsUnique();

                            b1.ToTable("contest_broadcast_memo", "placeholder", t =>
                                {
                                    t.HasCheckConstraint("CK_contest_broadcast_memo_contest_stage_Enum", "[contest_stage] IN ('SemiFinal1', 'SemiFinal2', 'GrandFinal')");
                                });

                            b1.WithOwner()
                                .HasForeignKey("ContestId");
                        });

                    b.OwnsOne("Eurocentric.Domain.Placeholders.Aggregates.GlobalTelevote", "GlobalTelevote", b1 =>
                        {
                            b1.Property<Guid>("ContestId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("VotingCountryId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("global_televote_voting_country_id");

                            b1.HasKey("ContestId");

                            b1.ToTable("contest", "placeholder");

                            b1.WithOwner()
                                .HasForeignKey("ContestId");
                        });

                    b.OwnsMany("Eurocentric.Domain.Placeholders.Aggregates.Participant", "Participants", b1 =>
                        {
                            b1.Property<Guid>("ContestId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("contest_id");

                            b1.Property<Guid>("ParticipatingCountryId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("participating_country_id");

                            b1.Property<string>("ActName")
                                .IsRequired()
                                .HasMaxLength(150)
                                .IsUnicode(true)
                                .HasColumnType("nvarchar(150)")
                                .HasColumnName("act_name");

                            b1.Property<string>("SemiFinalDraw")
                                .IsRequired()
                                .HasMaxLength(10)
                                .IsUnicode(false)
                                .HasColumnType("varchar(10)")
                                .HasColumnName("semi_final_draw");

                            b1.Property<string>("SongTitle")
                                .IsRequired()
                                .HasMaxLength(150)
                                .IsUnicode(true)
                                .HasColumnType("nvarchar(150)")
                                .HasColumnName("song_title");

                            b1.HasKey("ContestId", "ParticipatingCountryId");

                            SqlServerKeyBuilderExtensions.IsClustered(b1.HasKey("ContestId", "ParticipatingCountryId"));

                            b1.ToTable("contest_participant", "placeholder", t =>
                                {
                                    t.HasCheckConstraint("CK_contest_participant_semi_final_draw_Enum", "[semi_final_draw] IN ('SemiFinal1', 'SemiFinal2')");
                                });

                            b1.WithOwner()
                                .HasForeignKey("ContestId");
                        });

                    b.Navigation("BroadcastMemos");

                    b.Navigation("GlobalTelevote");

                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
