// <auto-generated />
using System;
using Eurocentric.Components.DataAccess.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eurocentric.Components.DataAccess.EfCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260117135042_Create_placeholder_country_aggregate_tables")]
    partial class Create_placeholder_country_aggregate_tables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Eurocentric.Domain.Aggregates.Placeholders.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("country_id");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .HasColumnName("country_code")
                        .IsFixedLength();

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("country_name");

                    b.Property<string>("CountryType")
                        .IsRequired()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("country_type");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasAlternateKey("CountryCode");

                    b.ToTable("country", "placeholder", t =>
                        {
                            t.HasCheckConstraint("CK_country_country_type_Enum", "[country_type] IN ('Real', 'Pseudo')");
                        });
                });

            modelBuilder.Entity("Eurocentric.Domain.Aggregates.Placeholders.Country", b =>
                {
                    b.OwnsMany("Eurocentric.Domain.Aggregates.Placeholders.ContestRole", "ContestRoles", b1 =>
                        {
                            b1.Property<int>("RowId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasColumnName("row_id");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("RowId"));

                            b1.Property<Guid>("ContestId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("contest_id");

                            b1.Property<string>("ContestRoleType")
                                .IsRequired()
                                .HasMaxLength(14)
                                .IsUnicode(false)
                                .HasColumnType("varchar(14)")
                                .HasColumnName("contest_role_type");

                            b1.Property<Guid>("CountryId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("country_id");

                            b1.HasKey("RowId");

                            b1.HasIndex("CountryId");

                            b1.HasIndex("ContestId", "CountryId")
                                .IsUnique();

                            b1.ToTable("country_contest_role", "placeholder", t =>
                                {
                                    t.HasCheckConstraint("CK_country_contest_role_contest_role_type_Enum", "[contest_role_type] IN ('Participant', 'GlobalTelevote')");
                                });

                            b1.WithOwner()
                                .HasForeignKey("CountryId");
                        });

                    b.Navigation("ContestRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
