using Eurocentric.Features.PublicApi.V1.Common.Constants;
using Eurocentric.Features.PublicApi.V1.Rankings.CompetingCountries.GetCompetingCountryPointsAverageRankings;
using Eurocentric.Features.PublicApi.V1.Rankings.CompetingCountries.GetCompetingCountryPointsConsensusRankings;
using Eurocentric.Features.PublicApi.V1.Rankings.CompetingCountries.GetCompetingCountryPointsInRangeRankings;
using Eurocentric.Features.PublicApi.V1.Rankings.CompetingCountries.GetCompetingCountryPointsShareRankings;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;

namespace Eurocentric.Features.PublicApi.V1.Rankings.CompetingCountries;

/// <summary>
///     Extension methods to be invoked when configuring web application middleware.
/// </summary>
internal static class Middleware
{
    /// <summary>
    ///     Adds the endpoints tagged with "Competing Country Rankings".
    /// </summary>
    /// <param name="builder">The endpoint route builder to which the endpoints are to be added.</param>
    internal static void MapCompetingCountryRankingsEndpoints(this IEndpointRouteBuilder builder)
    {
        RouteGroupBuilder group = builder.MapGroup("rankings/competing-countries")
            .WithTags(EndpointNames.Tags.CompetingCountryRankings)
            .ProducesProblem(StatusCodes.Status400BadRequest);

        group.MapGet("points-average", GetCompetingCountryPointsAverageRankingsFeature.ExecuteAsync)
            .WithName(EndpointNames.Routes.CompetingCountryRankings.GetCompetingCountryPointsAverageRankings)
            .WithSummary("Get competing country points average rankings")
            .WithDescription(
                """
                Returns a page of competing country rankings based on descending points average.

                Points average is a float between 0 and 12, calculated as the average individual points value received by the
                competing country across broadcasts.

                Rankings are generated by:
                - Filtering voting data.
                - Grouping data by competing country.
                - Calculating total points, points award count, and points average.
                - Ranking by descending points average.
                - Sorting by rank (ascending or descending) and country code.
                - Applying pagination.
                """)
            .HasApiVersion(1, 0)
            .Produces<GetCompetingCountryPointsAverageRankingsResponse>();

        group.MapGet("points-consensus", GetCompetingCountryPointsConsensusRankingsFeature.ExecuteAsync)
            .WithName(EndpointNames.Routes.CompetingCountryRankings.GetCompetingCountryPointsConsensusRankings)
            .WithSummary("Get competing country points consensus rankings")
            .WithDescription(
                """
                Returns a page of competing country rankings based on descending points consensus.

                Points consensus is a float between 0 and 1, calculated as the cosine similarity
                between jury and televote points received by the competing country across broadcasts.
                Each voting country in each broadcast acts as a vector dimension in the comparison.

                Rankings are generated by:
                - Filtering voting data.
                - Normalizing points values to a scale from 1.0 to 100.0.
                - Grouping data by competing country.
                - Calculating vector lengths, dot product, and points consensus.
                - Ranking by descending points consensus.
                - Sorting by rank (ascending or descending) and country code.
                - Applying pagination.
                """)
            .HasApiVersion(1, 0)
            .Produces<GetCompetingCountryPointsConsensusRankingsResponse>();

        group.MapGet("points-in-range", GetCompetingCountryPointsInRangeRankingsFeature.ExecuteAsync)
            .WithName(EndpointNames.Routes.CompetingCountryRankings.GetCompetingCountryPointsInRangeRankings)
            .WithSummary("Get competing country points in range rankings")
            .WithDescription(
                """
                Returns a page of competing country rankings based on descending points in range.

                Points in range is a float between 0 and 1, calculated as the frequency of points awards within a given range
                received by the competing country across broadcasts, relative to the number of points awards it received.

                Rankings are generated by:
                - Filtering voting data.
                - Grouping data by competing country.
                - Calculating points award counts and points in range.
                - Ranking by descending points in range.
                - Sorting by rank (ascending or descending) and country code.
                - Applying pagination.
                """)
            .HasApiVersion(1, 0)
            .Produces<GetCompetingCountryPointsInRangeRankingsResponse>();

        group.MapGet("points-share", GetCompetingCountryPointsShareRankingsFeature.ExecuteAsync)
            .WithName(EndpointNames.Routes.CompetingCountryRankings.GetCompetingCountryPointsShareRankings)
            .WithSummary("Get competing country points share rankings")
            .WithDescription(
                """
                Returns a page of competing country rankings based on descending points share.

                Points share is a float between 0 and 1, calculated as the total points received by the competing country across
                broadcasts as a fraction of the maximum available points.

                Rankings are generated by:
                - Filtering voting data.
                - Grouping data by competing country.
                - Calculating total points, available points, and points share.
                - Ranking by descending points share.
                - Sorting by rank (ascending or descending) and country code.
                - Applying pagination.
                """)
            .HasApiVersion(1, 0)
            .Produces<GetCompetingCountryPointsShareRankingsResponse>();
    }
}
