using Azure;
using CSharpFunctionalExtensions;
using Eurocentric.Apis.Public.V1.Config;
using Eurocentric.Apis.Public.V1.Dtos.Listings;
using Eurocentric.Apis.Public.V1.Enums;
using Eurocentric.Components.EndpointMapping;
using Eurocentric.Components.Messaging;
using Eurocentric.Domain.Analytics.Listings;
using Eurocentric.Domain.Core;
using JetBrains.Annotations;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using SlimMessageBus;
using BroadcastResultListing = Eurocentric.Domain.Analytics.Listings.BroadcastResultListing;
using BroadcastResultMetadata = Eurocentric.Domain.Analytics.Listings.BroadcastResultMetadata;
using IResult = Microsoft.AspNetCore.Http.IResult;

namespace Eurocentric.Apis.Public.V1.Features.Listings;

internal static class GetBroadcastResultListings
{
    private static async Task<IResult> ExecuteAsync(
        [AsParameters] GetBroadcastResultListingsRequest request,
        [FromServices] IRequestResponseBus bus,
        CancellationToken ct = default
    ) => await bus.DispatchAsync(request.ToQuery(), MapToOk, ct);

    private static Query ToQuery(this GetBroadcastResultListingsRequest request)
    {
        return new Query
        {
            ContestYear = request.ContestYear,
            ContestStage = request.ContestStage.ToDomainContestStage(),
        };
    }

    private static Ok<GetBroadcastResultListingsResponse> MapToOk(BroadcastResultListings listings)
    {
        (List<BroadcastResultListing> listingsRows, BroadcastResultMetadata metadata) = listings;

        return TypedResults.Ok(
            new GetBroadcastResultListingsResponse(
                listingsRows.Select(listing => listing.ToDto()).ToArray(),
                metadata.ToDto()
            )
        );
    }

    internal sealed class EndpointMapper : IEndpointMapper
    {
        public void MapEndpoint(RouteGroupBuilder routeBuilder)
        {
            routeBuilder
                .MapGet("listings/broadcast-result", ExecuteAsync)
                .WithName(V1EndpointNames.Listings.GetBroadcastResultListings)
                .AddedInVersion1Point0()
                .WithSummary("Get broadcast result listings")
                .WithDescription(
                    """
                    Lists all the results in a specified broadcast.

                    Returns a list of results and a metadata object.

                    Listings are generated by:

                    - Filtering voting data from query parameters.
                    - Listing results.
                    - Sorting results by running order spot (descending).
                    """
                )
                .WithTags(V1Tags.Listings)
                .Produces<Response>()
                .ProducesProblem(StatusCodes.Status400BadRequest);
        }
    }

    internal sealed record Query : BroadcastResultQuery, IQuery<BroadcastResultListings>;

    [UsedImplicitly]
    internal sealed class QueryHandler(IListingsGateway gateway) : IQueryHandler<Query, BroadcastResultListings>
    {
        public async Task<Result<BroadcastResultListings, IDomainError>> OnHandle(Query query, CancellationToken ct) =>
            await gateway.GetBroadcastResultListingsAsync(query, ct);
    }
}
