using CSharpFunctionalExtensions;
using Eurocentric.Apis.Public.V1.Config;
using Eurocentric.Apis.Public.V1.Dtos.Listings;
using Eurocentric.Components.EndpointMapping;
using Eurocentric.Components.Messaging;
using Eurocentric.Domain.Analytics.Listings;
using Eurocentric.Domain.Core;
using JetBrains.Annotations;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using SlimMessageBus;
using CompetingCountryResultListing = Eurocentric.Domain.Analytics.Listings.CompetingCountryResultListing;
using CompetingCountryResultMetadata = Eurocentric.Domain.Analytics.Listings.CompetingCountryResultMetadata;
using IResult = Microsoft.AspNetCore.Http.IResult;

namespace Eurocentric.Apis.Public.V1.Features.Listings;

internal static class GetCompetingCountryResultListings
{
    private static async Task<IResult> ExecuteAsync(
        [AsParameters] GetCompetingCountryResultListingsRequest request,
        [FromServices] IRequestResponseBus bus,
        CancellationToken ct = default
    ) => await bus.DispatchAsync(request.ToQuery(), MapToOk, ct);

    private static Query ToQuery(this GetCompetingCountryResultListingsRequest request) =>
        new() { CompetingCountryCode = request.CompetingCountryCode };

    private static Ok<GetCompetingCountryResultListingsResponse> MapToOk(CompetingCountryResultListings listings)
    {
        (List<CompetingCountryResultListing> listingsRows, CompetingCountryResultMetadata metadata) = listings;

        return TypedResults.Ok(
            new GetCompetingCountryResultListingsResponse(
                listingsRows.Select(listing => listing.ToDto()).ToArray(),
                metadata.ToDto()
            )
        );
    }

    internal sealed class EndpointMapper : IEndpointMapper
    {
        public void MapEndpoint(RouteGroupBuilder routeBuilder)
        {
            routeBuilder
                .MapGet("listings/competing-country-result", ExecuteAsync)
                .WithName(V1EndpointNames.Listings.GetCompetingCountryResultListings)
                .AddedInVersion1Point0()
                .WithSummary("Get competing country result listings")
                .WithDescription(
                    """
                    Lists all the results for a specified competing country.

                    Returns a list of results and a metadata object.

                    Listings are generated by:

                    - Filtering voting data from query parameters.
                    - Compiling result listings.
                    - Sorting listings
                        - by contest year (descending),
                        - then by contest stage (SemiFinal1 < SemiFinal2 < GrandFinal).
                    """
                )
                .WithTags(V1Tags.Listings)
                .Produces<GetCompetingCountryPointsListingsResponse>()
                .ProducesProblem(StatusCodes.Status400BadRequest)
                .ProducesProblem(StatusCodes.Status422UnprocessableEntity);
        }
    }

    internal sealed record Query : CompetingCountryResultQuery, IQuery<CompetingCountryResultListings>;

    [UsedImplicitly]
    internal sealed class QueryHandler(IListingsGateway gateway) : IQueryHandler<Query, CompetingCountryResultListings>
    {
        public async Task<Result<CompetingCountryResultListings, IDomainError>> OnHandle(
            Query query,
            CancellationToken ct
        ) => await gateway.GetCompetingCountryResultListingsAsync(query, ct);
    }
}
