using Azure;
using CSharpFunctionalExtensions;
using Eurocentric.Apis.Public.V1.Config;
using Eurocentric.Apis.Public.V1.Dtos.Listings;
using Eurocentric.Apis.Public.V1.Enums;
using Eurocentric.Components.EndpointMapping;
using Eurocentric.Components.Messaging;
using Eurocentric.Domain.Analytics.Listings;
using Eurocentric.Domain.Core;
using JetBrains.Annotations;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using SlimMessageBus;
using CompetingCountryPointsMetadata = Eurocentric.Domain.Analytics.Listings.CompetingCountryPointsMetadata;
using IResult = Microsoft.AspNetCore.Http.IResult;

namespace Eurocentric.Apis.Public.V1.Features.Listings;

internal static class GetCompetingCountryPointsListings
{
    private static async Task<IResult> ExecuteAsync(
        [AsParameters] GetCompetingCountryPointsListingsRequest request,
        [FromServices] IRequestResponseBus bus,
        CancellationToken ct = default
    ) => await bus.DispatchAsync(request.ToQuery(), MapToOk, ct);

    private static Query ToQuery(this GetCompetingCountryPointsListingsRequest request)
    {
        return new Query
        {
            ContestYear = request.ContestYear,
            ContestStage = request.ContestStage.ToDomainContestStage(),
            CompetingCountryCode = request.CompetingCountryCode,
        };
    }

    private static Ok<GetCompetingCountryPointsListingsResponse> MapToOk(CompetingCountryPointsListings listings)
    {
        (
            List<CompetingCountryPointsListing> juryListings,
            List<CompetingCountryPointsListing> televoteListings,
            CompetingCountryPointsMetadata metadata
        ) = listings;

        return TypedResults.Ok(
            new GetCompetingCountryPointsListingsResponse(
                juryListings.Select(listing => listing.ToJuryPointsDto()).ToArray(),
                televoteListings.Select(listing => listing.ToTelevotePointsDto()).ToArray(),
                metadata.ToDto()
            )
        );
    }

    internal sealed class EndpointMapper : IEndpointMapper
    {
        public void MapEndpoint(RouteGroupBuilder routeBuilder)
        {
            routeBuilder
                .MapGet("listings/competing-country-points", ExecuteAsync)
                .WithName(V1EndpointNames.Listings.GetCompetingCountryPointsListings)
                .AddedInVersion1Point0()
                .WithSummary("Get competing country points listings")
                .WithDescription(
                    """
                    Lists all the points awards received by a specified competing country in a specified broadcast.

                    Returns a list of jury points awards, a list of televote points awards, and a metadata object.

                    Listings are generated by:

                    - Filtering voting data from query parameters.
                    - Listing points awards.
                    - Sorting points awards
                        - by points value (descending)
                        - then by voting country code (ascending).
                    """
                )
                .WithTags(V1Tags.Listings)
                .Produces<Response>()
                .ProducesProblem(StatusCodes.Status400BadRequest)
                .ProducesProblem(StatusCodes.Status422UnprocessableEntity);
        }
    }

    internal sealed record Query : CompetingCountryPointsQuery, IQuery<CompetingCountryPointsListings>;

    [UsedImplicitly]
    internal sealed class QueryHandler(IListingsGateway gateway) : IQueryHandler<Query, CompetingCountryPointsListings>
    {
        public async Task<Result<CompetingCountryPointsListings, IDomainError>> OnHandle(
            Query query,
            CancellationToken ct
        ) => await gateway.GetCompetingCountryPointsListingsAsync(query, ct);
    }
}
