using CSharpFunctionalExtensions;
using Eurocentric.Apis.Public.V1.Config;
using Eurocentric.Apis.Public.V1.Dtos.Listings;
using Eurocentric.Apis.Public.V1.Enums;
using Eurocentric.Components.EndpointMapping;
using Eurocentric.Components.Messaging;
using Eurocentric.Domain.Analytics.Listings;
using Eurocentric.Domain.Core;
using JetBrains.Annotations;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using SlimMessageBus;
using IResult = Microsoft.AspNetCore.Http.IResult;
using VotingCountryPointsMetadata = Eurocentric.Domain.Analytics.Listings.VotingCountryPointsMetadata;

namespace Eurocentric.Apis.Public.V1.Features.Listings;

internal static class GetVotingCountryPointsListings
{
    private static async Task<IResult> ExecuteAsync(
        [AsParameters] GetVotingCountryPointsListingsRequest request,
        [FromServices] IRequestResponseBus bus,
        CancellationToken ct = default
    ) => await bus.DispatchAsync(request.ToQuery(), MapToOk, ct);

    private static Query ToQuery(this GetVotingCountryPointsListingsRequest request)
    {
        return new Query
        {
            ContestYear = request.ContestYear,
            ContestStage = request.ContestStage.ToDomainContestStage(),
            VotingCountryCode = request.VotingCountryCode,
        };
    }

    private static Ok<GetVotingCountryPointsListingsResponse> MapToOk(VotingCountryPointsListings listings)
    {
        (
            List<VotingCountryPointsListing> juryListings,
            List<VotingCountryPointsListing> televoteListings,
            VotingCountryPointsMetadata metadata
        ) = listings;

        return TypedResults.Ok(
            new GetVotingCountryPointsListingsResponse(
                juryListings.Select(listing => listing.ToJuryPointsDto()).ToArray(),
                televoteListings.Select(listing => listing.ToTelevotePointsDto()).ToArray(),
                metadata.ToDto()
            )
        );
    }

    internal sealed class EndpointMapper : IEndpointMapper
    {
        public void MapEndpoint(RouteGroupBuilder routeBuilder)
        {
            routeBuilder
                .MapGet("listings/voting-country-points", ExecuteAsync)
                .WithName(V1EndpointNames.Listings.GetVotingCountryPointsListings)
                .AddedInVersion1Point0()
                .WithSummary("Get voting country points listings")
                .WithDescription(
                    """
                    Lists all the points awards given by a specified voting country in a specified broadcast.

                    Returns a list of jury points awards, a list of televote points awards, and a metadata object.

                    Listings are generated by:

                    - Filtering voting data from query parameters.
                    - Listing points awards.
                    - Sorting points awards
                        - by points value (descending)
                        - then by competing country code (ascending).
                    """
                )
                .WithTags(V1Tags.Listings)
                .Produces<GetVotingCountryPointsListingsResponse>()
                .ProducesProblem(StatusCodes.Status400BadRequest)
                .ProducesProblem(StatusCodes.Status422UnprocessableEntity);
        }
    }

    internal sealed record Query : VotingCountryPointsQuery, IQuery<VotingCountryPointsListings>;

    [UsedImplicitly]
    internal sealed class QueryHandler(IListingsGateway gateway) : IQueryHandler<Query, VotingCountryPointsListings>
    {
        public async Task<Result<VotingCountryPointsListings, IDomainError>> OnHandle(
            Query query,
            CancellationToken ct
        ) => await gateway.GetVotingCountryPointsListingsAsync(query, ct);
    }
}
