# GitHub Action to publish and deploy web app to Azure App Service

name: Publish+Deploy Eurocentric Web App

on:
  push:
    branches:
    - main

env:
  AZURE_WEBAPP_NAME: eurocentric
  AZURE_WEBAPP_PACKAGE_PATH: './publish'

jobs:
  publish_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Install dependencies
        run: dotnet restore ./src/Eurocentric.WebApp/Eurocentric.WebApp.csproj

      - name: Build
        run: dotnet build ./src/Eurocentric.WebApp/Eurocentric.WebApp.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./src/Eurocentric.WebApp/Eurocentric.WebApp.csproj --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}' 
        
